### PR TITLE
Ups! Typo.

### PR DESCRIPTION
**Pull request by santiagopim**
Just tiny typo, but crashed my config loading because I created the file by myself.
Thanks for your work!

### CODE REVIEW

**Comment by Ambrevar** [comment]
Good catch!
Looks like @jmercouris used the wrong spelling here :)

**Comment by Ambrevar** [comment]
When you say it "crashed your config", did it crash the browser, or did Nyxt correctly report the error?

**Comment by santiagopim** [comment]
Nyxt correctly reported the error, very accurate, but was an ugly white page :) Can not reproduce here.
Thanks

**Comment by Ambrevar** [comment]
Indeed, the error page has no styling at all.
We will address this when we work on functional theme management.

**Comment by Ambrevar** [comment]
Thanks for the feedback!

**Pull request merged**
