### PR TITLE
Wip ospama

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Left to do:
- Handle case when no package manager is found.
- Add manifest management for Guix / Nix.
- Add tests.
- Add macports support.

**Comment by Ambrevar** [comment]
This is mostly functional by now.
@jmercouris Wanna give macports a try?

**Comment by Ambrevar** [comment]
Thoughts:

- There seems to be a race condition the first time the buffer is created: the title appears briefly then gets overwritten by the command output.  I can't reproduce reliably and it seems to only happen the first time.

- We could add a `os-package-with-output` class and have `guix-package` (and `nix-package` in the future) inherit from it.  Then, from the client side, we can either check the type of the package object, or write methods for `os-package` and `os-package-with-output` (e.g. when describing the package or  when listing the files.

**Comment by Ambrevar** [comment]
Tests done.

**Comment by jmercouris** [comment]
I will give MacPorts a try :-)

**Comment by Ambrevar** [comment]
OK to merge?  The macports / Nix backends can come later.

**Comment by jmercouris** [comment]
OK to merge!

**Comment by Ambrevar** [comment]
Done with e5d87559145a743776d592fd16e249b2cb8941b6.

**Comment by jmercouris** [comment]
Thank you! This is really great, well done monsieur!

**Pull request closed without merging**
