### PR TITLE
Fix nil browser

### LINKED ISSUE #2670: Always bind `*browser*`
In https://github.com/atlas-engineer/nyxt/pull/2666#discussion_r1031497582 we discussed the problem of having to protect against NIL `*browser*` all over the place.  Then having to extract some default value, which duplicates it since it's already in the slot initforms.

Suggestion: always bind `*browser*` to at least `(make-instance 'browser)`.

I believe this should do the right thing.  Thoughts?

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Follow up to #2671 and #2666.

This ensures `*browser*` is always bound, thus removing a whole class of potential errors.

Fixes #2670.

# Discussion

Can we set `*browser*` at compile time and save it in the image?

# To do:

- [ ] Test!

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [ ] I have pulled from master before submitting this PR
- [ ] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Turns out that instantiating a `browser` right away is not an easy task.
The reason is that `browser` has `nyxt-file` slots, which in turn needs to resolve a profile which is stored either in `*browser*`...  Hence the circularity.

We could break this circularity, but clearly the globality of the profile needs to be better designed somehow.

**Comment by aartaka** [comment]
That's what I meant by side-effects browser instantialion implies! How about the lazy `(current-browser)` solution wrapping around something like `%browser%` special variable? Seems to work for buffers...

**Comment by aartaka** [comment]
> That would not solve the issue: what would `(current-browser)` return at compilation time?

But do we need it at compile-time? Do we need it _that_ early? What's the use-case/bug/problem we're tryign to cover? Even if there's one, we may use `(current-browser)` and instantiate the browser there as well, but this time exactly when it's required to compute it, be it at run-time or compile-time.

> What we are trying to do here is instantiate a browser very early on.

Yes, so I'm suggesting to intantiate it lazily, which kind of implies that it may be initialized really early too, but without the downsides of being initialized _too early_.

**Comment by Ambrevar** [comment]
`*browser*` is needed very early indeed, look at `*default-hostlist*` in blocker-mode: it needs to know the global profile, and thus depends on `*browser*`.

One fix would be to not have the global profile be resolve in browser but separately, like we used to.

So we could partially revert #2666.

**Comment by aartaka** [comment]
> `*browser*` is needed very early indeed, look at `*default-hostlist*` in blocker-mode: it needs to know the global profile, and thus depends on `*browser*`.
> 
> One fix would be to not have the global profile be resolve in browser but separately, like we used to.
> 
> So we could partially revert #2666.

Yes, that sounds sanest.

**Comment by aadcg** [comment]
What's the status here? This might [solve the blocker mentioned in this PR](https://github.com/atlas-engineer/nyxt/pull/2693#issuecomment-1352848266).

**Comment by Ambrevar** [comment]
It's a tough one, so I need to find time to sit down and think through it.  It's high priority, obviously.

**Comment by aadcg** [comment]
No worries @Ambrevar and please ignore my previous comment, since the PR I mentioned has been already merged!

**Comment by jmercouris** [comment]
Please reopen when ready.

**Pull request closed without merging**
