### PR TITLE
Gopher support

### PR DESCRIPTION
**Pull request by aartaka**
This is to show off the Gopher support possible with the help of `cl-gopher`. It works fine in 90% of the cases, but I want to polish it even more.

# What's New
- `gopher:` scheme supported natively.
- Gopher pages displayed and themed in accordance to browser theme and my aesthetic understanding.
- `gopher-mode` to enable on these pages.
- `search-gopher` command to search Gopherspace using the page-local search prompts and the user-configured ones.
  - It's implemented this way because WebKitGTK doesn't seem to support JS redirects to `gopher:` URLs by default (some SecurityManager tinkering can solve this, I suppose). It's convenient and powerful, but quite unintuitive at first.

# Things to Discuss
- How should we lay pages out? Most Gopher clients are terminal-based, and the protocol itself was made to be used with such clients. Full HTML markup gives us a lot of possibilities for layout shuffling there.
- `search-gopher` is almost invisible, so one can get lost not seeing the search prompt on the familiar page.
- Should we display images and other displayable content on the page, or should we stick to the more conservative and lightweight approach of leaving download links?
  - I've gone with displaying media, but there could be strong arguments in favor of not displaying it, given the overall nature of Gopher.

# Things to Do
- Support more line types.
- Package `cl-gopher` for Guix and Nix. @Ambrevar, @jmercouris, could you help with this?

# Testing
- Simply build Nyxt and navigate to the Gopherspace page you like (for example `gopher://sdf.org/`), no additional setup required :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Wow, fantastic work!  I'll test in a little while.

I think the SBCL tests fail because you haven't added the cl-gopher submodule.

**Comment by aartaka** [comment]
> I think the SBCL tests fail because you haven't added the cl-gopher submodule.

Yes, that I didn't add yet. Will do!

**Comment by jmercouris** [comment]
I can't exactly patch `cl-gopher` for Nix, my PRs are never merged :-D

I presume next time Nyxt is updated in Nix, it will be added.

**Comment by jmercouris** [comment]
I shall test and see if I can do some styling in the coming days. Thanks for this PR Artyom, I am very much looking forward to it!

**Comment by Ambrevar** [comment]
cl-gopher is now in Guix!

**Comment by aartaka** [comment]
Thanks, Pierre! One day, I'd get accustomed to the email-based contributing workflow...

**Comment by boehs** [comment]
aartaka, you should consider https://nyxt.atlas.engineer/contact-work if you have not already!

**Comment by jmercouris** [comment]
I thought `cl-gopher` was now in Guix, why is the CI still failing?

**Comment by jmercouris** [comment]
To update, the coming day is Monday, I would like to do some Gopher styling today.

**Comment by aartaka** [comment]
> I thought `cl-gopher` was now in Guix, why is the CI still failing?

CI was failing because I didn't add `cl-gopher` to Nyxt inputs. Just added it, it should work now!

**Comment by aartaka** [comment]
Gopher support is more or less complete, but some parts of it (like `gopher-search` scheme and making `gopher:` an internal scheme) are hack-ish and I'de better not have those. 

Fixing them requires patching `cl-gopher` as per https://github.com/knusbaum/cl-gopher/pull/1 and https://github.com/knusbaum/cl-gopher/pull/2. Should we wait for knusbaum to respond or fork the (supposedly) abandoned library?

**Comment by jmercouris** [comment]
I'm happy with the appearance for now. I would like the quaternary color to be lighter, but alea iacta est!

**Comment by jmercouris** [comment]
Feel free to merge this when the tests pass!

**Comment by aartaka** [comment]
No, it's not ready. Things to do before merging:
- Fix all the bugs I've contributed to cl-gopher xD
- Prevent broken and slow Gopher servers handing Nyxt.
- Ensure all line types are either supported or explicitly ignored.

**Comment by jmercouris** [comment]
OK, then we leave it until you feel it is ready for alpha!

**Comment by aartaka** [comment]
@Ambrevar, would you mind updating `cl-gopher` on Guix? :)

**Comment by Ambrevar** [comment]
Done!

**Comment by aartaka** [comment]
Merging then!

**Pull request merged**
