### PR TITLE
history: Make history restoration more lenient to unknown symbols.

### LINKED ISSUE #2523: Migrating from 2.* to 3.* wipes history
**Describe the bug**

I revisited nyxt for the first time in a while and so built nyxt-3 from master and fired it up:
```
nyxt -I
```
On load there was a warning:
```
<WARN> [14:57:04] Warning: Failed to restore history from /home/fran/.local/share/nyxt/history/default.lisp: Symbol &quot;CURRENT-OWNER-ID&quot; not found in the HISTORY-TREE package. Line: 1580, Column: 14, File-Position: 163363 Stream: #&lt;SB-SYS:FD-STREAM for &quot;file /home/fran/.local/share/nyxt/history/default.lisp&quot; {100A8522B3}&gt;
```
and, sure enough, my old session from way back was not restored.  I opened a site or two and then quit.

I then fired nyxt again and this time the session was restored with the site or two I had opened.  On investigation, I discovered that the history file
```
/home/fran/.local/share/nyxt/history/default.lisp
```
had been completely overwritten and my old history wiped.

While I expected some friction after such a long time since I last tried nyxt, silently wiping the history is a little unfriendly!

**Information**
- OS name+version: Debian 11
- Graphics card and driver:
- Desktop environment / Window manager name+version: exwm
- How you installed Nyxt (Guix pack, package manager, build from source): source
- Information from `show-system-information`:
Nyxt version: 3-pre-release-1-273-g5dfb8039
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.0-17-amd64
Lisp implementation: SBCL 2.1.1 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.36 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-3 :CUSTOM-HASH-TABLE-NATIVE :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :FSET-EXT-STRINGS :GLOBAL-VARS :DECLARE-TYPES :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :SWANK :LPARALLEL :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/home/fran/common-lisp/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd /home/fran/common-lisp/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd /home/fran/common-lisp/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

**Output when started from a shell**
(sbcl:38775): Gtk-WARNING **: 14:57:04.322: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
Nyxt version 3-pre-release-1-273-g5dfb8039
<INFO> [14:57:04] Source location: #P"/home/fran/common-lisp/nyxt/"
<INFO> [14:57:04] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
<INFO> [14:57:04] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"
<INFO> [14:57:04] Loading #P"/home/fran/.local/share/nyxt/history/default.lisp".
<WARN> [14:57:04] Warning: Failed to restore history from /home/fran/.local/share/nyxt/history/default.lisp: Symbol &quot;CURRENT-OWNER-ID&quot; not found in the HISTORY-TREE package. Line: 1580, Column: 14, File-Position: 163363 Stream: #&lt;SB-SYS:FD-STREAM for &quot;file /home/fran/.local/share/nyxt/history/default.lisp&quot; {100A8522B3}&gt;
<INFO> [14:57:04] GTK extensions directory: #P"/home/fran/common-lisp/nyxt/libraries/web-extensions/"

(WebKitWebProcess:38832): Gtk-WARNING **: 14:57:04.853: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38832): Gtk-WARNING **: 14:57:04.943: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38861): Gtk-WARNING **: 14:57:05.069: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38864): Gtk-WARNING **: 14:57:05.109: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38861): Gtk-WARNING **: 14:57:05.160: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:38864): Gtk-WARNING **: 14:57:05.194: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
<INFO> [14:57:16] Loading #P"/home/fran/.local/share/nyxt/bookmarks.lisp".

(WebKitWebProcess:39263): Gtk-WARNING **: 14:57:16.790: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:39263): Gtk-WARNING **: 14:57:16.872: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
<INFO> [14:57:30] Loading "https://duckduckgo.com/?q=twistor%20theory".
<INFO> [14:57:33] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
WARNING:
   Attributes of #<WINDOW 1033 {1010547A13}> should be a non-dotted alist instead of (("ID"
                                                                                       1033)
                                                                                      ("Active buffer"
                                                                                       "twistor theory at DuckDuckGo"))
<INFO> [14:58:08] Dark mode enabled.
<INFO> [15:00:14] Emacs mode enabled.
<INFO> [15:00:23] Pressed keys: C-x
<INFO> [15:01:35] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:37] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:45] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:46] Finished loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:49] Loading "https://duckduckgo.com/?q=twistor+theory&ia=web".
<INFO> [15:01:49] Loading "https://duckduckgo.com/l/?uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTwistor_theory&notrut=duckduck_in".
<INFO> [15:01:49] Finished loading "https://duckduckgo.com/l/?uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FTwistor_theory&notrut=duckduck_in".
<INFO> [15:01:51] Finished loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:11] Dark mode disabled.
<INFO> [15:02:14] Loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:15] Finished loading "https://en.wikipedia.org/wiki/Twistor_theory".
<INFO> [15:02:25] Pressed keys: C-x

(WebKitWebProcess:50271): Gtk-WARNING **: 15:02:26.681: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()

(WebKitWebProcess:50271): Gtk-WARNING **: 15:02:26.763: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
; in:
;      LAMBDA (&KEY (NYXT/BUFFER-LISTING-MODE::CLUSTER NIL) NYXT/BUFFER-LISTING-MODE::LINEAR-VIEW-P)
;     (NYXT:DELETE-BUFFER :BUFFER NYXT:BUFFER)
; 
; caught STYLE-WARNING:
;   :BUFFER is not a known argument keyword.
; 
; compilation unit finished
;   caught 1 STYLE-WARNING condition
<INFO> [15:40:39] Deleting socket #P"/run/user/1000/nyxt/nyxt.socket".

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Self-explanatory.

Fixes #2523.

# Discussion

This only handle read errors.  Can we be more general?  Do we want to?
@aartaka 

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [ ] I have pulled from master before submitting this PR
- [ ] There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [ ] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Don't merge now, the tests may be broken.

**Comment by aartaka** [comment]
No, this doesn't look right. How about exporting the offending symbols from the `htree` instead? `s-serialization` seems to handle the non-existent slots graciously, so we only have to export a symbol so that the reader doesn't shout at ut.

We can actually export these symbols in the `reader-error` handler, so that we get both error tolerance and backwards-compatibility.

**Comment by Ambrevar** [comment]
> How about exporting the offending symbols from the `htree` instead?

What do you mean?

If you mean something like reverting https://github.com/atlas-engineer/nyxt/commit/ac3f55fbbeb714a204917e0f074016512b1ac872, then I disagree: it's too local and not future-proof.

My proposal is general enough I believe.  What does not seem right in your opinion?

> We can actually export these symbols in the `reader-error` handler, so that we get both error tolerance and backwards-compatibility.

Now I'm very confused... What are you trying to achieve?

**Comment by aartaka** [comment]
~~Okay, so the problem we have is:~~
- ~~There are symbols for things in `htree` that are long removed.~~
- ~~When Lisp reader tries to read the old history file, it rightfully complains that there's no such symbol in `htree'.~~
- ~~It raises a `reader-error`, thus preventing `s-serialization` and `nfiles` to do their work.~~
- ~~Then, to fix this problem, we should rather `intern` the offending symbol into `htree` so that it's perfectly readable again.~~
- ~~Using `continue` is fine and less of an effort...~~

Hmmmm, wiat, `reader-error` does not give us access to to the object we're reading (unlike `print-non-readable`), and thus we cannot control what the offending symbol it. Then the fix is okay!

**Comment by Ambrevar** [comment]
Nit: It's not hindering `s-serialization` but `s-deserialization`.

You are suggestion to intern the symbol, which pollutes the environment and forwards the issue.

My fix _discards_ the symbol, thus the deserialization effectively acts as if the offending symbol weren't there at all.  This seems better, doesn't it?

**Comment by aartaka** [comment]
Your fix is more reasonable here, yes!

**Comment by Ambrevar** [comment]
Merged with 6a38399ce88294dee728fe4d0e0dd0c2ad04c15f.

**Pull request closed without merging**
