### PR TITLE
build-scripts/guix: Add submodule files to sources.

### PR DESCRIPTION
**Pull request by jellelicht**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Guix does not need the submodules since all libraries are included (cluffer, etc.).
Did you run into a problem when building the package with Guix?

**Comment by jellelicht** [comment]
Without this change, I get:
`guix build -f build-scripts/guix.scm`

```
starting phase `build'
make application
make[1]: Entering directory '/tmp/guix-build-nyxt-0.0.0.drv-0/source'
false && \
env NYXT_INTERNAL_QUICKLISP=false sbcl --no-userinit --non-interactive \
	--eval '(require "asdf")' \
	--eval '(when (string= (uiop:getenv "NYXT_INTERNAL_QUICKLISP") "true") (load "quicklisp-client/setup.lisp"))' \
	--eval '(ql:quickload :swank)' \
	--eval '(load (merge-pathnames  "contrib/swank-asdf.lisp" swank-loader:*source-directory*))' \
	--eval '(swank:delete-system-fasls "nyxt")' \
	--eval '(uiop:quit)' || true
make[1]: *** No rule to make target 'quicklisp-client/setup.lisp', needed by 'quicklisp-update'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/guix-build-nyxt-0.0.0.drv-0/source'
make: *** [Makefile:38: nyxt] Error 2
command "make" "-j" "2" "nyxt" "NYXT_INTERNAL_QUICKLISP=false" "DESTDIR=/gnu/store/vdnj4nv0b134r3gh5jqgibjb35nchcbq-nyxt-0.0.0" "PREFIX=" failed with status 2
builder for `/gnu/store/y6d2h5y0ca6lkx1n15f5vb8ij57xc3ss-nyxt-0.0.0.drv' failed with exit code 1
build of /gnu/store/y6d2h5y0ca6lkx1n15f5vb8ij57xc3ss-nyxt-0.0.0.drv failed
View build log at '/var/log/guix/drvs/y6/d2h5y0ca6lkx1n15f5vb8ij57xc3ss-nyxt-0.0.0.drv.bz2'.
guix build: error: build of `/gnu/store/y6d2h5y0ca6lkx1n15f5vb8ij57xc3ss-nyxt-0.0.0.drv' failed
```

which makes sense, because setup.lisp is now part of a submodule :smile:

**Comment by Ambrevar** [comment]
This is a bug in the Makefile, the Guix build does not rely on Quicklisp.
I'll work on it.

**Comment by Ambrevar** [comment]
Should be fixed with 
66e3ead410b334b2cd1a9cb457b1c7892d409fe4.  Let me know if it works for you.

**Comment by jellelicht** [comment]
It seems to do the trick, thanks!
Perhaps some form of CI could be set up to verify that things still build?

**Comment by Ambrevar** [comment]
I'm hard at work on the CI at the moment ;)

If you know your way around the GitHub CI + Guix and GitHub CI + Lisp,
any help would be very much appreciated! :)

**Pull request closed without merging**
