### PR TITLE
nyxt.asd: Test subsystems.

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Enable testing of all Nyxt subsystems.

# Discussion

- I suppose that they were simply forgotten.  Let me know if there is any good reason not to test them.
- `analysis` has some broken tests.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [x] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [ ] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aadcg** [comment]
@Ambrevar I think we could make up the case for both opinions.

On the one hand, those subsystems are independent and, as such, they should tested on their own. For instance, you don't test `nfiles` everytime you make a change to `nyxt` right?  When I work on `nyxt/theme`, I always test that system on its own.

On the other hand, it certainly doesn't hurt.

I'd lean towards not accepting this change but, honestly, I don't think it's a big deal.

**Comment by Ambrevar** [comment]
@jmercouris `analysis` `test-variable-length` is broken, can you look into it?

**Comment by Ambrevar** [comment]
Rationale for enabling the tests: unlike Nfiles & friend that stand on their own and have a CI, `analysis` and friends' test are never run under the CI, and thus it's too easy to forget to test if no one does it locally.

**Review by aartaka — APPROVED** [review]

**Review by aadcg — APPROVED** [review]

**Comment by Ambrevar** [comment]
DO NOT MERGE: Analysis tests are broken.

**Comment by Ambrevar** [comment]
@jmercouris Friendly ping! :)

**Comment by Ambrevar** [comment]
@jmercouris Re-friendly ping! :)

**Comment by jmercouris** [comment]
I'm sorry, i keep forgetting. I swear it's not on purpose!

**Comment by jmercouris** [comment]
Interestingly they seem to pass on master with SBCL... not sure what's going on here.

**Comment by jmercouris** [comment]
I did not, still fails with CCL without uncommenting those snippets

**Comment by jmercouris** [comment]
OK with me.

**Pull request merged**
