### PR TITLE
Fix buttons

### PR DESCRIPTION
**Pull request by jmercouris**
Fixes: #3099

Screenshot_20230730_004558

### CODE REVIEW

**Comment by jmercouris** [comment]
And here is on hover
Screenshot_20230730_004625

**Comment by jmercouris** [comment]
Indeed, also got to make sure it works on dark theme and that the color of the SVG can be changed! I think it can, just have to test.

**Review by aartaka — APPROVED** [review]
Oh, so the design is finalized now! Even though I still feel strange about the rounded lines, it's a progress that I can't deny :upside_down_face: All good!

**Review by lansingthomas — APPROVED** [review]

**Comment by jmercouris** [comment]
Screenshot_20230801_023846

**Comment by lansingthomas** [comment]
@jmercouris 

Yay dark theme!

- [ ] can the tile be purple too?

I know you mentioned doing the color change programmatically, and here is a purple version in case it helps.

tile component purple action

**Pull request merged**
