### PR TITLE
proxy-mode: fix proxy setting example

### PR DESCRIPTION
**Pull request by Zwo1in**
Hi,
as mentioned in #1088, I got an error launching nyxt with example from proxy-mode help. I've managed to configure it like in this commit. I don't know lisp and have no idea what am I doing, so please correct me if the problem was on my side :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks for the feedback!

The issue is not with the documentation however, but with a symbol not being exported properly.
This should be fixed with 3fd79a0639f0fe897ade563badaa4feca2614260, can you confirm?

**Comment by Ambrevar** [comment]
Actually, 3fd79a0639f0fe897ade563badaa4feca2614260 might be broken, so test the latest commit instead.

**Comment by Zwo1in** [comment]
Yes, indeed, on latest master I can see the config based on original documentation parsed with no issues. It does not work as I would expect tho.
What I was expecting was that after turning vpn on, I would need to manually enable `proxy-mode` for each buffer that I'd like to use proxy to be able to reach desired websites.
What I found is that I don't need to enable `proxy-mode`. Each website I was trying to reach was accessible, it didn't matter whether the website was internal to the in-corpo network or external like youtube or this github etc. Maybe this is a desired behavior, but I wasn't aware of it (cool feature if it is by design btw :)).
Just for completenes, I didn't enable any addition of `proxy-mode` to `auto-mode` etc, the change that's visible in this PR is the only thing I have in my config (reverted to origin for this test puropses ofc).

**Comment by Zwo1in** [comment]
One more thing that I thing I should mention. When not under vpn, this proxy setting would result in no webste being accessible, and this is what happens when I explicitely set `proxy-mode` with no vpn. Not setting it explicitely results in each website accessible anytime, so it acts 'smartly'. That's why I said that's a cool feature if it's by design.
I'm sure that this proxy setting is used automatically under vpn, as normally my corpo blacklists sites like youtube and the only way of accessing those under vpn is using socks5 proxy.

**Comment by Zwo1in** [comment]
I've closed this, but please let me know whether this was desired :)

**Comment by Zwo1in** [comment]
In my config there is literally only this proxy setting that I was changing in this PR.

It makes sense, that means that I have some 'system network settings' that allows this connection. Setting `proxy-mode` results in much faster connections, so everythings seems to be working. I have no idea what are my 'system network settings', maybe I did there something years ago that make this working :) Anyway, PEBKAC, let's leave this topic, I'm completely fine with the outcome, thanks!

**Comment by Ambrevar** [comment]
Which desktop environment are you using?
Also check the output of `env | grep -E 'HTTPS?_PROXY'`.

**Comment by Zwo1in** [comment]
I'm using awesome wm.
My environment is clean:
```
~
❯ env | rg -i proxy

~
❯                  
```

Indeed when in firefox I check `Use system proxy settings`, the youtube is working also.

**Comment by Ambrevar** [comment]
Are you using the system of some corporate environment?  If so, the
proxy settings might have been preconfigured somehow.  You may want to
ask your system administrator.

**Pull request closed without merging**
