### PR TITLE
Move the extensions catalog to a command.

### PR DESCRIPTION
**Pull request by aadcg**
# Description

In the context of 709a6392d, I went ahead and made the migration.

# Checklist:

- [x] Git branch state is mergable.
- [x] Changelog is up to date (via a separate commit).
- [x] New dependencies are accounted for.
- [x] Documentation is up to date.
- [x] Compilation and tests (`(asdf:test-system :nyxt/<renderer>)`)
  - No new compilation warnings.
  - Tests are sufficient.

### CODE REVIEW

**Comment by jmercouris** [comment]
Not sure how I feel about this change. Unless we have a repository in which we persist caches of the extensions, they could move or disappear at any time. Shall I set-up a cache?

**Comment by aadcg** [comment]
After talking with @jmercouris, we decided that there the contents of the command will be populated via an endpoint from Nyxt's website.

No need for mirroring the extension under our belt.

Converting to draft.

**Comment by jmercouris** [comment]
The website has been updated with the code to make it possible, additionally, I have added one extension so far for the purposes of testing:

`https://nyxt-browser.com/api/extensions`

if you want the API changed, please let me know.

**Comment by aadcg** [comment]
@jmercouris looks perfect. I really like this idea to have a single point of truth coming from the website and feeding the codebase with it. Thanks!

If you'd like to finish the task, please go ahead. Otherwise, I'll get to it sooner or later.

**Comment by jmercouris** [comment]
OK!

**Comment by aadcg** [comment]
Closed via #3457.

**Pull request closed without merging**
