### PR TITLE
mode/visual: Refactor into caret-action helper

### PR DESCRIPTION
**Pull request by hendursaga**
Simple code de-duplication.

### CODE REVIEW

**Comment by aartaka** [comment]
The way I'd refactor it: rename the `action` arg to `extend-p`  and pass `(mark-set mode)`. Does it feel better to you?

**Comment by hendursaga** [comment]
@aartaka that's an idea; however, keep in mind `action` represents `alter` in the [parameters documented here](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify#parameters). Honestly, though, `alter` seems like a poor choice for an argument name, but seeing as they're not passed via ParenScript as keyword/named arguments.. what matters is whether or not :extend or :move is passed. I was thinking of refactoring further using typed enums, so I think this commit needs no further modifications.

**Comment by aartaka** [comment]
> @aartaka that's an idea; however, keep in mind `action` represents `alter` in the [parameters documented here](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify#parameters). Honestly, though, `alter` seems like a poor choice for an argument name, but seeing as they're not passed via ParenScript as keyword/named arguments.. what matters is whether or not :extend or :move is passed. I was thinking of refactoring further using typed enums, so I think this commit needs no further modifications.

Does make sense, thanks for the explanation!

**Comment by aartaka** [comment]
Thanks for the patch @hendursaga!

**Pull request merged**
