### PR TITLE
Adjust Nyxt JS usage to CL-WebKit 3.0.

### PR DESCRIPTION
**Pull request by aartaka**
This changes all the places that we call JS in to use Lispy return values of `cl-webkit` 3.0. Merge after https://github.com/joachifm/cl-webkit/pull/59 is merged to `cl-webkit`.

### CODE REVIEW

**Comment by aartaka** [comment]
Importantly, DOM parsing still returns strings, because it's magnitudes faster this way.

**Comment by Ambrevar** [comment]
Also got to update the Guix package before the next version release.

I think I'll define the 3.0 version of cl-webkit in Nyxt's guix.scm in the mean time.

**Comment by Ambrevar** [comment]
I tried this recipe;

```scheme
(define-public sbcl-cl-webkit
  (package
    (name "sbcl-cl-webkit")
    (version "3.0")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/joachifm/cl-webkit")
             (commit version)))
       (file-name (git-file-name "cl-webkit" version))
       (sha256
        (base32
         "015xry1cvbgspfzz35ifz2qscz946ljhj2z8rzjscy9v8fgnjsdk"))))
    (build-system asdf-build-system/sbcl)
    (inputs
     `(("cffi" ,sbcl-cffi)
       ("cl-cffi-gtk" ,sbcl-cl-cffi-gtk)
       ("webkitgtk" ,webkitgtk)))
    (native-inputs
     `(("calispel" ,sbcl-calispel)
       ("fiveam" ,sbcl-fiveam)
       ("float-features" ,sbcl-float-features)))
    (arguments
     `(#:asd-systems '("cl-webkit2")
       #:phases
       (modify-phases %standard-phases
         (add-after 'unpack 'fix-paths
           (lambda* (#:key inputs #:allow-other-keys)
             (substitute* "webkit2/webkit2.init.lisp"
               (("libwebkit2gtk" all)
                (string-append
                 (assoc-ref inputs "webkitgtk") "/lib/" all))))))))
    (home-page "https://github.com/joachifm/cl-webkit")
    (synopsis "Binding to WebKitGTK+ for Common Lisp")
    (description
     "@command{cl-webkit} is a binding to WebKitGTK+ for Common Lisp,
currently targeting WebKit version 2.  The WebKitGTK+ library adds web
browsing capabilities to an application, leveraging the full power of the
WebKit browsing engine.")
    (license license:expat)))
```

I get this error during the `check` phase:

```log
; processing (DEFVAR *CAN-RUN-TESTS-CHANNEL* ...)
; processing (DEFUN RUN-TESTS ...)

; wrote /gnu/store/7d93f5ldiz3h8iclnwz834rg9d1m4s2x-sbcl-cl-webkit-3.0/lib/common-lisp/sbcl/cl-webkit/webkit2/tests/tests-tmpAAURSO1.fasl
; compilation finished in 0:00:00.008

(sbcl:20): Gtk-CRITICAL **: 07:44:22.570: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(sbcl:20): Gtk-CRITICAL **: 07:44:22.570: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(sbcl:20): Gtk-CRITICAL **: 07:44:22.570: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
CORRUPTION WARNING in SBCL pid 20 tid 22:
Memory fault at 0x18 (pc=0x7ffff61cf940, fp=0x7ffff6686540, sp=0x7fffed7f5ba8) tid 22
The integrity of this image is possibly compromised.
Continuing with fingers crossed.
Unhandled SB-SYS:MEMORY-FAULT-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                                 {10099453B3}>:
  Unhandled memory fault at #x18.

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10099453B3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-SYS:MEMORY-FAULT-ERROR {1009A42183}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-SYS:MEMORY-FAULT-ERROR {1009A42183}>)
2: (INVOKE-DEBUGGER #<SB-SYS:MEMORY-FAULT-ERROR {1009A42183}>)
3: (ERROR SB-SYS:MEMORY-FAULT-ERROR :ADDRESS 24)
4: (SB-SYS:MEMORY-FAULT-ERROR #<unused argument> #.(SB-SYS:INT-SAP #X00000018))
5: ("foreign function: call_into_lisp")
6: ("foreign function: funcall2")
7: ("foreign function: handle_memory_fault_emulation_trap")
8: ("foreign function: handle_trap")
9: ("foreign function: #x41925E")
10: (GOBJECT::CALL-GOBJECT-CONSTRUCTOR "GtkWindow" NIL NIL NIL)
11: (GOBJECT::CREATE-GOBJECT-FROM-CLASS #<GOBJECT:GOBJECT-CLASS GTK:GTK-WINDOW> NIL)
12: ((:METHOD MAKE-INSTANCE (GOBJECT:GOBJECT-CLASS)) #<GOBJECT:GOBJECT-CLASS GTK:GTK-WINDOW>) [fast-method]
13: ((LAMBDA NIL :IN WEBKIT2/TESTS::RUN-TESTS))
14: ((LAMBDA (GTK::DATA) :IN "/gnu/store/d5c1c8gnp3qal5ka37n2287cm56dsil4-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/gtk/gtk.init.lisp") #.(SB-SYS:INT-SAP #X00000002))
15: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/gnu/store/d5c1c8gnp3qal5ka37n2287cm56dsil4-sbcl-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/sbcl/cl-cffi-gtk/glib/glib.main-loop.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
16: ("foreign function: funcall_alien_callback")
17: ("foreign function: callback_wrapper_trampoline")
18: ("foreign function: #x50101CF2")
19: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
20: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
25: (SB-THREAD::RUN)
26: ("foreign function: call_into_lisp")
27: ("foreign function: funcall1")

```

Any idea?

**Comment by aartaka** [comment]
Errors the same on my machine 0_o

**Comment by aartaka** [comment]
Looks like a problem we cannot influence -- it's GtkWindow creation that errors. Maybe disable tests and leave them for manual runs?

As a side-note, try running tests on your machine. Do those return a results? They somewhy don't return on my machine, so maybe it's me missing something in FiveAM documentation...

**Comment by Ambrevar** [comment]
I tried to get the tests to work by starting an X server:

```scheme
(define-public sbcl-cl-webkit
  (package
    (name "sbcl-cl-webkit")
    (version "3.0.0")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/joachifm/cl-webkit")
             (commit version)))
       (file-name (git-file-name "cl-webkit" version))
       (sha256
        (base32
         "015xry1cvbgspfzz35ifz2qscz946ljhj2z8rzjscy9v8fgnjsdk"))))
    (build-system asdf-build-system/sbcl)
    (inputs
     `(("cffi" ,sbcl-cffi)
       ("cl-cffi-gtk" ,sbcl-cl-cffi-gtk)
       ("webkitgtk" ,webkitgtk)))
    (native-inputs
     `(("calispel" ,sbcl-calispel)
       ("fiveam" ,sbcl-fiveam)
       ("float-features" ,sbcl-float-features)
       ("xorg-server" ,xorg-server-for-tests)))
    (arguments
     `(#:asd-systems '("cl-webkit2")
       #:phases
       (modify-phases %standard-phases
         (add-after 'unpack 'fix-paths
           (lambda* (#:key inputs #:allow-other-keys)
             (substitute* "webkit2/webkit2.init.lisp"
               (("libwebkit2gtk" all)
                (string-append
                 (assoc-ref inputs "webkitgtk") "/lib/" all)))))
         (add-before 'check 'start-xorg-server
           (lambda* (#:key inputs #:allow-other-keys)
             ;; The test suite requires a running X server.
             (system (string-append (assoc-ref inputs "xorg-server")
                                    "/bin/Xvfb :1 &"))
             (setenv "DISPLAY" ":1")
             #t)))))
    (home-page "https://github.com/joachifm/cl-webkit")
    (synopsis "Binding to WebKitGTK+ for Common Lisp")
    (description
     "@command{cl-webkit} is a binding to WebKitGTK+ for Common Lisp,
currently targeting WebKit version 2.  The WebKitGTK+ library adds web
browsing capabilities to an application, leveraging the full power of the
WebKit browsing engine.")
    (license license:expat)))
```

This time it does not error, but the check phase hangs.

Disabling the tests works.

**Comment by Ambrevar** [comment]
The reason the tests don't return is because we call `(gtk:join-gtk-main)` before `(gtk:gtk-main-quit)`.  But join waits on quit, so this cannot work.

Removing `(gtk:join-gtk-main)` fixes it and it may fix the test suit on Guix too.

**Comment by aartaka** [comment]
Yes, tests return nicely after removing `join-gtk-main`. Guix recipe errors even with this change, though.

**Comment by Ambrevar** [comment]
What error do you have?

**Comment by aartaka** [comment]
Same as before, the one with "Unhandled memory fault at #x18."

**Comment by Ambrevar** [comment]
Wait, did you try my new recipe with the Xorg server?

**Comment by aartaka** [comment]
Tried with Xorg server and latest cl-webkit commit. No memory faults, but hangs for indefinite time.

**Comment by Ambrevar** [comment]
Any idea where it hangs?

**Comment by Ambrevar** [comment]
Wait, doesn't it break backward compatibility?

If we want to give such a guarantee to Nyxt users, we should pin all dependencies, shouldn't we?

**Comment by jmercouris** [comment]
Yes, we should pin dependencies and probably merge this in with 3.0.0, no?

**Comment by Ambrevar** [comment]
I lean towards that too.

See https://github.com/atlas-engineer/nyxt/issues/1427.

**Comment by aartaka** [comment]
The only exported thing that changed behavior is `ffi-buffer-evaluate-javascript`. The last time we discussed it with John, we concurred on the idea that it's fine for the minor release (e.g. `2.2` or `2.3`). 

If it's also about the dependencies, then yes, it's backwards-incompatible.

**Comment by Ambrevar** [comment]
> The only exported thing that changed behavior is `ffi-buffer-evaluate-javascript`. The last time we discussed it with John, we concurred on the idea that it's fine for the minor release (e.g. `2.2` or `2.3`). 

Can you explain the rationale?

**Comment by aartaka** [comment]
The rationale was that it's not much of a visible change, mostly an internal one, as far as I remember.

**Comment by jmercouris** [comment]
Ah, whoops, my bad then :-D

sometimes I wish my memory was better!

**Comment by jmercouris** [comment]
I still think we should pin the version in our ASDF file. That seems to be the best approach.

**Comment by Ambrevar** [comment]
> I still think we should pin the version in our ASDF file. That seems to be the best approach.

It's not enough, because Quicklisp does not distribute arbitrary
versions as far as I can tell.

If we pin the version in the ASD, then we must distribute the said
versions, for instance as Git submodules.

But then, if we distribute the dependencies, the ASD version information
is redundant.

Also ASDF does not support Git commits as versions, and many CL
libraries don't have version numbers, so it would be effectively
impossible to specify the version numbers in the ASD.

**Comment by Ambrevar** [comment]
I'll work on the Git submodules as soon as possible.

**Comment by jmercouris** [comment]
Then your conclusions is correct, we'll have to bring back the submodule for cl-webkit...

**Comment by Ambrevar** [comment]
We've never removed it! ;)

**Comment by jmercouris** [comment]
Ah, well then... no problem :-D!

**Comment by Ambrevar** [comment]
The tests ahn with

```
Running test suite WEBKIT-TESTS
 Running test suite JS-TESTS
  Running test JSON-VALUES ffffff
  Running test BACK-AND-FORTH .
  Running test UNDEFINED .
  Running test NULL f
  Running test NULL-AS-NIL f
  Running test FALSE f
  Running test FALSE-AS-KEYWORD f
  Running test TRUE f
  Running test TRUE-AS-KEYWORD f
  Running test INTEGERS X
  Running test SPECIAL-NUMBERS X
  Running test FRACTIONAL-NUMBER X
  Running test PERIODIC-NUMBER X
  Running test SIMPLE-STRING f
  Running test ESCAPED-STRING f
  Running test TEMPLATED-STRING f
  Running test CONCATENATED-STRING f
  Running test SIMPLE-ARRAY fff
  Running test EVERYTHING-ARRAY f
  Running test EVERYTHING-ARRAY-VECTOR f
  Running test SINGLE-FIELD-OBJECT f
  Running test LONG-OBJECT f
  Running test EVERYTHING-OBJECT f
  Running test EVERYTHING-OBJECT-HASH fX
  Running test EVERYTHING-OBJECT-PLIST f
  Running test ZERO-FN X

(process:87): GLib-GIO-ERROR **: 07:54:06.387: Settings schema 'org.gnome.system.proxy' is not installed
```

My guess is this is because of

```lisp
(webkit2:webkit-web-view-load-uri view "http://www.example.com")
```

Can we run the tests on about:blank instead?
Then we would need no network and the tests might pass.

**Comment by aartaka** [comment]
Done. I cannot reproduce test fails with my WiFi turned off, will try again later.

**Comment by Ambrevar** [comment]
Same.  Actually the tests work without this line:

```lisp
(webkit2:webkit-web-view-load-uri view "http://www.example.com")
```

I suggest to remove it.

I guess it's OK to have a Guix package with tests disabled for now.  My suspicion goes towards an issue with Xorg.

Let's merge this then?

**Comment by Ambrevar** [comment]
I'll add a `Minor backward incompatilities` section to the change log.

**Comment by aartaka** [comment]
> Same. Actually the tests work without this line:
> 
> ```lisp
> (webkit2:webkit-web-view-load-uri view "http://www.example.com")
> ```
> 
> I suggest to remove it.
> 
> I guess it's OK to have a Guix package with tests disabled for now. My suspicion goes towards an issue with Xorg.
> 
> Let's merge this then?

Yep.

**Comment by aartaka** [comment]
> I'll add a `Minor backward incompatilities` section to the change log.

Thanks for that :)

**Comment by Ambrevar** [comment]
Merged with 04925777868cf18368330593eda4e18380b5351f, thanks a lot!

**Comment by aartaka** [comment]
Cool :)

**Pull request closed without merging**
