### PR TITLE
history: Extract buffer restoration out of `restore' to avoid side ef…

### PR DESCRIPTION
**Pull request by Ambrevar**
…fects and corruption.

`restore' should not have side effect.  Otherwise it may accidentally trigger
nested `restore' calls (via get-data) which may corrupt everything.  (Like
having 2 histories!)

The buffer restoration should thus be done outside of the context of data-path
restoration.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Shoud fix #1560 and #1550.

**Comment by jmercouris** [comment]
I'm running an older commit, and can't really test. I've also never had history problems. Perhaps it is something about my setup.

**Comment by Ambrevar** [comment]
It's a race condition, so it depend on how many buffers you restore and
how fast your hardware is.

Also the history-related issues usually arise when

```
(define-configuration browser
  ((session-restore-prompt :always-restore)))
```

Anyways, can you have a look at the code and test it on you machine, see
if it loads the history only once (look at the shell output) and if it
works probably on restart?

**Comment by jmercouris** [comment]
I will test on my machine. I guess the big difference here is that I have `:never-restore` in my config, which is probably why I am not having these errors. I'll test with no config then.

**Comment by jmercouris** [comment]
I'll also take a look at the code, of course.

**Comment by Ambrevar** [comment]
> I guess the big difference here is that I have `:never-restore` in my
> config, which is probably why I am not having these errors.

Totally, the issue at hand only arises when session restoration! :p

**Comment by jmercouris** [comment]
I've tried to force kill the program at critical moments to corrupt the history with a ton of buffers, still appears to work.

**Comment by Ambrevar** [comment]
Thanks!

**Pull request merged**
