### PR TITLE
Asd refactor2

### PR DESCRIPTION
**Pull request by Ambrevar**
Supersedes #1055.

I still need to test the CI (in particular the .deb build).

### CODE REVIEW

**Comment by Ambrevar** [comment]
OK, now the CI should pass!  I think this is ready to merge.

**Comment by Ambrevar** [comment]
@jmercouris Have you had time to have a look at this?

**Comment by jmercouris** [comment]
I have. I looked at it yesterday before we spoke, and we talked about it. I am ready for this change!

**Comment by jmercouris** [comment]
don't forget about the %variables to *variables*

**Comment by jmercouris** [comment]
After that, it is in my opinion, ready!

**Comment by Ambrevar** [comment]
Thanks!

Merged with 8e03f33708048d90c6610a5704e52a79b7fa4b28.

**Pull request closed without merging**
