### PR TITLE
Fix Shadow DOM performance issue and restore its support

### LINKED ISSUE #3295: `hint-mode` Shadow DOM elements support
As mentioned in https://github.com/atlas-engineer/nyxt/pull/3269#issuecomment-1862897209, `hint-mode`'s support for Shadow DOM may need to be re-designed from scratch.

Related to #3254. 

Performance benchmarks are needed as to ensure that the addition of this feature won't impact performance. E.g., mock an HTML document with thousands of links and return the time it takes for the renderer to draw the hints.

### PR DESCRIPTION
**Pull request by heiwiper**
# Description

The algorithm for the macro `rqsa` has been improved by using Tree Walker instead of Node Iterator and the matching elements are now sorted in depth first order. The sorting order was necessary to fix the performance issue, You can read more about the details of that issue in the references issues below.

The algorithm for the macro `rqs-nyxt-id` has been improved by directly retrieving Shadow root elements if the matching element cannot be found by executing `querySelect` function. Previously, we would walk through all elements to check whether each element is a Shadow root. Please note that we can't use this same method in the `rqsa` macro because the that macro might be executed on elements that do not yet have nyxt attributes assigned which isn't the case for `rqs-nyxt-id`.    

Fixes #3295

# Checklist:

- [X] Git branch state is mergable.
- [x] Changelog is up to date (via a separate commit).
- [ ] New dependencies are accounted for.
- [x] Documentation is up to date.
- [X] Compilation and tests (`(asdf:test-system :nyxt/<renderer>)`)
  - No new compilation warnings.
  - Tests are sufficient.

### CODE REVIEW

**Comment by jmercouris** [comment]
Thank you @heiwiper! I want you to know that this PR is not unnoticed!

**Comment by heiwiper** [comment]
Thanks for the followup! I totally understand, especially considering that the related issue is marked as low priority.

**Comment by heiwiper** [comment]
I have just added the changelog entry and rebased into master.

Thanks for taking the time to test these changes!

**Comment by aadcg** [comment]
Thanks again @heiwiper.

**Comment by heiwiper** [comment]
My pleasure!

Feel free to tag me in related issues.

**Pull request merged**
