### PR TITLE
configuration: Have define-configuration add just one handler per slot.

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Currently calling `define-configuration` multiple times over the same slot has no effect.
This patch ensures there is only one handler per slot.

# Discussion

- [ ] The `add-hook` of nhooks should probably do this handler replacement for us.
- [ ] Why are handler named uniquely?  Shouldn't they be named after the slot, actually? 

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

EDIT: Added more discussion.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@aartaka OK with you?

**Comment by aadcg** [comment]
> Why are handler named uniquely? Shouldn't they be named after the slot, actually?

I'd say they should indeed.

If there's a single handler per slot, how could the user change the value of a slot at runtime? 

I don't remember now, but don't we generate new object when using `define-configuration`?

**Comment by Ambrevar** [comment]
> I don't remember now, but don't we generate new objects when using `define-configuration`?

True in the `2-series` but no longer the case since our user-classes have hooks :)  See `user-classes.lisp`.

**Comment by aartaka** [comment]
No, I don't agree!

The change with `%slot-value%` opened for a new workflow: composing several handlers to change the value several times. I consider this a step towards a more intuitive model of configuration. If one puts several configuration forms for the same slot in their config -- they want all of those, together, modifying the value one by one!

**Comment by aartaka** [comment]
What about this?
``` lisp
(setf slot-foo (append 17 %slot-value%))
(setf slot-foo (append 18 %slot-value%))
```

This use-case is enabled by the current implementation, and I don't want to let it go!

**Comment by Ambrevar** [comment]
Oh right...

Then I suggest one change: to have one handler per slot and to name the handler after the slot: this way it makes hook introspection and editing much easier.

**Comment by aartaka** [comment]
"one handler per slot"?

**Review by aartaka — APPROVED** [review]

**Comment by Ambrevar** [comment]
You mean you agree with my last proposal, but not this pull request as it is, right?

**Comment by aartaka** [comment]
Yes, I don't agree with deleting the same slot handlers, but I agree with splitting slots into their own handlers!

So the course I'd be content with is removing the `:place` and `:value` from the generated handler and not deleting the handler with matching place.

**Comment by Ambrevar** [comment]
Superseded by #2480.

**Pull request closed without merging**
