### PR TITLE
Upstream class star

### PR DESCRIPTION
**Pull request by Ambrevar**
Following up to #1102, I've upstreamed most of the changes brought by our `class-star`.
In particular, upstream has adopted the `class*` nickname which means we can no longer use it.

This change set it meant to ease the transition before the library gets updated on Quicklisp.

1. When Quicklisp updates defclass-star, then we will be able to finalize the package nickname renaming by renaming all the 

```lisp
(hu.dwim.defclass-star:make-name-transformer name)
```

to
```lisp
(class*:make-name-transformer name)
```

2. One change is still pending upstream: https://github.com/hu-dwim/hu.dwim.defclass-star/pull/3.  If it gets accepted, then we can safely remove our  `class-star`.  If not, then we need to update `class-star` to apply this one change.

Please check if this works for you.

### CODE REVIEW

**Comment by aartaka** [comment]
Works for me!

**Comment by Ambrevar** [comment]
Great!
@jmercouris OK to merge?

**Comment by Ambrevar** [comment]
Thanks for testing Artyom!

**Comment by jmercouris** [comment]
OK to merge, I guess we'll make it less wordy when upstream is done.

**Pull request merged**
