### PR TITLE
Remove notification.lisp

### PR DESCRIPTION
**Pull request by jmercouris**
needs better design, for example, different notification programs may
have different command arguments, this does /not/ consider that.

this will also allow us to remove `notify-osd`.

### CODE REVIEW

**Comment by Ambrevar** [comment]
To fix the CI, I suggest you put `(echo-warning message)` in place of the remove `notify`.

**Comment by Ambrevar** [comment]
I'm OK with the removal, it can be restored later more properly.

I don't use notifications though, so I may be biased.
Thoughts anyone?
@aartaka?

**Comment by jmercouris** [comment]
We are only using them in a single place for now. When we restore them, we will restore them properly. We can add support for all kinds of notifications, page finished loading, download complete, etc.

**Comment by aartaka** [comment]
> I'm OK with the removal, it can be restored later more properly.
> 
> I don't use notifications though, so I may be biased.
> Thoughts anyone?
> @aartaka?

Not using notifications either ¯\\\_(ツ)_/¯

**Pull request merged**
