### PR TITLE
More obvious nicknames

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Add

- `time` for `local-time`
- `types` for `trivial-types`.

Use

- `flex` for `flexi-streams`.

# Discussion

Anything I may have missed?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [ ] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [x] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
I'm cautious about `types`, because it can clash with `nyxt/types` someday. 

But then, we import `nyxt/types` into `nyxt`, so it should be fine...

**Comment by Ambrevar** [comment]
> I'm cautious about `types`, because it can clash with `nyxt/types` someday.
> 
> But then, we import `nyxt/types` into `nyxt`, so it should be fine...

Indeed.  If there ever is an issue, we will change the nicknames then, it's a trivial change.

**Comment by Ambrevar** [comment]
Merged with 49ca9de17adb2db640a0ef3715a72db3692b3ade.

**Comment by aadcg** [comment]
@Ambrevar let us not forget to delete the remote branch :)

I've done it, thanks!

**Comment by aadcg** [comment]
Sorry for confusing you. I believe I haven't pruned deleted branch when fetching!

**Comment by Ambrevar** [comment]
Deleting branches on GitHub does not remove your local branches (even the "origin/*" ones).

**Pull request merged**
