### PR TITLE
Ci warnings

### PR DESCRIPTION
**Pull request by Ambrevar**
Note the elegance of the process: I'm not parsing some the output of some executable.  Instead, I'm leveraging ASDF directly in pure Common Lisp.  This is awesome!

### CODE REVIEW

**Comment by Ambrevar** [comment]
And this pull-request is meta-useful: It already highlights a problem with the double-definition of load-system!

What shall we do about it?  Rename one to `load-lisp-system`?  Which one?

**Comment by Ambrevar** [comment]
See the error on GitHub: "Some checks were not succesful".

**Comment by phoe** [comment]
Side note: you should write a separate article about it and publish it somewhere; possibly have it included on Planet Lisp as well.

**Comment by Ambrevar** [comment]
Will do!

**Comment by Ambrevar** [comment]
I suggest we replace the load-system helper with `load-after-system` as per #757.

**Comment by jmercouris** [comment]
Tested, works fine on my machine!

**Pull request merged**
