### PR TITLE
Add files as a nickname to the nfiles library.

### PR DESCRIPTION
**Pull request by aadcg**
In accordance to how the nhook library is used.

Closes issue #2241.

### CODE REVIEW

**Comment by aartaka** [comment]
Have you tried loading it? Seems like the nickname is not accessible in all of the packages `nfiles` is used in... You need to add `(use-nyxt-package-nicknames)` there then

**Comment by aadcg** [comment]
I did that, but I missed the tests folders!

Please check my latest 2 commit, especially b1371efb. Notice that I had to include the `in-package` declaration otherwise `use-nyxt-package-nicknames` wouldn't be defined. Does this make sense at all? Thanks.

**Comment by aadcg** [comment]
Looks good to me. Can I merge? @aartaka @Ambrevar

**Comment by aartaka** [comment]
Yes, looks just fine to me! Resolve the conflicts (I can do that if you don't feel like arguing with Git) and we can merge :)

**Comment by aadcg** [comment]
I didn't argue with Git much :p 

Should be ready to merge!

Recently I discovered `smerge-mode.el`, quite helpful!

**Pull request merged**
