### PR TITLE
buffer: Don't update the last-access when previewing buffers.

### LINKED ISSUE #1491: Do-what-I-mean follow-mode in switch-buffer
In commit b3dcf8400d92d1fe12eb91043981b52d5bc32201 @jmercouris changed the behaviour of `switch-buffer` to not move the last buffer to the top.

While this is convenient when follow-mode is on, it removes the ability to easily "alt-tab" between the last two buffers.

@jmercouris Can you remind me of the rationale behind not shuffling buffers?

### PR DESCRIPTION
**Pull request by Ambrevar**
Also add option to show current buffer last in switch-buffer.
This makes it easier to define a custom command to not show the current buffer last.

Fixes #1491.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@jmercouris About your rationale:

1. Is "fixed" by allowing the user to define a custom commands to choose whether the current buffer should be prompter or not.  I'm fine with swapping the defaults.
2. Is fixed by not updating `last-access` on preview.

**Comment by Ambrevar** [comment]
OK to merge?

**Comment by jmercouris** [comment]
99% of the way there :-). I don't like how "current-is-last" got changed :-O

It really makes me forget exactly what I was doing every time. I think the default should be nil.

**Comment by Ambrevar** [comment]
As I said, I don't mind setting the default to nil :)

**Pull request merged**
