### PR TITLE
renderer-gtk*.lisp: re-enable native renderer download

### PR DESCRIPTION
**Pull request by jmercouris**
It seems to be enough to just re-enable it in the context menu. Then it bypasses the download manager and allows the engine to handle it.

That said, perhaps I should write a interface so that you can at least monitor a download initiated in this manner, or perhaps specify a download path... here is the reference: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitDownload.html

### CODE REVIEW

**Comment by Ambrevar** [comment]
Indeed, we need to capture the download progress.  It's not hard, just a few more bindings.

That said, supporting cookies in our download manager might be even easier to do, and it will be more useful in the future!
(Dexador accepts a cookie argument.)

**Comment by jmercouris** [comment]
I see as adding cookie support to dexador not mutually exclusive :-)

**Comment by jmercouris** [comment]
I will investigate both!

**Comment by Ambrevar** [comment]
Why did you close this?

Also I see it's merged, I would have like to review and test this.
Any reason you merged it so soon?

I don't understand the new feature: now we have both a CL download manager _and_ downloads via right-click?  The right click download, if I'm not mistaken, won't download to the directory configured by the user, nor will it report any progress (which is very confusing).  Am I missing something?

**Comment by jmercouris** [comment]
I made a new branch where I've created download displays, will add a new pull request soon!

**Comment by jmercouris** [comment]
More details following soon :-)

**Comment by jmercouris** [comment]
To clarify, this branch was only about enabling the context menu

**Comment by Ambrevar** [comment]
Ah OK, thanks!

**Pull request closed without merging**
