### PR TITLE
bookmarklets: Move all to nyxt/web-mode package.

### PR DESCRIPTION
**Pull request by Ambrevar**
Indeed, they manipulate the content of the buffer, they should not be global
commands.

Bonus: Move bookmarklets-related commands from data-storage (why were they
there?) to bookmarklets.lisp.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Addresses #1406.

**Comment by jmercouris** [comment]
I can accept this change EXCEPT for moving the functions out of data storage. I don't see why they would belong to web-mode, they have use in a broader context.

**Comment by jmercouris** [comment]
Additionally the `define-bookmarklet-command` macro should belong to the Nyxt package.

**Comment by Ambrevar** [comment]
> Additionally the `define-bookmarklet-command` macro should belong to the Nyxt package.

Good catch!

**Comment by Ambrevar** [comment]
> I can accept this change EXCEPT for moving the functions out of data storage. I don't see why they would belong to web-mode, they have use in a broader context.

No strong opinion on where they belong.  Here was my thinking process:

- They don't belong to data-storage :p  Maybe configuration.lisp?
- They are not exported, so it does not really matter where they are.
- They are only used in bookmarklets so far.  We can always move them to
  a more general location when we get a need for them.
  Since they are unexported, we are free to move them around as we wish.

Thoughts?

**Comment by jmercouris** [comment]
OK, `configuration.lisp` is fine.

**Comment by Ambrevar** [comment]
Just force-pushed, what do you think?

**Comment by jmercouris** [comment]
Thank you!

**Pull request merged**
