### PR TITLE
Refer to "guix shell" rather than "guix environment"

### PR DESCRIPTION
**Pull request by khinsen**
Guix is transitioning away from "guix environment" to the new
"guix shell" command.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks a lot!
Looks good to me, but there would be a few more ajustment to take over in the README, in `nyxt-guix.el` and in the CI scripts.

@aartaka Does this look good to you?  Any particular opinion on `guix shell`?

**Comment by aartaka** [comment]
> Thanks a lot! Looks good to me, but there would be a few more ajustment to take over in the README, in `nyxt-guix.el` and in the CI scripts.

We should also rename `build-scripts/nyxt.scm` to `build-scripts/guix.scm`, as this name is automatically discovered by `guix shell` and `guix environment -l guix.scm` becomes simply `guix shell` while in `build-scripts`.

> @aartaka Does this look good to you? Any particular opinion on `guix shell`?

It's short, it has a more intuitive default behavior, it does smart file discovery -- I like it :D

**Comment by khinsen** [comment]
Renaming `nyxt.scm` doesn't look very useful to me, as there aren't many useful things to run with `build-scripts` as the current directory. But it wouldn't do any harm either.

**Comment by Ambrevar** [comment]
I've tested this and there seems to be a bug in `guix shell`.
See

```sh
guix shell --pure -D -f /home/ambrevar/projects/nyxt/build-scripts/nyxt.scm glib lisp-repl-core-dumper -- lisp-repl-core-dumper --help
Usage: lisp-repl-core-dumper [OPTIONS] LISP [START-FLAGS]
...
```

Now if I remove `glib` from the command:

```lisp
guix shell --pure -D -f /home/ambrevar/projects/nyxt/build-scripts/nyxt.scm  lisp-repl-core-dumper -- lisp-repl-core-dumper --help
guix shell: error: lisp-repl-core-dumper: command not found
```

So it seems that `-D` applies both on `nyxt.scm` and on `lisp-repl-core-dumper` in the second case (or `glib` in the first case).

Am I mistaken or is it a `guix shell` bug?

**Comment by khinsen** [comment]
Yes, this looks like a bug. If you run
```sh
guix shell --pure -D -f /home/ambrevar/projects/nyxt/build-scripts/nyxt.scm  lisp-repl-core-dumper
```
to get an interactive shell, and then look at `$GUIX_ENVIRONMENT/manifest`, you see as the first two entries the two inputs of `lisp-repl-core-dumper`, but `lisp-repl-core-dumper` is not part of the manifest.

**Comment by khinsen** [comment]
I have submitted a bug report to Guix: https://issues.guix.gnu.org/52093

**Comment by Ambrevar** [comment]
@khinsen Would you have time to report this to the Guix team?
Let me know if you don't, then I'll do it later.

**Comment by Ambrevar** [comment]
Thanks a lot!

**Comment by khinsen** [comment]
The bug in `guix shell` has been fixed.

**Comment by aartaka** [comment]
Indeed, seems to work just fine!

**Comment by aartaka** [comment]
@Ambrevar, I can take README, CI, and nyxt-guix fixes on me, that sounds fun :)

**Comment by Ambrevar** [comment]
Alrighty, thank you!
nyxt-guix might be a bit tricky, beware ;)

**Comment by Ambrevar** [comment]
Thanks for your help, @khinsen!

**Comment by Ambrevar** [comment]
Maybe we wait a week or so before merging this to give some time to Guix
users and not force them to immediately `guix pull`.

**Comment by aartaka** [comment]
OK, both `build-script/nyxt-guix.el` and `documents/README.org` refer to the `guix shell` now. @Ambrevar, can you connect to the nyxt environment and see whether it works? I'm unable to check it myself due to weird segfaults that started around a month ago. Nyxt dependencies seem to load just fine, though.

**Comment by aartaka** [comment]
OK, I'm pretty sure it should work just fine. Two weeks have passed too. Merging it.

**Comment by aartaka** [comment]
@khinsen, thanks for enlightening us about `guix shell`!

**Comment by Ambrevar** [comment]
Thanks for finishing up the work, Artyom!

**Pull request merged**
