### PR TITLE
Recover from broken init

### PR DESCRIPTION
**Pull request by Ambrevar**
This is where functional style and user classes really pay off!

Previously, if an init file was syntactically correct but would break Nyxt otherwise, the browser would fail to start in the weidest ways (e.g. blank window).

Now startup errors are caught and the state is almost completely reinitialized, then the error is displayed as usual using the reported.

Notes:
- The user classes implementation is completely upside down, but I don't think we can easily overhaul this without breaking backward compatibility.  We can do this for 3.0.  See https://github.com/atlas-engineer/nyxt/issues/1431.

- If you want to test, in particular compare the behaviour with master, try adding this to your init file:

```lisp
(define-configuration window
  ((status-formatter 17)))
```

From KABOOM! to swooosh! :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
OK to merge? @jmercouris @aartaka

**Comment by jmercouris** [comment]
I don't know how I feel about a 'reset' function rather than a functional start. Hence why I haven't commented yet! Could you please walk me through some of your decision making?

**Comment by Ambrevar** [comment]
A functional (re)start would be great, but... Can we?

GTK is heavily non-functional.  Maybe we can join the GTK thread, thus
stopping it, then completely start over passing `:no-init t` to `start`.
Seems more elegant indeed.
I'll give it a try.

Note that we have to "reset" the user classes anyways.  Does that make sense?

**Comment by jmercouris** [comment]
Yes, that makes sense :-)

**Comment by Ambrevar** [comment]
Done, we are now restarting the Nyxt _executable_ on error.  Only once, to avoid looping forever.  This should be much more bullet proof.

OK to merge now?

**Comment by jmercouris** [comment]
Ok!

**Comment by jmercouris** [comment]
Works well! Thank you!

**Comment by Ambrevar** [comment]
Note for future reference: 

> Note that we have to "reset" the user classes anyways.  Does that make sense?

This is only true when run from the REPL.

Thank you John for testing and suggesting to restart the browser, it's much better now!

**Pull request merged**
