### PR TITLE
Combine-append buffer default-modes.

### PR DESCRIPTION
**Pull request by Ambrevar**
This is an alternative to #1411.

It uses an `append` method combination.
Unlike what I commented in #1411, this does not allow for using `define-configuration` either.  But still, it's cleaner and less intrusive than #1411 I believe, so I'm in favour of this one.

As per `define-configuration` support, we could expand the macro to add support for generic functions.

For instance,

```lisp
(define-configuration buffer
  ((default-modes '(foo)))
```

would automatically detact that default-modes is a defgeneric with a non-standard method combination and thus expand to

```lisp
(defmethod default-modes append ((buffer buffer)
  '(foo)))
```

Thoughts?

### CODE REVIEW

**Comment by Ambrevar** [comment]
Great news, I've just implemented support for `define-configuration`.

What's really cool about it is that it should be syntactically backward compatible, meaning that the user config should now behave as expected, without change!

**Comment by Ambrevar** [comment]
Element-hint is now also working properly.

This does it I believe :)
Please confirm that it works with your configuration (hopefully without change), and this should be ready to merge.

**Comment by Ambrevar** [comment]
As with #1411, this fixes #1383 and #1355.

**Comment by jmercouris** [comment]
Let me give this  a try. It is a most interesting proposal!

**Comment by jmercouris** [comment]
Well, it does work with my configuration! That is good news. This is very very clever, and that concerns me a little bit. I must agree with you though, this is a better solution that #1411.

I would like to talk about something you hinted at though: the problem of potentially having a `user-modes` slot. You talked about this being overridden in the hierarchy of inheritance. However, if we do not ever set this slot, and confirm that it is for user use only, would that not be OK?

**Pull request merged**
