### PR TITLE
FreeBSD related changes

### PR DESCRIPTION
**Pull request by nayuki-d**
#1111

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks, very useful!

Don't you also need gsettings-desktop-schemas?

**Comment by nayuki-d** [comment]
gsettings-desktop-schemas is a build and runtime dependency of net/glib-networking. Both pkg(8) and ports installation will install it automatically.

**Comment by Ambrevar** [comment]
Thanks a lot!

**Comment by jmercouris** [comment]
+1 thank you!

**Pull request merged**
