### PR TITLE
Actions fix

### PR DESCRIPTION
**Pull request by jmercouris**
What do you think?

### CODE REVIEW

**Comment by aartaka** [comment]
That seems like an absolute overkill. What stops us from extracting `open-file*` to a top-level function instead?

**Comment by Ambrevar** [comment]
Is something broken?
@jmercouris I don't understand the intention.

**Comment by Ambrevar** [comment]
@aartaka We could extract `open-file*`, but not that actions don't take a source as argument, so you'd still need the initialize-instance method and to curry the source into the extracted function.

**Comment by jmercouris** [comment]
@Ambrevar that's exactly the problem I identified as well, hence my proposed solution. I just force pushed, please take a look.

**Comment by jmercouris** [comment]
@Ambrevar Yes, something was broken. Editor open file would constantly open up libre office instead of actually opening the built-in editor. It turns out that the `initialize-instance :after` of the `file-source` was changing the `actions`.

**Comment by aartaka** [comment]
Looks alright. Maybe call it `openable-file-source` or `open-file-source`? Also, it should be used in `download-open-file`.

**Comment by aartaka** [comment]
@Ambrevar, maybe we should add a `(setf actions)` method to mirror `actions`?

**Comment by aartaka** [comment]
Thanks John! That was quick! :)

**Comment by jmercouris** [comment]
No problem!

**Comment by aartaka** [comment]
> @aartaka You mean a setf-method?

Exactly.

**Pull request merged**
