### PR TITLE
Fix "can't open-code test" SBCL warnings

### PR DESCRIPTION
**Pull request by Ambrevar**
This should finally rid us of the warnings in the line of

```log
source/buffer.lisp:856:1:
  note:
    can't open-code test of unknown type BROWSER
```

that started occurring with SBCL 2.1.9 at least.
You can trigger these warnings by force-compiling Nyxt or simply by changing branch (between `master` and `2-series` for instance).

I like the new `:module` in the .asd: it structures the list and make us less prone to break the load order by introducing new files and re-ordering files.

The only "fix" that I'm a bit skeptical about is the class forward declaration in f97d8fc612f059295b87de2106a47088bb6edb22.  What do you think?

### CODE REVIEW

**Comment by Ambrevar** [comment]
Actually the forward-declaration of class triggers a warning on CCL, so that's not the proper fix.  Any better idea?

**Comment by aartaka** [comment]
Hmmmm, what about exporting a symbol in advance, so that it exists and has a type declared for it?

**Comment by Ambrevar** [comment]
Doesn't work because the type is still unknown.

With no better idea, I suggest to merge this without the last commit.

**Comment by aartaka** [comment]
> Doesn't work because the type is still unknown.

Oh, okay :)

> With no better idea, I suggest to merge this without the last commit.

Yes, sounds sane.

**Comment by aartaka** [comment]
Thanks, Pierre, these were annoying :)

**Comment by Ambrevar** [comment]
2 of them remain because we need to either forward declare the browser,
or untangle our window / buffer / browser definitions.

**Pull request merged**
