### PR TITLE
Alternative style for <pre> code listings.

### PR DESCRIPTION
**Pull request by aartaka**
# Description

@jmercouris expressed the worry that code listings on Nyxt pages are not intelligible enough. This PR tries to address this problem by turning all code blocks in Nyxt into bordered boxes with regular background and text colors. It's clear, it's contrasting, it's simple. See the attached screenshot for how it looks now:

pre-restyle

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [X] I've added the new dependencies as:
  - [X] ASDF dependencies,
  - [X] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [X] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - [X] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [X] I have updated the existing documentation to match my changes.
  - [X] I have commented my code in hard-to-understand areas.
  - [X] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [X] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [X] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [X] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [X] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
I like the Genera vibes new style emits :D

**Comment by aartaka** [comment]
And no need for tertiary color!

**Comment by aadcg** [comment]
I believe that the specification that @lansingthomas has in mind is different: instead of boxing, apply a nuanced background.

That could be achieved in a similar way as it was done in a911f29c0.

**Comment by aartaka** [comment]
> I believe that the specification that @lansingthomas has in mind is different: instead of boxing, apply a nuanced background.
> 
> That could be achieved in a similar way as it was done in [a911f29](https://github.com/atlas-engineer/nyxt/commit/a911f29c008dee02e79d7f217a4b4795ab0377ba).

Yes, but a911f29c008dee02e79d7f217a4b4795ab0377ba I try to avoid, because it's essentially trying to introduce a new color without introducing one, and makes elements mutually dependent in their styling.

**Comment by aadcg** [comment]
I agree that it's a subpar solution too, and a nuanced background would be a better solution. 

Anyway, no strong opinion from my side, so I'm stepping out of this exchange of ideas.

**Comment by jmercouris** [comment]
Hello Artyom,

a great idea you have here. In fact this is one of the first things that Thomas and I tried to do. It is a good solution, but an incomplete solution. Thomas had some ideas for some other places we could use a lighter color as well.

For example, as we discussed above, the message buffer is a hack, and should not be set at 90% opacity to achieve the result. For now this is good, but I do not believe this negates the need for a third color!

**Pull request merged**
