### PR TITLE
Serialize quri:uri as string in session.

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by aartaka** [comment]
There's a `#'str:emptyp` remaining in the `previous-history-urls-suggestion-filter` (certificate-whitelist-mode.lisp) that won't work for `quri:uri`. Please, replace it with `#'url-empty-p`, while you're at it.

**Comment by Ambrevar** [comment]
Good catch!

Fixed in 780837c28815b364fe413e2aa7171a6d59b186d4.

**Comment by Ambrevar** [comment]
@jmercouris OK to merge?

Note: last commit is missing from this pull request.

**Comment by jmercouris** [comment]
Oui, merci beaucoup!

**Pull request merged**
