### PR TITLE
libraries/user-interface: fix `eval' with runtime solution

### PR DESCRIPTION
**Pull request by createyourpersonalaccount**
As recommended by the README of spinneret:
<https://github.com/ruricolist/spinneret#interpreting-trees>

# Description

Removed `TODO` in code that asked to remove `eval`.

# Discussion

The spinneret project claims that the function `interpret-html-tree` does not support the full range of features. It should be fine for the marshalled expressions. It could be tested with a unit test.

Feel free to comment on this commit and offer tips, it's my first in the project.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [X] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
> I foresee one problem though: I'm not sure how much control we have over the content of `object-expression`, and thus `interpret-html-tree` could potentially hit an unsupported expression.

And it eventually will :(

> @aartaka Thoughts on this?

I mean, `interpret-html-tree` is nice, but maybe we're trying to solve the wrong problem here? How about this: maybe we should define a method on interface elements that would return the exact HTML for those, no matter which way it's produced? So, instead of 
``` lisp
(defmethod object-expression ((button button))
  `(:button :id ,(id button)
            :class "button"
            :title ,(alt-text button)
            :onclick ,(action button)
            ,(text button)))
```
have
``` lisp
(defmethod object-string ((button button))
  (spinneret:with-html-string
   (:button :id (id button)
            :class "button"
            :title (alt-text button)
            :onclick (action button)
            (text button))))
```

I can vaguely recall that this `object-expression`/`object-string` dichotomy was due to `cl-markup` (our previous HTML-generation library) being extremely inflexible. And `user-interface` library wasn't updated for a loooooong time, maybe even sinse `cl-markup` times...

Or, even more radical: maybe we don't actually need `user-interface`? We have `spinneret-tags.lisp` now, and it is already full of useful widgets that are as easy to embed as writing any other HTML via Spinneret. Do we actually need to move further than that for UI?

**Comment by Ambrevar** [comment]
No strong opinion, but if there is resistance for the second suggestion, then we can at least implement Artyom's first suggestion as a simple step to remove the `eval`.

**Comment by createyourpersonalaccount** [comment]
I am returning the exact HTML now. I didn't know what is meant by the more radical suggestion, but I'll keep it in mind for later.

**Comment by aartaka** [comment]
Thanks, @createyourpersonalaccount :)

**Pull request merged**
