### PR TITLE
Fix url setting

### LINKED ISSUE #1412: Nyxt is not loading a local valid HTML file
**Describe the bug**

Expected: Nyxt would execute/interpret a local valid HTML file.

Returned: "page could not be loaded"

Control group: the same file under the same conditions is successfully loaded using Firefox

**Precise recipe to reproduce the issue**

After running on the shell:
`nyxt index.html`

Nyxt returns:
<INFO> [16:16:19] Nyxt already started, requesting to open URL(s): index.html

However, it fails to load the **local** file, and the browser's GUI shows:

> Page could not be loaded.
> 
> URL: index.html
> 
> Please check:
> 
> Your Internet connection.
> That the URL is valid.
> That the resource at the URL is reachable.
> 

To reproduce you need to use a valid HTML file and run `nyxt example.html` on your shell.

**Information**

- OS name+version: 
       Ubuntu 20.04.2 LTS
       
- Graphics card and driver: 
       product: Iris Plus Graphics 640
       configuration: driver=i915 latency=0

- Desktop environment / Window manager name+version:
       Name: GNOME Shell 3.36.7
       Window manager's "showing the desktop" mode: OFF

- How you installed Nyxt (Guix pack, package manager, build from source): 
       package manager

- Information from command copy-system-information: 
     Nyxt version: 2-pre-release-7
     Renderer: GI-GTK
     Operating system kernel: Linux 5.8.0-53-generic
     Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
     Features: (WEBKIT2 WEBKIT2-2.30 WEBKIT2-TRACKING WEBKIT2-MUTE WEBKIT2-EMOJI
           WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18 GTK-3-16
           GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
           GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8
           GDK-3-6 GDK-3-4 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32
           GLIB-2-34 GLIB-2-36 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44
           GLIB-2-46 GLIB-2-48 GLIB-2-50 GLIB-2-52 GLIB-2-54 GLIB-2-56
           GLIB-2-58 GLIB FSET-EXT-STRINGS CUSTOM-HASH-TABLE-NATIVE SWANK
           PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES PARENSCRIPT NAMED-READTABLES
           21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP CL-PPCRE-UNICODE
           CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS FAST-IO-SV
           FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
           CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64
           UNIX CFFI FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2
           ASDF3.1 ASDF3 ASDF2 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE
           X86-64 GENCGC 64-BIT ANSI-CL COMMON-LISP ELF IEEE-FLOATING-POINT
           LINUX LITTLE-ENDIAN PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION
           SB-LDB SB-PACKAGE-LOCKS SB-THREAD SB-UNICODE SBCL UNIX)

**Output when started from a shell**
     $ nyxt
     <INFO> [16:31:30] Listening to socket "/home/pedro/.local/share/nyxt/nyxt.socket".
     Nyxt version 2-pre-release-7
     <INFO> [16:31:31] Loading Lisp file "/home/pedro/.config/nyxt/auto-config.lisp".
     WARNING: Key was bound to LOAD-FILE
     WARNING: Key was bound to SET-URL-NEW-NOSAVE-BUFFER

**Speculation**

     I am still a noob around Nyxt but maybe this problem is connected to this [issue](https://github.com/atlas-engineer/nyxt/issues/1258)

### PR DESCRIPTION
**Pull request by Ambrevar**
Fixes #1412.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@pdelfino Wanna test this?

**Comment by pdelfino** [comment]
> @pdelfino Wanna test this?

Hi, I tested and it works!

I should just mention that the test conditions on my side are different now to when I found the bug.
Now, I am running Nyxt from source, version 2.0.0-20, after loading it in Emacs/Slime and I did `M-x`+`open-file`+selected the path+ `enter`. All this **inside** Nyxt.

When I found the bug I was using the ubuntu's command line and simply did `nyxt index.html`. This commands automatically opens Nyxt's version-2-pre-release-7.

I **do not know** how to use the ubuntu command line to open a file with nyxt most advanced version. Just methaporically, something like `$nyxt-master index.html`.

**Comment by Ambrevar** [comment]
1. Remove Nyxt 2-pre-release-7.
2. Add `/path/to/your/nyxt/checkout` to your PATH environment variable.  For instance


```sh
export PATH="/path/to/nyxt/dir/:$PATH"
```

Store the above line in your `~/.profile` or similar.

**Comment by pdelfino** [comment]
Hi Pierre,

> Remove Nyxt 2-pre-release-7.

Checked!

> Add /path/to/your/nyxt/checkout to your PATH environment variable. For instance

Well, I did this:
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi


# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    export PATH="$HOME/pedro/common-lisp/nyxt/:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    export PATH="$HOME/pedro/common-lisp/nyxt/:$PATH"
fi

```

Unfortunately, when I run:
```
~$ nyxt
Command 'nyxt' not found, did you mean:
```
It does not work. Did I do something wrong? Is the Nyxt checkout another thing?

**Comment by Ambrevar** [comment]
There are multiple mistakes in your ~/.profile:

- `$HOME` probably expands to `/home/pedro` (you can test this with `echo $HOME` in a shell), so the following `pedro` is redundant.
- The surrounding conditional points to the wrong folder.  It's testing if the folder exists, so if should be `-d "$HOME/common-lisp/nyxt"`.
- No need to do the whole thing twice.

**Pull request merged**
