### PR TITLE
Add extensions-path.

### LINKED ISSUE #1367: Nyxt extension storage location
Something that completely slipped my mind: we need to decide where extensions ought to be loaded from by default.  `~/common-lisp` is no good since it's not Nyxt-specific and could conflict with CL devs local libraries.

`~/.local/share/nyxt/extensions/`?

Any better suggestion?

### PR DESCRIPTION
**Pull request by Ambrevar**
Fixes #1367.

### CODE REVIEW

**Comment by jmercouris** [comment]
I can confirm that this works on NixOS. I can test on Ubuntu, let me just trigger a build!

**Comment by Ambrevar** [comment]
Thanks!

**Comment by jmercouris** [comment]
Hm:

Screenshot_20210506_123057

**Comment by jmercouris** [comment]
Aha!

Screenshot_20210506_123242

**Comment by Ambrevar** [comment]
Good catch, I'll fix it just now.

**Comment by Ambrevar** [comment]
(pfeww, that was worth testing!)

**Comment by Ambrevar** [comment]
Done: f7ff0b4417ab7ee3fddca14d167fc61bbd89a901.
Mind re-testing?

**Comment by jmercouris** [comment]
OK, will do!

**Comment by jmercouris** [comment]
I really have to say, the built-in REPL has been invaluable!

**Comment by jmercouris** [comment]
That fixes it! thank you!

**Comment by Ambrevar** [comment]
Fantastic!
OK, will merge!

**Comment by jmercouris** [comment]
I will delete the commit and merge.

**Comment by jmercouris** [comment]
OK NVM, you can merge :-D

**Comment by Ambrevar** [comment]
Merged with 739bee73e17751af5b3e18c163cf6a7e762bfc0f.

**Comment by jmercouris** [comment]
Thank you!

**Pull request closed without merging**
