### PR TITLE
Demote some core modes as non-core modes

### PR DESCRIPTION
**Pull request by Ambrevar**
Still trying to make the Nyxt core as micro as possible... :)

### CODE REVIEW

**Comment by aartaka** [comment]
Maybe we should even move some modes to extensions?

**Comment by aadcg** [comment]
> Maybe we should even move some modes to extensions?

I second that. Especially:

- `no-procrastinate`, that extends `blocker-mode`;
- `tts`;

Notice that marking something as an extension doesn't mean that we must take it outside of our repository. There could be extensions that we ship together with nyxt.

**Comment by aadcg** [comment]
I'm ok with this change, philosophically @Ambrevar.

Let me see test it to see if it breaks something terribly obvious.

**Comment by aadcg** [comment]
Seems to ok @Ambrevar.

**Pull request merged**
