### PR TITLE
GitHub release

### PR DESCRIPTION
**Pull request by Ambrevar**
This enables the following:

- Test the Guix package.
- Release the .deb file automatically.
- Build the "Guix pack" for us and release it.

How does it look to you?
Don't merge yet, I need to test the release CI.

### CODE REVIEW

**Comment by jmercouris** [comment]
I'm just joking of course :-D

**Comment by jmercouris** [comment]
Looks OK to me, are the tests of comparable performance on Guix? I would imagine they are more reliable than tests run on Ubuntu :-).

**Comment by Ambrevar** [comment]
Indeed, we could have the tests just run on Guix since it duplicates the workload for the CI.  That said I've seen tests that failed but the Guix package creation still passed, I'm not completely sure why.  My guess is that it's a bug in the Guix' `asdf-build-system`.

To keep in mind for later.

**Comment by Ambrevar** [comment]
I've tested the release: The Guix pack is properly generated, but the deb is not: https://github.com/atlas-engineer/nyxt/runs/3729647456?check_suite_focus=true

I'll investigate.

**Comment by Ambrevar** [comment]
Got it!

OK to merge then?

**Comment by jmercouris** [comment]
Ok!

**Comment by jmercouris** [comment]
I assume you want to apply this same patch forward to master as well?

**Comment by Ambrevar** [comment]
Yes, will do, but first I want to merge the Git Submodule patch.

**Pull request merged**
