### PR TITLE
XMPP support

### PR DESCRIPTION
**Pull request by aartaka**
This is a terribly rough prototype for XMPP support.

# Things There
- Dependency on old `cl-xmpp` that seems to cover everything we want -- just takes some learning and getting used to.
- `xmpp-mode` -- yet another scheme-tied mode.
- More interface idioms -- this time it's a chat window resembling our current REPL :D 

# Things To Do
- Allow several chat buffers with several accounts? At least several chat buffers with all the messages properly distributed between them (right now it's basically putting every message into the current `xmpp-mode` irregradless of who the message comes from)

# Things To Discuss
- How does one test XMPP without chatting? Anyone knows some Jabber bots to chat with? Anyone ready to chat with me for me to test this obviously incomplete prototype?
- We have `small-web-mode`, `activitypub-mode` from #2238, `xmpp-mode` as the modes that match a certain scheme. Feels like #1790 and #2004 are a necessity now (: 

Again, anyone wants to chat?

### CODE REVIEW

**Comment by aadcg** [comment]
This seems very interesting! I don't know much about XMPP but I'd like to chat :)

**Comment by aartaka** [comment]
Update: It's more or less working now, I can have reasonably long conversations with myself, but
- [ ] There are still SSL, XML, and XMPP errors happening around and eventually killing the connection.
- [ ] The chat rendering gets broken if the chat is longer than one screen.

**Comment by hendursaga** [comment]
I remember there was this one echo bot... but I can't remember the address anymore! :(

**Comment by aartaka** [comment]
> I remember there was this one echo bot... but I can't remember the address anymore! :(

No worries, I've just set up a bunch of accounts on different servers with their own special XMPP formats, so I'm having lots of fun time :)

**Comment by hendursaga** [comment]
I managed to find one working echo bot address: [echo@jabber.fu-berlin.de](xmpp:echo@jabber.fu-berlin.de)

**Comment by aartaka** [comment]
Closing this because of `cl-xmpp` maintenence burden becoming unmanageable `t(-_-t)`

**Comment by Ambrevar** [comment]
Care to move it to an extension repository?

**Comment by aartaka** [comment]
> Care to move it to an extension repository?

No, `cl-xmpp` is too broken for a working extension :P

**Comment by Ambrevar** [comment]
I mean as a place where to keep your work, we can mark it as "non working".

**Comment by aartaka** [comment]
Well, it's still a branch in Nyxt, preserved on GitHub servers...

**Comment by Ambrevar** [comment]
Branches are harder to find (by the general public, also it by GitHub search bar), please more easily accidentally pruned ;)

**Comment by Ambrevar** [comment]
Excellent, thank you!

**Comment by Ambrevar** [comment]
@aartaka Can this branch be removed?

**Comment by aartaka** [comment]
Yes, I removed it!

**Comment by Ambrevar** [comment]
Thanks!

**Pull request closed without merging**
