### PR TITLE
Replace classes using replace-class macro and fix CCL support.

### PR DESCRIPTION
**Pull request by Ambrevar**
Should be good for merging.
@jmercouris Can you test on macOS to make sure I didn't break anything?

### CODE REVIEW

**Comment by jmercouris** [comment]
#I will test when I can, don't have easy computer access at the current moment. I put it on my calendar for Monday, but will try to get to it sooner

**Comment by Ambrevar** [comment]
On second though it should not break anything, the macro should expand
to the same code than that on master, so this should be rather safe to merge.

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
Merged with 4a2ddfc48255da2c7019c716bf237cf126ec7461.

**Pull request closed without merging**
