### PR TITLE
mode/history: Visit page in corresponding buffer when clicking on his…

### PR DESCRIPTION
**Pull request by Ambrevar**
…tory tree link.

Open the `history-tree` (or `buffer-history-tree`).  Now if you click on the link, it will switch to the corresponding buffer and navigate back or forward to the corresponding history location, without corrupting the flow of the history.

Try it, it's awesome!

@aartaka Initially the history tree visualization showed links, which could be seen as more appropriate.
But maybe they are not, since we are not loading anything?
Either way, the style looks really bad.  Can we somehow make it look more like links and less like buttons?

### CODE REVIEW

**Comment by aartaka** [comment]
> …tory tree link.
> 
> Open the `history-tree` (or `buffer-history-tree`). Now if you click on the link, it will switch to the corresponding buffer and navigate back or forward to the corresponding history location, without corrupting the flow of the history.
>
> Try it, it's awesome!

Whoa, I've been thinking about doing it for a long time! And now you beat me to it, Pierre :D Thanks for taking the time!

> @aartaka Initially the history tree visualization showed links, which could be seen as more appropriate. But maybe they are not, since we are not loading anything? Either way, the style looks really bad. Can we somehow make it look more like links and less like buttons?

One word: CSS! You can use [`all` property](https://developer.mozilla.org/en-US/docs/Web/CSS/all#formal_definition) to reset all the styling, or you can use a mixture of `:border`, `:display`, and `:text-decoration` to remove things one by one. It's all configurable there :)

**Comment by Ambrevar** [comment]
What I'd like to do (and we probably need this elsewhere) is to "import" the style of `a` elements.  Is there a way to do this?

**Comment by aartaka** [comment]
> Question: why do we have two `style` lines in `history-tree`?
> 
> ```lisp
>              (:style (style output-buffer))
>              (:style (:raw (style mode)))
> ```

This is to use styles of both the buffer and the mode. Is somthing wrong with this?

**Comment by aartaka** [comment]
> What I'd like to do (and we probably need this elsewhere) is to "import" the style of `a` elements. Is there a way to do this?

Nope, you can only reproduce it :)

**Comment by Ambrevar** [comment]
Mind doing it?  (Feeling lazy to play with CSS... :p)

**Comment by aartaka** [comment]
Done with 8b00d3b227de1e5b8803afb4b39de7004e38fc49.

**Comment by Ambrevar** [comment]
Thanks a lot!

**Pull request merged**
