### PR TITLE
Empty asdf registries

### LINKED ISSUE #1306: Remove default ASDF registries when using Makefile
Presently running `make all` may load system-installed Common Lisp packages, which has broken the build for quite a few users in the past.

Instead, we should add an option to nullify the default ASDF registries (enable this option by default), and only add the submodules and internal Quicklisp.

### PR DESCRIPTION
**Pull request by Ambrevar**
Fixes #1306.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Works on Ubuntu, I guess this is good to merge.

Can anyone spot a catch?

**Comment by jeffbowman** [comment]
Pulled the asdf-empty-registries branch, it does not build on Arch Linux:

make all
sbcl --no-userinit --non-interactive --eval '(require "asdf")' --eval '(when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-system :nyxt/quicklisp))' --eval '(asdf:load-asd "/home/jeffbowman/Projects/CommonLisp/nyxt//nyxt.asd")' --eval '(ql:quickload :nyxt/gtk-application)' \
	--eval '(asdf:make :nyxt/gtk-application)' \
	--eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Unhandled ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                             {1001878103}>:
  Component :NYXT/QUICKLISP not found

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001878103}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component :NYXT/QUICKLISP not found #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component :NYXT/QUICKLISP not found)
2: (INVOKE-DEBUGGER Component :NYXT/QUICKLISP not found)
3: (ERROR ASDF/FIND-COMPONENT:MISSING-COMPONENT :REQUIRES :NYXT/QUICKLISP)
4: ((:METHOD ASDF/OPERATE:OPERATE (SYMBOL T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP) [fast-method]
5: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP)
6: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
7: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP) [fast-method]
8: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1004A3913B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
9: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
10: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {10032D8AAB}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
11: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP) [fast-method]
12: (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)
13: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP) #<NULL-LEXENV>)
14: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)) #<NULL-LEXENV>)
15: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WHEN (STRING= "true" "true") (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)) #<NULL-LEXENV>)
16: (EVAL (WHEN (STRING= "true" "true") (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)))
17: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . "(when (string= \"true\" \"true\") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-system :nyxt/quicklisp))") (:EVAL . "(asdf:load-asd \"/home/jeffbowman/Projects/CommonLisp/nyxt//nyxt.asd\")") (:EVAL . "(ql:quickload :nyxt/gtk-application)") (:EVAL . "(asdf:make :nyxt/gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
18: (SB-IMPL::TOPLEVEL-INIT)
19: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
20: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
21: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting

Compilation failed, see the above stacktrace.

make: *** [Makefile:42: nyxt] Error 1

**Comment by Ambrevar** [comment]
Thanks for reporting.

So it turns out that Ubuntu on the CI was not leveraging the .asd to get Quicklisp.  I need to fix this, then fix the issue that @jeffbowman reported.

**Comment by Ambrevar** [comment]
@jeffbowman Could you try again?

**Comment by jeffbowman** [comment]
pulled changes from the same branch (empty-asdf-registries), build still broken: 

Magit shows these recent commits:
421813c5 * empty-asdf-registries upstream/empty-asdf-registries build-scripts/build-ubuntu-package: Add Quicklisp diagnostic.    Pierre Neidhardt   17 minutes 
9a574c49 * build-scripts/build-ubuntu-package: Remove submodule ASDF registry workaround.                                        Pierre Neidhardt   39 minutes 
1cdc3add * nyxt.asd: Fix absolute location of *submodules-dir* and *quicklisp-dir*.                                              Pierre Neidhardt   39 minutes 
66bcde20 * build-scripts/build-ubuntu-package: Register submodules with ASDF.                                                    Pierre Neidhardt   58 minutes 
4300fc87 * build-scripts/build-fedora-package: Set up Quicklisp via :nyxt/quicklisp system.                                      Pierre Neidhardt    1 hour    
e7620fc5 * Makefile: Keep original load order, first load the .asd, then set up Quicklisp.                                       Pierre Neidhardt    1 hour    

build output:

make all
sbcl --no-userinit --non-interactive --eval '(require "asdf")' --eval '(asdf:load-asd "/home/jeffbowman/Projects/CommonLisp/nyxt//nyxt.asd")' --eval '(when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-system :nyxt/quicklisp))' --eval '(ql:quickload :nyxt/gtk-application)' \
	--eval '(asdf:make :nyxt/gtk-application)' \
	--eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
WARNING: redefining PERFORM (#<STANDARD-CLASS ASDF/BUNDLE:IMAGE-OP> #<STANDARD-CLASS ASDF/SYSTEM:SYSTEM>) in DEFMETHOD
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp.txt">
; 0.40KB
==================================================
408 bytes in 0.00 seconds (0.00KB/sec)
Installing dist "quicklisp" version "2021-04-11".
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp/2021-04-11/releases.txt">
; 482.50KB
==================================================
494,076 bytes in 0.35 seconds (1365.53KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp/2021-04-11/systems.txt">
; 356.79KB
==================================================
365,350 bytes in 0.31 seconds (1163.42KB/sec)
You already have the latest version of "quicklisp": 2021-04-11.
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                              {1001878233}>:
  Component "nyxt" not found, required by #<SYSTEM "nyxt/quicklisp">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001878233}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component "nyxt" not found, required by #<SYSTEM "nyxt/quicklisp"> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component "nyxt" not found, required by #<SYSTEM "nyxt/quicklisp">)
2: (INVOKE-DEBUGGER Component "nyxt" not found, required by #<SYSTEM "nyxt/quicklisp">)
3: (ERROR ASDF/FIND-COMPONENT:MISSING-DEPENDENCY :REQUIRED-BY #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> :REQUIRES "nyxt")
4: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> "nyxt" NIL)
5: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> #<FUNCTION (LAMBDA (ASDF/PLAN::DEP-O ASDF/PLAN::DEP-C) :IN ASDF/PLAN:REDUCE-DIRECT-DEPENDENCIES) {10036F886B}>)
6: (ASDF/PLAN:REDUCE-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> #<FUNCTION (LAMBDA (DO ASDF/PLAN::DC ASDF/PLAN::STATUS) :IN ASDF/ACTION:COMPUTE-ACTION-STAMP) {10036F881B}> #<ASDF/PLAN:ACTION-STATUS :BITS 4 :STAMP 3829135727 :LEVEL 0 :INDEX NIL>)
7: ((:METHOD ASDF/ACTION:COMPUTE-ACTION-STAMP (T ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) NIL #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> :JUST-DONE T) [fast-method]
8: ((:METHOD ASDF/ACTION:MARK-OPERATION-DONE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp">) [fast-method]
9: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp">)
10: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
11: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp">) [fast-method]
12: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002DCB753}>) [fast-method]
13: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
14: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002DCB753}>) [fast-method]
15: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
16: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp">)
17: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
18: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt/quicklisp">) [fast-method]
19: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP)
20: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
21: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP) [fast-method]
22: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002DB11BB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
23: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
24: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<FUNCTION (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1002C5A67B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
25: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP :NYXT/QUICKLISP) [fast-method]
26: (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)
27: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP) #<NULL-LEXENV>)
28: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PROGN (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)) #<NULL-LEXENV>)
29: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WHEN (STRING= "true" "true") (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)) #<NULL-LEXENV>)
30: (EVAL (WHEN (STRING= "true" "true") (SETF ASDF/SOURCE-REGISTRY:*DEFAULT-SOURCE-REGISTRIES* NIL) (UIOP/CONFIGURATION:CLEAR-CONFIGURATION) (ASDF/OPERATE:LOAD-SYSTEM :NYXT/QUICKLISP)))
31: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . "(asdf:load-asd \"/home/jeffbowman/Projects/CommonLisp/nyxt//nyxt.asd\")") (:EVAL . "(when (string= \"true\" \"true\") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-system :nyxt/quicklisp))") (:EVAL . "(ql:quickload :nyxt/gtk-application)") (:EVAL . "(asdf:make :nyxt/gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
32: (SB-IMPL::TOPLEVEL-INIT)
33: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
34: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
35: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition

Compilation failed, see the above stacktrace.

make: *** [Makefile:42: nyxt] Error 1

**Comment by jeffbowman** [comment]
Sorry about the font on that last message, not sure why it suddenly changed size that large... I just cut and paste from the terminal, maybe I'll do that from Emacs next time.

**Comment by Ambrevar** [comment]
This error is different, and I think you'd have the same error on master.
It's discussed on the AUR: https://aur.archlinux.org/packages/nyxt-browser-git/.

What happens if you run `make all` multiple times?

It's the strangest thing that this bug seems to affect Arch users only.

**Comment by jmercouris** [comment]
> Sorry about the font on that last message, not sure why it suddenly changed size that large... I just cut and paste from the terminal, maybe I'll do that from Emacs next time.

Don't worry, you just have to wrap things in triple backticks like this:

\```
code that will be formatted
\```

**Comment by Ambrevar** [comment]
@jeffbowman Can you report your ASDF version with

```
sbcl --noinform --eval '(print (asdf:asdf-version))' --quit
```

?

**Comment by jeffbowman** [comment]
Thanks for the tip on the triple quotes...

Ran `make all` again (no `make clean`) and it built! Weird! I'm building from source directly from a git pull rather than from the AUR package. 

Another interesting (maybe) datapoint: I run `make clean` it fails, I immediately run it it again, it passes (ie completes normally), I run it a third time and it fails again, but a fourth run and it passes. Same seems to be true for `make all`. Further, it seems I can interleave those : `make clean` (fails) `make all` (builds) `make all` (fails) `make clean` (builds) - so, only even numbered incantations work?

**Comment by jeffbowman** [comment]
`make clean` -> removes the contents of _build/quicklisp-client (build succeeds (no error))
`make clean` -> populates the contents of _build/quicklisp-client (build fails)

So, if `_build/quicklisp-client` *does not* have any contents, the subsequent `make` command fails and the contents of the directory are populated. A follow-on `make` command will now pass.

**Comment by jeffbowman** [comment]
sbcl --noinform --eval '(print (asdf:asdf-version))' --quit                                                                                            2 ↵

"3.3.1" %

**Comment by jeffbowman** [comment]
Recent commits seem to have resolved the issue for me, I have not been able to reproduce the former build failures and behavior.

**Comment by Ambrevar** [comment]
Thanks for the report.

I understand what's going on.  There were at least 3 bugs together:

- I forgot to reload the .asd after clearing the ASDF configuration.
- When running `ql:update-dist', the nyxt.asd that was loaded with
  `load-asd` is forgotten.  So I had to add it to the QL project
  directories.
- `make clean` was running `make clean-fasls` which in turn would check
  out the submodules.  I've remove `clean-fasls` since it's not useful
  for non-developers anyways.

I'm going to keep testing, I'd like to fix the Ubuntu pipeline as well.

**Comment by Ambrevar** [comment]
After months of being puzzled by this issue, and an entire day of investigation, I've finally understood where the bug lurks: it's in cffi-toolchain, where the `static-program-op` fires up a new SBCl executable and loads quicklisp with the defaults... without forwarding the local projects.

We need to report this to CFFI and replace the QL local projects with a custom ASDF registry.

**Comment by Ambrevar** [comment]
Merged with 6e14d6dff48d65e3736259df2006988a6e880efa.

**Comment by progfolio** [comment]
AUR package is building fine for me now. Thanks again.

**Comment by Ambrevar** [comment]
Fantastic!  Thanks for the update!

**Comment by progfolio** [comment]
I apologize! Seems to be broken again (may have been due to the every-other-build triggering the bug), but here is the current stack trace:

```
sbcl --no-userinit --non-interactive --eval '(require "asdf")' --eval '(when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-asd "/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser//nyxt-quicklisp.asd") (asdf:load-system :nyxt-quicklisp))' --eval '(asdf:load-asd "/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser//nyxt.asd")' --eval '(when (find-package :ql) (funcall (read-from-string "ql:quickload" :cffi)))' --eval '(when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-directories*" )) :test (quote equal)))' --eval '(ql:quickload :nyxt/gi-gtk-application)' \
	--eval '(asdf:make :nyxt/gi-gtk-application)' \
	--eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
Submodule path '_build/quicklisp-client': checked out 'b525ae5a4db984bf96a33b9c7379b3b13a4edd98'
Submodule path '_build/submodules/cl-cffi-gtk': checked out 'e9a46df65995d9a16e6c8dbdc1e09b775eb4a966'
Submodule path '_build/submodules/cl-webkit': checked out 'db855639d4a13f6ba296959cf11635b6b67421bf'
Submodule path '_build/submodules/cluffer': checked out '4aad29c276a58a593064e79972ee4d77cae0af4a'
Submodule path '_build/submodules/quri': checked out 'd7f2720568146c6674187f625f115925e6364a7f'
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp.txt">
; 0.40KB
==================================================
408 bytes in 0.00 seconds (0.00KB/sec)
Installing dist "quicklisp" version "2021-04-11".
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp/2021-04-11/releases.txt">
; 482.50KB
==================================================
494,076 bytes in 0.05 seconds (10339.35KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/dist/quicklisp/2021-04-11/systems.txt">
; 356.79KB
==================================================
365,350 bytes in 0.04 seconds (8919.68KB/sec)
; CL_SOURCE_REGISTRY: "/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser/_build/submodules//:/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser/:"
You already have the latest version of "quicklisp": 2021-04-11.
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {1001888303}>:
  The function
    #<STANDARD-GENERIC-FUNCTION QUICKLISP-CLIENT:QUICKLOAD (2)>
  requires at least 1 argument.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001888303}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" {10048A80D3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" {10048A80D3}>)
2: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" {10048A80D3}>)
3: (ERROR #<SB-INT:SIMPLE-PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" {10048A80D3}>)
4: (SB-INT:%PROGRAM-ERROR "~@<The function ~2I~_~S ~I~_requires at least ~W argument~:P.~:>" #<STANDARD-GENERIC-FUNCTION QUICKLISP-CLIENT:QUICKLOAD (2)> 1)
5: (SB-PCL::ERROR-NEED-AT-LEAST-N-ARGS #<STANDARD-GENERIC-FUNCTION QUICKLISP-CLIENT:QUICKLOAD (2)> 1)
6: (SB-PCL::INITIAL-DFUN #<STANDARD-GENERIC-FUNCTION QUICKLISP-CLIENT:QUICKLOAD (2)> NIL)
7: (SB-INT:SIMPLE-EVAL-IN-LEXENV (FUNCALL (READ-FROM-STRING "ql:quickload" :CFFI)) #<NULL-LEXENV>)
8: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WHEN (FIND-PACKAGE :QL) (FUNCALL (READ-FROM-STRING "ql:quickload" :CFFI))) #<NULL-LEXENV>)
9: (EVAL (WHEN (FIND-PACKAGE :QL) (FUNCALL (READ-FROM-STRING "ql:quickload" :CFFI))))
10: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(require \"asdf\")") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (227)) (when (string= "true" "true") (setf asdf:*default-source-registries* nil) (asdf:clear-configuration) (asdf:load-asd "/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser//nyxt-quicklisp.asd") (asdf:lo... {100188021F}>) (:EVAL . "(asdf:load-asd \"/home/n/.cache/yay/nyxt-browser-git/src/nyxt-browser//nyxt.asd\")") (:EVAL . "(when (find-package :ql) (funcall (read-from-string \"ql:quickload\" :cffi)))") (:EVAL . #<(SIMPLE-ARRAY CHARACTER (235)) (when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-dir... {1001A1C53F}>) (:EVAL . "(ql:quickload :nyxt/gi-gtk-application)") (:EVAL . "(asdf:make :nyxt/gi-gtk-application)") (:EVAL . "(uiop:quit)") (:QUIT)))
11: (SB-IMPL::TOPLEVEL-INIT)
12: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
13: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
14: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting

Compilation failed, see the above stacktrace.

make: *** [Makefile:41: nyxt] Error 1
```

**Comment by Ambrevar** [comment]
No, that's me! :)
Should be fixed with a63c5e140bc8258793977bedf9350b490fc7ccf6.

**Comment by progfolio** [comment]
Back in business. Thanks again.

**Comment by Ambrevar** [comment]
You're welcome :)

**Pull request closed without merging**
