### PR TITLE
Warn on missing password executable

### LINKED ISSUE #3213: Error using KeePassXC integration (couldn't execute "clip")
.

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This warns the user if Nyxt cannot find the executable for their password manager, instead of erroring down the line.

# Discussion

It uses `:around` method, which might be dangerous. But then, `password-mode` is all about hijacking into `password-interface` and making it more considerate, so it's aligned with the general approach.

Warning in any other place is not feasible, because it's either too early (in `password-manager`, because it mustn't know anything about Nyxt or user config) or too late (in `password:execute` and `uiop:*-program`).

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [X] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
    - Changelog update should be a separate commit.
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by jmercouris** [comment]
Is there something I am missing, would the following work?

```
(defgeneric execute (interface arguments &rest run-program-args &key wait-p &allow-other-keys)
  (:method ((interface password-interface) (arguments list) &rest run-program-args &key (wait-p t) &allow-other-keys)
    (when (executable interface)
      (apply (if wait-p #'uiop:run-program #'uiop:launch-program)
             (append (uiop:ensure-list (executable interface)) arguments)
             (alexandria:remove-from-plist run-program-args :wait-p))))
  (:documentation "Execute the command matching the INTERFACE, with ARGS.

`uiop:run-program' is used underneath, with RUN-PROGRAM-ARGS being its
arguments.

When the WAIT-P is NIL, `uiop:launch-program' is used instead of
`uiop:run-program'."))
```

@aadcg @aartaka ?

**Comment by jmercouris** [comment]
Of course we would then have to put guards in Nyxt to see if a function returns nil...

**Comment by aartaka** [comment]
> Note the this PR needs to be rebased onto master.

Done :white_check_mark:

**Comment by aartaka** [comment]
It errors on me with this piece of config (ensuring NIL value):
``` lisp
(define-configuration :password-mode
  ((password-interface (make-instance 'password:keepassxc-interface :executable nil))))
```

**Comment by aartaka** [comment]
Commands that use password interface will get an error and warn the user about it. Good pattern? Good pattern.

**Comment by aartaka** [comment]
I tried it with the snippet I provided, which should be equivalent to the environment you described. I've also tried to reproduce on binary build. This is what I got:
error

What exactly looks off to you?

**Comment by aadcg** [comment]
Stale.

**Pull request closed without merging**
