### PR TITLE
Catch all errors! O.o

### PR DESCRIPTION
**Pull request by Ambrevar**
This is certainly one of my most important contributions: it catches hopefully all Lisp errors at runtime, which means no more Lisp-induced crashes for Nyxt!

2-pre-release-6 introduced many crash regressions for stupid mistakes that should not have crashed the browser anyways.

With this patchset, this kind of errors are reported, but won't crash the browser anymore!

This introduces a few changes:

- Removal of `funcall-safely`.  Hopefully OK, please test.
- Renamed `*keep-alive*` to the more meaningful `*run-from-repl-p*`.
- Renamed `with-muffled-body` to the more accurate `with-protect`.

Please test and let me know what you think! :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Important note:
In the future, we should always use `run-thread` instead of `bt:make-thread` and `within-gtk-thread` instead of `gtk:within-gtk-thread`.

**Comment by jmercouris** [comment]
Oh boy oh boy, let me give this bad boy a try :-D

**Comment by jmercouris** [comment]
Appears to work... :-D

**Comment by Ambrevar** [comment]
I just had a hang...
Let's keep using it for a day at least (from the binary, _not from the REPL_).

**Comment by jmercouris** [comment]
Well, that will have to be you for now, I can ONLY run from a REPL :-/

**Comment by Ambrevar** [comment]
Why?
Can I help you build the Nyxt binary?

**Comment by jmercouris** [comment]
Indeed, as we discussed, we can try to figure it out on Monday :-)

**Comment by Ambrevar** [comment]
Actually, you can test the new behaviour from the REPL too if you set `*run-from-repl-p*` to NIL before starting Nyxt.

**Comment by jmercouris** [comment]
I'm not sure that would achieve what we want. I would still be attached to the slime debugger. I still believe only you can test for now.

**Comment by Ambrevar** [comment]
Precisely: if you see the SLIME debugger, it means it didn't work!
So it would test what we want.

**Comment by jmercouris** [comment]
Ah, I see! OK! I will do that then.

**Comment by Ambrevar** [comment]
Thanks!

I've been running it for some time now, looks fine so far.

**Comment by Ambrevar** [comment]
It's working for me all day.

OK to merge?

**Comment by jmercouris** [comment]
Is it OK if I keep using Nyxt over the weekend first?

**Comment by Ambrevar** [comment]
Sure!

**Comment by jmercouris** [comment]
No problems, feel free to merge!

**Comment by Ambrevar** [comment]
Merged!

**Pull request closed without merging**
