### PR TITLE
manual: Fix warnings on load-lisp and load-config-lisp.

### PR DESCRIPTION
**Pull request by Ambrevar**
This should fix the CI with CCL.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [x] ASDF dependencies,
  - [x] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [x] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [x] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - [x] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [x] I have updated the existing documentation to match my changes.
  - [x] I have commented my code in hard-to-understand areas.
  - [x] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [x] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [x] Compilation and tests:
  - [x] My changes generate no new warnings.
  - [x] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@aartaka @aadcg OK to you?

**Comment by aartaka** [comment]
Yes, looks OK to me.

**Comment by aadcg** [comment]
Look good to me.

I have a minor remark.  Commit 97872b8bd introduces a change to `nyxt.asd` that is reverted in 2109d532a. The latter should be squashed into the former. Or, if you think it's important to separate them, then commit 97872b8bd should have no changes to `nyxt.asd`.

Why do I find this important? First of all, it's easier on the reviewer. Second, we should not pollute our history with the thought process by which a PR came about (in my opinion of course).

**Comment by jmercouris** [comment]
I actually disagree Andre. I think it is important that we tell the story of the development process via the commit log. Someone will look at it and say: why didn't they do it way X? But if they see way X was tried, then they will know it was considered, and probably *why* it was not pursued.

**Comment by Ambrevar** [comment]
Merged with 7eeee5b4ac56660cfc973f18f93184b5a86fdc83.

Agreed with both John and André, but in this case the double commit was actually due to me forgetting to rebuild before I pushed: nothing interesting to remember here.  So I squashed.

**Pull request closed without merging**
