### PR TITLE
status.lisp: show enabled modes

### PR DESCRIPTION
**Pull request by jmercouris**
additionally allow clicking to toggle enable/disable modes

### CODE REVIEW

**Comment by Ambrevar** [comment]
OK, it's better, the only thing is that the circled `i` only displays if you've got the font.  I don't! :p 
Any alternative?

@jmercouris Which fonts do you have on your system?  Maybe we should have Nyxt depend on some lightweight fonts, like the awesome fonts.

**Comment by jmercouris** [comment]
I use noto font on my system, let me look for a more common symbol. I'm hesitant to include a font in Nyxt, maybe we will have to at some point!

**Comment by Ambrevar** [comment]
Unfortunately, Noto is 1.5 GiB strong, so it's a big no-no for lots of
people :p

**Comment by jmercouris** [comment]
Do you have 'ℹ'?

**Comment by jmercouris** [comment]
Do you have '⊕'?

**Comment by jmercouris** [comment]
Do you have '⏼'?

**Comment by Ambrevar** [comment]
I have `⊕`.

**Pull request merged**
