### PR TITLE
Fix slow hints

### PR DESCRIPTION
**Pull request by Ambrevar**
Fix all points mentioned in https://github.com/atlas-engineer/nyxt/issues/1784.

@aartaka @jmercouris Let me know if it looks OK to you.
Once approved, I'll forward-port this to master.

### CODE REVIEW

**Comment by aartaka** [comment]
Looks all fine to me!

I'm curious, though: can we speed up `merge-url*` somehow? Is it possible to avoid all the branching and copying here? I feel that it could become the next bottleneck.

**Comment by shamazmazum** [comment]
Not asking DNS to resolve everything you are typing is super nice!

**Comment by jmercouris** [comment]
Not as fast as my solution, but it is correct :-D

Thank you for this monsieur!

**Comment by jmercouris** [comment]
(whereas my solution has bugs :-D)

**Comment by Ambrevar** [comment]
@aartaka: Indeed, this `valid-url-p` with all the branching is still slow, but note that it's no longer used by element hints.

Let's optimize it when the need arises and `valid-url-p` is shown to be a bottleneck again.

**Pull request merged**
