### PR TITLE
Rename: %slot-default -> %slot-default%

### PR DESCRIPTION
**Pull request by jmercouris**
%xyz% is for special local variables

for some reason, this does not work, I do not believe to have missed any instances. Any idea why?

### CODE REVIEW

**Comment by Ambrevar** [comment]
What's the error?

**Comment by jmercouris** [comment]
It fails on my configuration saying %slot-default% is undefined.

**Comment by jmercouris** [comment]
I see the problem now! Projectile replace failed me!

**Comment by aadcg** [comment]
> Projectile replace failed me!

A suggestion if you're on emacs 27. Run `project-find-regexp`, an `*xref*` buffer pops up, and then run `xref-query-replace-in-results` (which by default is bound to `r`).

**Pull request merged**
