### PR TITLE
Fix prompter race conditions and memory leaks

### PR DESCRIPTION
**Pull request by Ambrevar**
This is a follow up to #1606.  The Git history is based on it, but should be merged independently.

It includes fixes to the prompter, but not everything is solved yet.

The starting point is to remove the memory leaks by free-ing the prompt buffer web view:

```lisp
(defun hide-prompt-buffer (prompt-buffer)
  "Hide PROMPT-BUFFER, display next active one."
  (let ((window (window prompt-buffer)))
    ;; Note that PROMPT-BUFFER is not necessarily first in the list, e.g. a new
    ;; prompt-buffer was invoked before the old one reaches here.
    (alex:deletef (active-prompt-buffers window) prompt-buffer)
    (if (resumable-p prompt-buffer)
        (flet ((prompter~ (prompter1 prompter2)
                 (and (not (eq prompter1 prompter2))
                      (string= (prompter:prompt prompter1)
                               (prompter:prompt prompter2))
                      (string= (prompter:input prompter1)
                               (prompter:input prompter2)))))
          ;; Delete a previous, similar prompt, if any.
          (alex:when-let ((old-prompt (find prompt-buffer (old-prompt-buffers *browser*)
                                            :test #'prompter~)))
            (alex:deletef (old-prompt-buffers *browser*)
                          old-prompt)
            (ffi-buffer-delete old-prompt))
          (push prompt-buffer (old-prompt-buffers *browser*)))
        (ffi-buffer-delete prompt-buffer))
    (if (active-prompt-buffers window)
        (let ((next-prompt-buffer (first (active-prompt-buffers window))))
          (show-prompt-buffer next-prompt-buffer))
        (ffi-window-set-prompt-buffer-height window 0))))
```

This opens a pandora box though: fire up any prompt buffer 3-4 times until it starts echoing

```
<WARN> [13:35:42] Warning: JavaScript error: GError: Domain: "WebKitJavascriptError", Code: 699, Message: 
```

and the prompt buffer no longer displays.

 I believe this is because at one point Nyxt tries to evaluate JS in a web view that got garbage-collected, which triggers an error, which leaves the broken prompt buffer active and thus prevents any further display.

I feel that I'm really close to nailing this :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Note that I could root out the origin of the leak thanks to the new memory tracking helpers introduced in https://github.com/atlas-engineer/nyxt/pull/1612/commits/0d82b0344770158a3e18a94e3301bda6301f370c: SBCL is amazing!

**Comment by Ambrevar** [comment]
@jmercouris @aartaka Have a look at the aforementioned commit and the examples in the docstring: it's amazing stuff, nah?  :)

**Comment by jmercouris** [comment]
will do!

**Comment by jmercouris** [comment]
just took a brief look. Very interesting! We can track literally all allocations over time! This would make some great graphs!

**Comment by aartaka** [comment]
Oh wow! 0_o

**Comment by Ambrevar** [comment]
Closing in favour of #1646.

**Pull request closed without merging**
