### PR TITLE
gtk.lisp: Web context sharing and separation (MASTER)

### PR DESCRIPTION
**Pull request by Ambrevar**
This is a follow up to #1757 and #1987.
It's rebased on `master` and should address all suggestions  from the previous pull requests.

This will hopefully fix the sudden log-out issues and such.

Fixes:
- #1733 
- #1640

Maybe fixes:
- #797
- #837
- #1625 
- #1787

To do after merging:
- #1805 
- #1875 (initialize-modes)

### Things to discuss

 - Can we have multiple non-persisted contexts?
  According to Artyom, yes!
- Should non-web-buffers have a `status` now that we load them like any other buffer?
  Otherwise we must protect all `status' accesses, which is cumbersome.  See 671f4b41c7cdf73b7bc662de109b17374c0112af.
  Also a yes!

- Do you like the `make-buffer-with-context` command name?
  Remove it and instead add a prompt-buffer to `make-buffer` with the `new-query-url` source and a bunch of actions, some of which would set the context, the tag, the class (`nosave`), etc.  Then also remove `make-nosave-buffer`?

### CODE REVIEW

**Comment by babariviere** [comment]
Just tested your merge request, the history is no longer stored.

I keep getting this warning while running `history-backwards` command.

```
<WARN> [13:29:26] Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
```

With debug logs:

```
<DEBUG> [13:37:39] nyxt input.lisp (dispatch-input-event) -
  Found key binding "C-b" [C-#56] to HISTORY-BACKWARDS
Backtrace for: #<SB-THREAD:THREAD "Nyxt run-async command" RUNNING {100D28DAA3}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7F756C50591B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {100D29C72B}> :PACKAGE :CL)
4: ((:METHOD LOG4CL-IMPL:APPENDER-DO-APPEND (NYXT::MESSAGES-APPENDER T T T)) #<NYXT::MESSAGES-APPENDER {101037E923}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}>) [fast-method]
5: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOGGER +ROOT+ {10019AA213}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}>)
6: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT NIL {10020F87D3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}>)
7: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100261A3B3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}>)
8: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}>)
9: (LOG4CL-IMPL::LOG-WITH-LOGGER #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7F756C505D8B}> #<PACKAGE "NYXT">)
10: (NYXT:ECHO-WARNING "Error on separate thread: ~a" "There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6")
11: ((FLET "H0" :IN NYXT::RUN-ASYNC) #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100D292643}>)
12: (SB-KERNEL::%SIGNAL #<SB-PCL::NO-APPLICABLE-METHOD-ERROR {100D292643}>)
13: (ERROR SB-PCL::NO-APPLICABLE-METHOD-ERROR :GENERIC-FUNCTION #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)> :ARGS (NIL))
14: ((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)> NIL) [fast-method]
15: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)> (NIL))
16: ((:METHOD HISTORY-TREE:BACKWARD (HISTORY-TREE:HISTORY-TREE T)) #<HISTORY-TREE:HISTORY-TREE {10067DA103}> "944" 1) [fast-method]
17: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN NYXT/WEB-MODE:HISTORY-BACKWARDS))
18: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
19: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN NYXT/WEB-MODE:HISTORY-BACKWARDS) {7F756C50646B}> #<SB-THREAD:MUTEX "user-data lock" owner: #<SB-THREAD:THREAD "Nyxt run-async command" RUNNING {100D28DAA3}>> T NIL)
20: (NYXT/WEB-MODE:HISTORY-BACKWARDS #<NYXT:USER-BUFFER 944 {10074F5F23}>)
21: ((LAMBDA NIL :IN NYXT::RUN-ASYNC))
22: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))
25: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
26: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::RUN))
27: (SB-THREAD::RUN)
28: ("foreign function: call_into_lisp")
29: ("foreign function: funcall1")
 <WARN> [13:37:39] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: Error on separate thread: There is no applicable method for the generic function
  #&lt;STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)&gt;
when called with arguments
  (NIL).
See also:
  The ANSI Standard, Section 7.6.6
```

<details>
<summary>`nyxt --system-information`</summary>

```
guix shell --pure -D -f build-scripts/nyxt.scm -- ./nyxt --system-information
Nyxt version: 2.1.1-1472-g2d678d04
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.90
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE
 :NYXT-G2D678D04 :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS
 :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES
 :PARENSCRIPT :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL
 :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/hqj5vp8c477g0brkfhk90x6kakqka612-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/1pnsazwwrkwmy84dididqx9g0f5za1ka-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/qhh0k5gwlrihybjiqxwss0vcn1p6a8bn-cl-webkit-3.5.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)
```
</details>

### Steps to reproduce

1. Open `nyxt`
2. Type `C-l hello world`
3. Open first url
4. Press `C-b` and get the error

**Comment by Ambrevar** [comment]
@babariviere Thanks for reporting!  Should be fixed now, and I've seized the opportunity to strengthen our history calls.

**Comment by babariviere** [comment]
I prefer not to bother too much, but I got the following error with the same steps as before.

<details>
<summary><b>Debug logs</b></summary>

```
<DEBUG> [17:14:28] nyxt input.lisp (dispatch-input-event) -
  Found key binding "C-b" [C-#56] to HISTORY-BACKWARDS
Backtrace for: #<SB-THREAD:THREAD "Nyxt run-async command" RUNNING {101067FD63}>
0: ((LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE))
1: ((FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX))
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<FUNCTION (FLET "THUNK" :IN UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX) {7FA29C55DA8B}>)
3: (UIOP/STREAM:CALL-WITH-SAFE-IO-SYNTAX #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:PRINT-BACKTRACE) {101068F1FB}> :PACKAGE :CL)
4: ((:METHOD LOG4CL-IMPL:APPENDER-DO-APPEND (NYXT::MESSAGES-APPENDER T T T)) #<NYXT::MESSAGES-APPENDER {1010366643}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}>) [fast-method]
5: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOGGER +ROOT+ {10019AA213}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}>)
6: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT NIL {10020F87D3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}>)
7: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100261A3B3}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}>)
8: ((LABELS LOG4CL-IMPL::LOG-TO-LOGGER-APPENDERS :IN LOG4CL-IMPL::LOG-WITH-LOGGER) #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}>)
9: (LOG4CL-IMPL::LOG-WITH-LOGGER #<LOG4CL-IMPL::FILE-LOGGER NYXT.ECHO-WARNING.FORM-FUN-6 /home/babariviere/src/github.com/atlas-engineer/nyxt/source/message.lisp {100281F103}> 3 #<FUNCTION (FLET "log-stmt9" :IN NYXT:ECHO-WARNING) {7FA29C55DEFB}> #<PACKAGE "NYXT">)
10: (NYXT:ECHO-WARNING "Error on separate thread: ~a" "The value of QURI::URI1 is #&lt;HISTORY-TREE:NODE {100CBEDAA3}&gt;, which is not of type QURI.URI:URI.")
11: ((FLET "H0" :IN NYXT::RUN-ASYNC) #<SIMPLE-TYPE-ERROR expected-type: QURI.URI:URI datum: #<HISTORY-TREE:NODE {100CBEDAA3}>>)
12: (SB-KERNEL::%SIGNAL #<SIMPLE-TYPE-ERROR expected-type: QURI.URI:URI datum: #<HISTORY-TREE:NODE {100CBEDAA3}>>)
13: (ERROR #<SIMPLE-TYPE-ERROR expected-type: QURI.URI:URI datum: #<HISTORY-TREE:NODE {100CBEDAA3}>>)
14: (SB-KERNEL:WITH-SIMPLE-CONDITION-RESTARTS ERROR NIL #<SIMPLE-TYPE-ERROR expected-type: QURI.URI:URI datum: #<HISTORY-TREE:NODE {100CBEDAA3}>>)
15: (SB-KERNEL:CHECK-TYPE-ERROR QURI::URI1 #<HISTORY-TREE:NODE {100CBEDAA3}> QURI.URI:URI NIL)
16: (QURI::%URI= #<unavailable argument> #<QURI.URI.HTTP:URI-HTTPS https://#1=github.com/flameshot-org/flameshot> :NORMALIZE-PATH-P NIL)
17: (NYXT/WEB-MODE::LOAD-HISTORY-URL #<HISTORY-TREE:NODE {100CBEDAA3}> :BUFFER NIL :MESSAGE "No backward history.")
18: (NYXT/WEB-MODE:HISTORY-BACKWARDS #<NYXT:USER-WEB-BUFFER 952 {1010770073}>)
19: ((LAMBDA NIL :IN NYXT::RUN-ASYNC))
20: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
21: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
22: ((FLET "WITHOUT-INTERRUPTS-BODY-10" :IN SB-THREAD::RUN))
23: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
24: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-THREAD::RUN))
25: (SB-THREAD::RUN)
26: ("foreign function: call_into_lisp")
27: ("foreign function: funcall1")
 <WARN> [17:14:28] nyxt message.lisp (echo-warning form-fun-6) -
  Warning: Error on separate thread: The value of QURI::URI1 is #&lt;HISTORY-TREE:NODE {100CBEDAA3}&gt;, which is not of type QURI.URI:URI.
```
</details>

<details>
<summary>System information</summary>

```
Nyxt version: 2.1.1-1475-g76fecd19
Renderer version: GI-GTK
Operating system kernel: Linux 5.10.90
Lisp implementation: SBCL 2.1.9 (Dynamic space size: 3221225472)
Features: (:WEBKIT2 :WEBKIT2-2.34 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT
 :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA
 :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14
 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20
 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4
 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :GLIB-2-30 :GLIB-2-32 :GLIB-2-34
 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48
 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB :NYXT-UNSTABLE
 :NYXT-G76FECD19 :NYXT-2.1.1 :NYXT-2.1 :NYXT-2 :FSET-EXT-STRINGS
 :CUSTOM-HASH-TABLE-NATIVE :SWANK :PLUMP-UTF-32 :GLOBAL-VARS :DECLARE-TYPES
 :PARENSCRIPT :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :LPARALLEL
 :21BIT-CHARS :CLOSER-MOP :CL-PPCRE-UNICODE :CL-UNICODE
 :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CL-PPCRE
 :CHUNGA :FLEXI-STREAMS :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :GENCGC :64-BIT :ANSI-CL
 :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

ASDF version: 3.3.5
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY USER-SOURCE-REGISTRY
                      USER-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-USER-SOURCE-REGISTRY SYSTEM-SOURCE-REGISTRY
                      SYSTEM-SOURCE-REGISTRY-DIRECTORY
                      DEFAULT-SYSTEM-SOURCE-REGISTRY)
Critical dependencies: (/gnu/store/hqj5vp8c477g0brkfhk90x6kakqka612-cl-cffi-gtk-0.11.2-2.e9a46df/share/common-lisp/source/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /gnu/store/1pnsazwwrkwmy84dididqx9g0f5za1ka-cl-gobject-introspection-0.3-1.d0136c8/share/common-lisp/source/cl-gobject-introspection/cl-gobject-introspection.asd
 /gnu/store/qhh0k5gwlrihybjiqxwss0vcn1p6a8bn-cl-webkit-3.5.0/share/common-lisp/source/cl-webkit/webkit2/cl-webkit2.asd)
```
</details>

Tell me if you need additional information. I will happily test this in more depth if required!

**Comment by Ambrevar** [comment]
Thanks for reporting again, this is very helpful!

I made a mistake indeed in the original fix.  Should be fixed for good now.  I've also fixed an issue where adding some default modes like reduce-tracking-mode would raise a condition.

@aartaka @pdelfino @jmercouris Please test! :)

**Comment by jmercouris** [comment]
OK! Will do!

**Comment by babariviere** [comment]
@Ambrevar I can confirm the history is fixed!

**Comment by Ambrevar** [comment]
Thanks, @babariviere !

**Comment by Ambrevar** [comment]
@aartaka @jmercouris OK to merge?

**Comment by aartaka** [comment]
Yes, fine to merge! 

It's confusing that contexts are not displayed anywhere (like mode line) and one (it seems) cannot create a new context in the `make-buffer-with-context` prompt, but those we can fix after merging.

**Comment by Ambrevar** [comment]
Indeed, he make-buffer-with-context is really just a prototype for now,
mainly meant for testing.

I'll open issues about your very relevant comments.

Also when #2072 is in, we would need to merge the `context-name` and
`profile` buffer slots.

**Comment by aartaka** [comment]
Sounds like a plan! :D

**Comment by Ambrevar** [comment]
> one (it seems) cannot create a new context in the `make-buffer-with-context` prompt

Actually what do you mean here?  The command has two source, the first one is for creating new contexts.  Trying typing something, you'll see!

**Comment by Ambrevar** [comment]
Merged with a645ed180386016d0b3db06ddf73a64b94d3c8f3.

The rebasing was a bit difficult.  @aartaka Can you make sure it looks OK to you?  In particular the `make-context` function with this bit:

```lisp
      (unless (or ephemeral-p
                  (internal-context-p name))
        (webkit:webkit-web-context-add-path-to-sandbox
         context (namestring (asdf:system-relative-pathname :nyxt "libraries/web-extensions/")) t)
        (unless (uiop:emptyp gtk-extensions-path)
          ;; TODO: Should we also use `connect-signal' here?  Does this yield a memory leak?
          (gobject:g-signal-connect
...
```

Should `webkit:webkit-web-context-add-path-to-sandbox` be callse for internal contexts as well?

**Comment by Ambrevar** [comment]
Also before closing let's answer the `Things to discuss` in the original post.  @aartaka What do you think?

**Comment by aartaka** [comment]
> Should `webkit:webkit-web-context-add-path-to-sandbox` be callse for internal contexts as well?

Yes, it is safe to call there, as extensions store no thing on the disk except the dynamic library that is already there anyway.

**Comment by aartaka** [comment]
Wait, it's merged, isn't it?

**Comment by Ambrevar** [comment]
Yes, but we still need to implement the "Things to disucss".

**Comment by aartaka** [comment]
> Yes, but we still need to implement the "Things to disucss".

Feels like something to move to an issue :p

**Comment by Ambrevar** [comment]
Done with #2104.

**Comment by aartaka** [comment]
Thanks!

**Pull request closed without merging**
