### PR TITLE
command: Hide deprecated commands (don't add them to *command-list*).

### PR DESCRIPTION
**Pull request by Ambrevar**
While we are at it, factor out some code, it's even shorter now.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@jmercouris @aartaka Thoughts about this?

**Comment by aartaka** [comment]
Feels right!

**Comment by Ambrevar** [comment]
Bindings still work, merging.

**Comment by jmercouris** [comment]
I found this patch to be difficult to read. I think it is too clever.

**Comment by jmercouris** [comment]
Ignore my previous comment, I confused this with the other patch...!

**Comment by Ambrevar** [comment]
Which one?

**Comment by jmercouris** [comment]
I've left some comments now.

**Comment by Ambrevar** [comment]
You mean https://github.com/atlas-engineer/nyxt/pull/1587?

**Comment by jmercouris** [comment]
Yes.

**Pull request closed without merging**
