### PR TITLE
Library move

### PR DESCRIPTION
**Pull request by jmercouris**
Move quicklisp-libraries -> libraries.

### CODE REVIEW

**Comment by jmercouris** [comment]
@Ambrevar :-D?

**Comment by Ambrevar** [comment]
I'm hot on the pipeline today, no worries, I'll get to it! :)

**Comment by jmercouris** [comment]
:-D

**Comment by Ambrevar** [comment]
The patch seems correct (I haven't tested) but I'm having second thoughts: in the past we've had issues with people having stale libraries in quicklisp-libraries.
Having a separate folder makes it easier to just tell them "delete the content of the `quicklisp-libraries` folder".  Without a separate directory, we'd need to list the exact Nyxt-owned libraries to keep.

Does that make sense?
Can you think of a better way to do it?

Of course, should we adopt CLPM #1065, none of this would be an issue, we would not even need submodules in the first place.

**Comment by jmercouris** [comment]
I think all git submodules should be updated, whether they are on quicklisp or not. We should be able to just give them a command to update all submodules. Therefore, I think it would still be OK. What do you think?

**Comment by Ambrevar** [comment]
Misunderstanding.  What I'm saying is unrelated to the update of git
submodules.

The problem is when people try to build _without_ using the submodules,
for instance using Guix, Nix or ~/common-lisp.

In this case, having the library submodules checked out may create a
conflict (for instance if they forgot NYXT_INTERNAL_QUICKLISP=false).
Should we move submodules to libraries, ASDF would have no way to know
whether to load the Guix package or the library in `nyxt/libraries`.

Does that make sense?

**Comment by jmercouris** [comment]
I'm not sure I understand. How could someone build without using the submodules? Using their own outdated quicklisp?

Can we not force the makefile to use the libraries located in the libraries folder when `NYXT_INTERNAL_QUICKLISP=true`?

**Comment by jmercouris** [comment]
Oh, I see, you don't mean literally without the source of those submodules, you mean without the mechanism of the git submodules for retrieving said source!

**Comment by jmercouris** [comment]
In that case, is what I said still not true? Can our makefile not impose certain behaviors on ASDF based on the value of 'NYXT_INTERNAL_QUICKLISP`?

**Comment by Ambrevar** [comment]
Example with Guix: Nyxt is built using the cl-cluffer (or sbcl-cluffer)
package.  The submodules are never retrieved when using Guix.

**Comment by Ambrevar** [comment]
Currently, when NYXT_INTERNAL_QUICKLISP is false, quicklisp-libraries is
not added to ADSF search path.

But `libraries` is always added.

So if we move the submodules to `libraries`, we have no way to say
"don't load the submodules" anymore.

**Pull request closed without merging**
