### PR TITLE
tests.yml: update libfixposix version.

### PR DESCRIPTION
**Pull request by aadcg**
Solves #1197

### CODE REVIEW

**Comment by Ambrevar** [comment]
The CI uses ubuntu-latest, not Debian.

GitHub is in the process of updating ubuntu-latest to 20.04, maybe they've just rolled out the update.

**Comment by aadcg** [comment]
> The CI uses ubuntu-latest, not Debian.

I thought it doesn't matter since both use apt. Ubuntu-latest must use the stable apt "channel" or whatever it's called.

I don't have permissions to re-run this job, but could you please do it for me?

**Comment by Ambrevar** [comment]
It matters: APT is only the program, while the distribution repository
are a whole different thing.

Packages that are in Ubuntu are not necessarily in Debian and vice
versa.

Also distribution version matters.

**Comment by aadcg** [comment]
The only thing happening here is that the github runners moved to
a newer ubuntu version and the packages of apt changed.  When you
wrote `tests.yml` it was called `libfixposix0`, but now it's
called `libfixposix3`.  Why?  No idea.

Keep in mind that my understanding is very shallow but here's
what I think.

It doesn't seem to make much sense to test on ubuntu everytime a
commit lands on master.  That would make sense to happen on every
release (perhaps only the proper ones, not the pre-releases) tho.
It is when you do a release that you want to exhaust all of the
possible combinations to make sure stuff works.  This is what you
call a "matrix".

Now, it also makes sense to test when commits land on master.
But I'd stick to guix and nix for that.  Assuming that the cl
build system will be fixed in nix soon, we could even forget
about guix since it would ensure that we have a healthy nyxt on
gnu/linux and macOS.  Well, only if it weren't for our
fervant (but JUSTIFIED) beliefs that guix is orders of magniture
better than nix.  I see guix today as a way to have "consensus"
among nyxt devs.  I don't see why we should care to have
a "multi-platform" dev environment.  Guix even allows us to build
with and without quicklisp.

As a rule of thumb we should think about dev, test and production
envs.  For dev I'd make it as minimal and dumb as possible, but
highly reliable and dependable (in other words, guix).  For test
we need to care about more things like testing on ubuntu on the
current latest release, possibly try to see how it behaves with
other cl compilers, etc.  For production, well, unless we'll
start to have some kind of NaaS (Nyxt as a service) running on
the cloud, I don't see the point.

Hopefully I didn't say anything too stupid :)

**Comment by aadcg** [comment]
> This is expected indeed, I just don't see why it previously failed for
you, then stopped failing.

Perhaps I wasn't clear. It seems that the github runners update took effect first on my fork, and later on this repository. I made this change and the job run succesfully on my fork, but then it failed when I started this PR. Then, I asked you to re-run and it passed!

> We test on Ubuntu because it's been the easiest route to deploy a test
pipeline since it's what GitHub actions offer.

I see. I'm not sure about pinning a version though. This should me merged ASAP so that we stop getting annoying e-mails :)

> A few months ago Guix didn't run well in Docker for pipelines.  There's
been some work done since then, I need to retry.

I see. Can I be of help?

**Comment by Ambrevar** [comment]
> Perhaps I wasn't clear. It seems that the github runners update took effect first on my fork, and later on this repository. I made this change and the job run succesfully on my fork, but then it failed when I started this PR. Then, I asked you to re-run and it passed!

Oh, OK, yes that would make sense.

> I see. I'm not sure about pinning a version though. This should me merged ASAP so that we stop getting annoying e-mails :)

Done.

>> A few months ago Guix didn't run well in Docker for pipelines.  There's
> been some work done since then, I need to retry.
>
> I see. Can I be of help?

If you can set a GitHub action to run Guix and build Nyxt, that'd be grand!

**Pull request merged**
