### PR TITLE
Dynamic print status

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

In https://github.com/atlas-engineer/nyxt/issues/2219#issuecomment-1141024604 I introduced a draft of how we could avoid hard-coding the calls to `print-status`.

This is useful since it allows the user to customize what triggers a status buffer re-print.

# Discussion

1. [x] Each time a `status-buffer' is created the defmethods are redefined, which triggers warnings.  Can we somehow report warning only when a  _non-watcher_ method exists?  Yes, see a2109f9de5c8852982db53a57301096120996d86.
2. [ ] I've re-introduced the `mode` `enabled-p` accessor, but the writer should not be called externally.  But we can add a setf "watcher" only on slots with writers.  Unless... Is it possible to add an `:after` method to `(setf (slot-value ...))`?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by Ambrevar** [comment]
I think a2109f9de5c8852982db53a57301096120996d86 fixes the redefinition warning.

**Comment by Ambrevar** [comment]
Ready to merge on my end.

**Comment by Ambrevar** [comment]
Another way to add slot "watchers" could be to use the Cells library: https://github.com/kennytilton/cells

But that may be too much for what we want there.

**Comment by aadcg** [comment]
I agree that going forward with the Cells library isn't a good idea today.

**Comment by Ambrevar** [comment]
Merged with 324ad2d904b1a834433ee82c56c30c3964cb811d.  I don't know what to do with the `enabled-p` slot, I guess we will see when the time comes.

**Pull request closed without merging**
