### PR TITLE
[REBASE] User scripts (Greasemonkey/Tampermonkey-like) support

### PR DESCRIPTION
**Pull request by Ambrevar**
Rebase of #2139.

@aartaka Can you test see if it behaves the way you expect?  In particular, recursive includes should be supported.

### CODE REVIEW

**Comment by Ambrevar** [comment]
The original post in https://github.com/atlas-engineer/nyxt/pull/2139 mentions a few missing parts.  Shall we open new issues for them?

**Comment by aartaka** [comment]
> The original post in #2139 mentions a few missing parts. Shall we open new issues for them?

Yes!

**Comment by aartaka** [comment]
@Ambrevar, the user class infrastructure is broken for this PR -- there are still old `define-user-class` and inverted inheritance around user scripts. The right way ™️  to handle users scripts would be to define `renderer-user-script` mixin and use `(:metaclass user-class)` for `user-script`, I suppose?

**Comment by Ambrevar** [comment]
Can you open the related issues then?  You have a better understanding of what it's about.

I'll fix the class issue.

**Comment by Ambrevar** [comment]
Sorry for not testing the rebase.  It's done now, the following works for me:

```lisp
(make-instance 'nyxt/web-mode:user-script  :base-path "extra-button42.js" :url (quri:uri "https://greasyfork.org/scripts/7543-google-search-extra-buttons/code/Google%20Search%20Extra%20Buttons.user.js"))

(nfiles:content *)
```

**Comment by aartaka** [comment]
@Ambrevar, I've tested it and fixed some bugs left from my initial implementation. However, it's still not injecting scripts properly, because `get-script-url` implies that `script` is a string, which it is not.

**Comment by aartaka** [comment]
More testing, yay!

**Comment by Ambrevar** [comment]
Can you share a full example for testing?

**Comment by aartaka** [comment]
Sure, here it is:
``` lisp
(defmethod customize-instance ((mode nyxt/web-mode:web-mode) &key)
  (setf (nyxt/web-mode:user-scripts mode)
        (list
        (make-instance 'nyxt/web-mode:user-script
                        :base-path (nyxt-init-file "darkreader.user.js"))
         (make-instance 'nyxt/web-mode:user-script
                        :base-path (nyxt-init-file "hide-youtube-google-ad.user.js")
                        :url "https://greasyfork.org/scripts/38182-hide-youtube-google-ad/code/Hide%20youtube%20google%20ad.user.js")
         )))
```

Where darkreader.user.js is
``` js
// ==UserScript==
// @name          Dark Reader (Unofficial)
// @icon          https://darkreader.org/images/darkreader-icon-256x256.png
// @namespace     DarkReader
// @description	  Inverts the brightness of pages to reduce eye strain
// @version       4.7.15
// @author        https://github.com/darkreader/darkreader#contributors
// @homepageURL   https://darkreader.org/ | https://github.com/darkreader/darkreader
// @run-at        document-end
// @grant         none
// @include       http*
// @require       https://cdn.jsdelivr.net/npm/darkreader/darkreader.min.js
// @noframes
// ==/UserScript==

DarkReader.enable({
	brightness: 80,
	contrast: 60,
	sepia: 0
});
```

**Comment by Ambrevar** [comment]
Your issue is because you rely on `nyxt-init-file`.  It automatically appends ".lisp" to the file (see the docstring).

What you want to use instead is

```lisp
(nfiles:expand (make-instance 'nyxt/web-mode:user-script
																				:base-path (nfiles:expand (make-instance 'init-directory-file :base-path "darkreader.user.js"))))
```

I've pushed a fix for `init-directory-file` as well as one for GTK to avoid loading empty scripts.

Does that make sense?

**Comment by aartaka** [comment]
Indeed, my bad ｜−・;）

**Comment by Ambrevar** [comment]
OK to merge then?

**Comment by Ambrevar** [comment]
Thanks for reporting.  There was indeed a bug in Nfiles: when the remote-file exist, it would overwrite it with empty url-content.  `git pull` the latest and let me know if it works now.  If so, I'll release a new tag.

I've also updated this branch with a fix: previously the `require' scripts could be plain, non-UserScript javascripts, in which case `nfiles:deserialize` would return NIL.  Now it returns the plain script, and it only sets `code`.

Do you think this is the right behaviour?

**Comment by aartaka** [comment]
The only requirement for `@require` is that they are valid JS files, not necessarily userScript ones! 

For other types of content, there's `@resource` property.

**Comment by Ambrevar** [comment]
So my fix is alright, then, isn't it?

**Comment by aartaka** [comment]
I've pushed a small fix for script `blocklist` to not override script `allowlist`. This and nfiles fix make user scripts to finally work for me, yay!

**Comment by aartaka** [comment]
Tag the nfiles release and we're good to merge!

**Comment by Ambrevar** [comment]
Done!

**Comment by jmercouris** [comment]
7th rebase is the charm :-D?

**Comment by aartaka** [comment]
@Ambrevar, merge then?

**Comment by Ambrevar** [comment]
Please do!

**Comment by aadcg** [comment]
Not the most informed opinion but here it goes. Leave it in `document` for now; in the future we might have several `document-` (such as `document-html`?) and it will sense to move it.

**Comment by Ambrevar** [comment]
I forgot what we said.  Should I perform the rebase then?  @aartaka ?

**Comment by aartaka** [comment]
> I forgot what we said. Should I perform the rebase then? @aartaka ?

Yes, I'd be much grateful!

**Comment by Ambrevar** [comment]
Merged with d185f645ea3f2aaaa2fbb4fe4f7f7d37431c0610.
@aartaka Please test `master` to make sure it works as expected for you.

**Comment by jmercouris** [comment]
You did it! Woohoo! :-D

**Comment by aartaka** [comment]
@Ambrevar, something's wrong...
``` lisp
(asdf:load-system :nyxt/gtk)
;; No values
(typep (make-instance 'nyxt/user-script-mode:user-script) 'nyxt/user-script-mode:renderer-user-script)
;; T
(typep (make-instance 'nyxt/user-script-mode:user-script) 'nyxt:gtk-user-script)
;; NIL
```

Seems like the inheritance's gotten broken somewhere along the way. That's why the scripts don't work for me.

**Comment by Ambrevar** [comment]
Oops!  This issue is due to  a typo when we introduced package locks.

Fixed with 0b0954a3e91dde280d3b47941c6437960a75a9f2.

**Pull request closed without merging**
