### PR TITLE
Build the gobject/gtk renderer by default.

### PR DESCRIPTION
**Pull request by Ambrevar**
I tested in a Guix container and it worked.

Don't merge yet:
- [ ] Need to test on Nix.
- [x] And on Ubuntu.

### CODE REVIEW

**Comment by Ambrevar** [comment]
The .deb got produced!

I haven't tested it though.  Anyone with Ubuntu 20.04 around to test it?

**Comment by jmercouris** [comment]
Yay! If you like I can spin up a VM.

**Comment by jmercouris** [comment]
Download the Ubuntu Desktop Image now... will take some time at 3gb.

**Comment by jmercouris** [comment]
I've spun up the VM, where can I download the deb file?

**Comment by Ambrevar** [comment]
If you go to the pull request "checks" here

https://github.com/atlas-engineer/nyxt/pull/1353/checks

you'll find an "artifacts (1)" drop down menu, with the .deb to download.

**Comment by jmercouris** [comment]
I see, thank you!

**Comment by jmercouris** [comment]
Not sure if this is intended or not:

```
jmercouris@jmercouris-VirtualBox:~$ nyxt 
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006B00D3}>:
  Error opening shared object "libfixposix.so":
  libfixposix.so: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006B00D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libfixposix.so" "libfixposix.so: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT T)
9: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
11: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by jmercouris** [comment]
Works on Ubuntu, I manually installed the dependencies:

```
        sudo apt-get install -y libfixposix3 libfixposix-dev libwebkit2gtk-4.0-dev glib-networking gsettings-desktop-schemas xclip notify-osd enchant-2

```

I don't know if I was supposed to install the `.deb` in a different way. I just double clicked it and followed through some sort of wizard. Maybe you have to `dpkg` install with some flags?

**Comment by jmercouris** [comment]
In other words, Yay! the gobject/gtk renderer works!

**Comment by jmercouris** [comment]
To verify I tested printing buffers of course :-)

**Comment by Ambrevar** [comment]
Can you uninstall the deps, uninstall nyxt, then reinstall the .deb
with APT (e.g. `apt install *.deb` I think) , not by double-clicking nor
with `dpkg`.

**Comment by Ambrevar** [comment]
And thank you a lot for testing!

**Comment by jmercouris** [comment]
OK! I will try the method proposed tomorrow.

**Comment by jmercouris** [comment]
Same exact issue with the proposed method. Libfixposix, and all other dependencies are somehow not installed.

**Comment by jmercouris** [comment]
I'll recreate the VM and start over just in case there is some state in the system.

**Comment by Ambrevar** [comment]
No need, you'd waste your time.

Can you post the output of the `apt` command you ran?

**Comment by Ambrevar** [comment]
I just extracted the archive to look at thee control.tar.gz file, it
shows this:

--8<---------------cut here---------------start------------->8---
Depends: glib-networking, gsettings-desktop-schemas, xclip, enchant, notify-osd, libc6, zlib1g, libwebkit2gtk-4.0-37, libgtk-3-0, libgtk-3-0, libpangocairo-1.0-0, libpango-1.0-0, libcairo2, libgdk-pixbuf2.0-0, libglib2.0-0, libglib2.0-0, libglib2.0-0, libglib2.0-0, libgirepository-1.0-1, libglib2.0-0, libfixposix3, libssl1.1
--8<---------------cut here---------------end--------------->8---

Seems to be correct.

**Comment by jmercouris** [comment]
So, the problem seems to be this: wrong version of libfixposix. I think we need `libfixposix-devel`.

**Comment by jmercouris** [comment]
```
jmercouris@jmercouris-VirtualBox:~$ cd ~/Downloads/
jmercouris@jmercouris-VirtualBox:~/Downloads$ ls
nyxt-ubuntu.zip
jmercouris@jmercouris-VirtualBox:~/Downloads$ unzip nyxt-ubuntu.zip 
Archive:  nyxt-ubuntu.zip
  inflating: nyxt_2_amd64.deb        
jmercouris@jmercouris-VirtualBox:~/Downloads$ ls
nyxt_2_amd64.deb  nyxt-ubuntu.zip
jmercouris@jmercouris-VirtualBox:~/Downloads$ sudo apt install ./nyxt_2_amd64.deb 
[sudo] password for jmercouris: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'nyxt' instead of './nyxt_2_amd64.deb'
The following packages were automatically installed and are no longer required:
  chromium-codecs-ffmpeg-extra gstreamer1.0-vaapi
  libgstreamer-plugins-bad1.0-0 libva-wayland2
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  enchant libenchant1c2a libfixposix3 notify-osd notify-osd-icons xclip
Suggested packages:
  libenchant-voikko
The following NEW packages will be installed:
  enchant libenchant1c2a libfixposix3 notify-osd notify-osd-icons nyxt xclip
0 upgraded, 7 newly installed, 0 to remove and 135 not upgraded.
Need to get 283 kB/31,0 MB of archives.
After this operation, 141 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 libenchant1c2a amd64 1.6.0-11.3build1 [64,7 kB]
Get:2 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 enchant amd64 1.6.0-11.3build1 [12,4 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 libfixposix3 amd64 1:0.4.3-1 [15,1 kB]
Get:4 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 notify-osd amd64 0.9.35+20.04.20191129-0ubuntu1 [107 kB]
Get:5 /home/jmercouris/Downloads/nyxt_2_amd64.deb nyxt amd64 2 [30,7 MB]
Get:6 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 notify-osd-icons all 0.8+15.10.20151016.2-0ubuntu1 [65,6 kB]
Get:7 http://de.archive.ubuntu.com/ubuntu focal/universe amd64 xclip amd64 0.13-1 [18,4 kB]
Fetched 283 kB in 0s (748 kB/s)
Selecting previously unselected package libenchant1c2a:amd64.
(Reading database ... 183338 files and directories currently installed.)
Preparing to unpack .../0-libenchant1c2a_1.6.0-11.3build1_amd64.deb ...
Unpacking libenchant1c2a:amd64 (1.6.0-11.3build1) ...
Selecting previously unselected package enchant.
Preparing to unpack .../1-enchant_1.6.0-11.3build1_amd64.deb ...
Unpacking enchant (1.6.0-11.3build1) ...
Selecting previously unselected package libfixposix3:amd64.
Preparing to unpack .../2-libfixposix3_1%3a0.4.3-1_amd64.deb ...
Unpacking libfixposix3:amd64 (1:0.4.3-1) ...
Selecting previously unselected package notify-osd.
Preparing to unpack .../3-notify-osd_0.9.35+20.04.20191129-0ubuntu1_amd64.deb .
..
Unpacking notify-osd (0.9.35+20.04.20191129-0ubuntu1) ...
Selecting previously unselected package notify-osd-icons.
Preparing to unpack .../4-notify-osd-icons_0.8+15.10.20151016.2-0ubuntu1_all.de
b ...
Unpacking notify-osd-icons (0.8+15.10.20151016.2-0ubuntu1) ...
Selecting previously unselected package xclip.
Preparing to unpack .../5-xclip_0.13-1_amd64.deb ...
Unpacking xclip (0.13-1) ...
Selecting previously unselected package nyxt.
Preparing to unpack .../6-nyxt_2_amd64.deb ...
Unpacking nyxt (2) ...
Setting up notify-osd (0.9.35+20.04.20191129-0ubuntu1) ...
Setting up libenchant1c2a:amd64 (1.6.0-11.3build1) ...
Setting up enchant (1.6.0-11.3build1) ...
Setting up xclip (0.13-1) ...
Setting up notify-osd-icons (0.8+15.10.20151016.2-0ubuntu1) ...
Setting up libfixposix3:amd64 (1:0.4.3-1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
Setting up nyxt (2) ...
jmercouris@jmercouris-VirtualBox:~/Downloads$ nyxt 
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006B00D3}>:
  Error opening shared object "libfixposix.so":
  libfixposix.so: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006B00D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080283}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libfixposix.so" "libfixposix.so: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT T)
9: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
11: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment]
OK, I know what's going on: libfixposix.so.3 is in the libfixposix3
package (notice the trailing ".3"), but libfixposix.so is in libfixposix-dev.

https://packages.ubuntu.com/hirsute/amd64/libfixposix3/filelist
https://packages.ubuntu.com/hirsute/amd64/libfixposix-dev/filelist

**Comment by Ambrevar** [comment]
I'm pushing a fix, a new artifact will be available soon.

**Comment by jmercouris** [comment]
OK, thank you!

**Comment by Ambrevar** [comment]
Artefact should be there!

**Comment by jmercouris** [comment]
A little bit further:

```
jmercouris@jmercouris-VirtualBox:~/Downloads$ nyxt 
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                    {10006B00D3}>:
  Error opening shared object "libwebkit2gtk-4.0.so":
  libwebkit2gtk-4.0.so: cannot open shared object file: No such file or directory.

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10006B00D3}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080793}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080793}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." {1001080793}>)
3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
  ~A." "libwebkit2gtk-4.0.so" "libwebkit2gtk-4.0.so: cannot open shared object file: No such file or directory")
4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libwebkit2gtk-4.0.so" :NAMESTRING "libwebkit2gtk-4.0.so" :HANDLE NIL :DONT-SAVE NIL))
5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libwebkit2gtk-4.0.so" :NAMESTRING "libwebkit2gtk-4.0.so" :HANDLE NIL :DONT-SAVE NIL))
6: (SB-SYS:REOPEN-SHARED-OBJECTS)
7: (SB-IMPL::FOREIGN-REINIT)
8: (SB-IMPL::REINIT T)
9: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
11: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by jmercouris** [comment]
Perhaps the wrong version of libwebkitgtk?

**Comment by Ambrevar** [comment]
No, all webkit2gtk versions are supported.

It's the same issue as with libfixposix: recent Ubuntus have separated
the .so files in a weird way, now you need to depend on the -dev version
of the package as well.

I've just pushed a commit, artifact should be ready in 5 minutes.

**Comment by jmercouris** [comment]
When I meant the wrong version, I meant the wrong `-dev` variant :-)

**Comment by jmercouris** [comment]
As soon as this is done I shall test again!

**Comment by jmercouris** [comment]
Yay! It works :-)

**Comment by Ambrevar** [comment]
You should not have merged yet, Nix is not ready!

In particular, the cl-gobject-introspection dep is missing.

**Comment by jmercouris** [comment]
This doesn't break NixOS. It will still build. I'm working on the dependency... :'-(

**Comment by jmercouris** [comment]
I am actively procrastinating it as we speak!

**Comment by Ambrevar** [comment]
You mean it will still build without the dependency?

**Comment by jmercouris** [comment]
That's correct.

**Comment by jmercouris** [comment]
I can try it again though just to be sure...

**Comment by jmercouris** [comment]
OK, I've verified it to be still true.

**Comment by Ambrevar** [comment]
How?

**Comment by jmercouris** [comment]
I don't understand the spell books myself, I couldn't explain it if I tried!

**Comment by Ambrevar** [comment]
When we tried together yesterday, it failed for you on Nix.
What changed?

Considering that cl-gobject-introspection is not in Nix, it should
failed to build.

How are you building it?
Are you sure it's running the gobject-renderer? (Start with --verbose to
see the log:debug message.)

**Comment by Ambrevar** [comment]
Wait, isn't cl-gobject found by ASDF locally?

What does

(asdf:locate-system :cl-gobject-introspection)

return you?

**Comment by jmercouris** [comment]
It is not running the gobject renderer, and that is why it is working.

**Comment by Ambrevar** [comment]
OK, can you revert the merge then, and reopen the pull request?

**Comment by jmercouris** [comment]
Perhaps you misunderstand what I am saying. Nyxt builds just fine on NixOS. It just runs the GTK renderer instead of the GObject/GTK renderer.

**Comment by Ambrevar** [comment]
Hmm, OK, but then we the issue is only partially fixed.  We need to
update the NixOS package still.

**Comment by jmercouris** [comment]
I'm working on getting the cl-gobject-introspection library in NixOS, then I will update Nyxt on NixOS.

**Comment by jmercouris** [comment]
s/NixOS/NixPkgs

**Comment by Ambrevar** [comment]
Thanks.

Another reason why this was not meant to be merged: commit https://github.com/atlas-engineer/nyxt/pull/1353/commits/bf596df69d4db287e3993c0bbca6fc43a9dfbc7b was meant only to test the .deb package and was not supposed to end on master.

I suggest to update out patch review workflow with a simple step: always ask before merging.  Thoughts?

**Comment by jmercouris** [comment]
OK! I will ask when non-obvious!

**Pull request merged**
