### PR TITLE
status-buffer: vi mode indicator

### PR DESCRIPTION
**Pull request by edgar-vincent**
This adds a vi mode indicator in the status buffer when `vi-normal-mode` or `vi-insert-mode` are enabled. There is some flickering in the status buffer when changing modes - I'm not sure how to fix that.
Also, my branch's history is messed up, but I assume that you'll squash the commits :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thank you for your contribution!
If I'm not mistaken, this is your first contribution, so welcome to the world of Nyxt hackers :)

You are addressing an important point: per-mode status buffer customization.
Unfortunately we can't hard-code the mode customization.  Instead, we should derive a framework that's extensible and where the core functions are mode-agnostic.

If you look at `format-status-modes`, you'll see that it calls `glyph` which is a method that can be specialized for each mode.

This is a bit limited and I believe we can do better.  In particular:
- Change the appearance of the HTML span of the mode button in the status bar.
- A mode should be able to tell whether it should appear first.  How do we resolve conflicts then?
- Should a mode be able to tweak the appearance of the whole mode list?  E.g. change the background color?  If we want to keep it simple, I'd say no, the above point about mode reordering is enough.

This generalization could integrate the glyph feature.

Thoughts?

**Comment by edgar-vincent** [comment]
> Thank you for your contribution!
> If I'm not mistaken, this is your first contribution, so welcome to the world of Nyxt hackers :)

Thank you!

> You are addressing an important point: per-mode status buffer customization.
> Unfortunately we can't hard-code the mode customization. Instead, we should derive a framework that's extensible and where the core functions are mode-agnostic.

I was wondering about that, and you're absolutely right. How to do you think this should be done?
This is somewhat unrelated, but what about styling? The styling definitions seem to be scattered in different places (moreover, shouldn't the blue "accent" colour be inherited from somewhere rather than re-specified every time it is used?).

> If you look at `format-status-modes`, you'll see that it calls `glyph` which is a method that can be specialized for each mode.

I'd missed that! Thanks.

> This is a bit limited and I believe we can do better. In particular:
> 
>     * Change the appearance of the HTML span of the mode button in the status bar.

I agree. It is probably a good thing, especially for "visual" people (which I'm not BTW ^^). For example, it should be very obvious that one is using visual-mode or, indeed, vi-insert-mode. Quite a few people have been confused with the latter, even though the mode is listed in the status buffer.
 
>     * A mode should be able to tell whether it should appear first.  How do we resolve conflicts then?

Specifically about the vi-mode indicator, I think it should probably in the left, like in powerline. Perhaps there could be several "mode" areas in the status buffer? Tridactyl has it on the right though, but I think that vim users would expect it to be on the left.
Not sure about conflicts.

>     * Should a mode be able to tweak the appearance of the whole mode list?  E.g. change the background color?  If we want to keep it simple, I'd say no, the above point about mode reordering is enough.

I can't think of why a mode would need to change the appearance of the whole list, but it might be useful.

**Comment by Ambrevar** [comment]
> I was wondering about that, and you're absolutely right. How to do you
> think this should be done?

I'm not completely sure yet, but I think a generalized version of
format-status-modes seems closer to the right direction.

> This is somewhat unrelated, but what about styling? The styling
> definitions seem to be scattered in different places

"Functional" theming has been on my roadmap for a while.
We've already started laying down the foundations: most styling elements
are found in a slot that's consistently called `style`.

It should be quite easy to go from there.

> (moreover, shouldn't the blue "accent" colour be inherited from
> somewhere rather than re-specified every time it is used?).

Which "blue accent colour" do you mean?

> Specifically about the vi-mode indicator, I think it should probably
> in the left, like in powerline.

This is a separate issue, and not really an issue.
With the WINDOW `status-formatter` slot you can fully customize the
appearance of the status area, including the position of the different parts.

> Perhaps there could be several "mode" areas in the status buffer?

By default I'd rather have just one mode area, but we can discuss it of
course.

And obviously, styling and custom status bars would make for great
extensions! :)

**Comment by edgar-vincent** [comment]
> I'm not completely sure yet, but I think a generalized version of format-status-modes seems closer to the right direction.

> "Functional" theming has been on my roadmap for a while. We've already started laying down the foundations: most styling elements are found in a slot that's consistently called `style`. It should be quite easy to go from there.

Okay - I trust the expert :)


> Which "blue accent colour" do you mean?

I mean `#37a8e4` as in https://github.com/atlas-engineer/nyxt/blob/d50f819372f8c781147ad52fe4d31e020ae50168/source/prompt-buffer.lisp#L111 and https://github.com/atlas-engineer/nyxt/blob/17f7b7f2d903082b5b0308b07cdad8311a81dadc/source/web-mode.lisp#L47 :)


> This is a separate issue, and not really an issue. With the WINDOW `status-formatter` slot you can fully customize the appearance of the status area, including the position of the different parts.

I mean I think it should be there by default :) But I suppose if we make it more obvious that `vi-mode` is enabled by other means, I imagine it would be fine :)

**Comment by Ambrevar** [comment]
Related issue: https://github.com/atlas-engineer/nyxt/issues/1024

**Comment by Ambrevar** [comment]
OK to merge this as an intermediary solution until we come up with something more general.
Let's just unexport the `format-*` function.

**Comment by Ambrevar** [comment]
Rebased and merged with 08b36b4ae42db1209798ea9c160e53ee11dc3f9d.
I've fixed a few things to accommodate with the recent changes in the status bar CSS.

Thanks a lot for this very demanded change, sorry for the delay and thanks for your patience!

**Comment by jmercouris** [comment]
Pierre, this is broken with no init, AKA people who do not use vi mode... I will fix it.

**Comment by Ambrevar** [comment]
Oops, I was thinking I should test this case, then I forgot... :(

**Comment by jmercouris** [comment]
It's OK, it happens to the best of us :-)

**Pull request closed without merging**
