### PR TITLE
Add support for GTK clipboard(2)

### PR DESCRIPTION
**Pull request by shamazmazum**
The original patch which uses `cl-cffi-gtk`

### CODE REVIEW

**Comment by shamazmazum** [comment]
Does `copy-url` work with this variant?

**Comment by Ambrevar** [comment]
Works for me!

@jmercouris can you try it out?

**Comment by jmercouris** [comment]
I C A N T R Y I T

**Comment by jmercouris** [comment]
I T W O R K S

should we not have a `ffi-xyz-` method though?

**Comment by jmercouris** [comment]
or maybe not, I don't know.

**Comment by jmercouris** [comment]
This is best.

**Comment by shamazmazum** [comment]
Oh thanks!

**Comment by jmercouris** [comment]
Thank you!

**Pull request merged**
