### PR TITLE
Support of macOS via MacPorts

### PR DESCRIPTION
**Pull request by catap**
# Description

Here a series of patches which is used at MacPorts to be able to build nyxt 3.5.0.

Fixes # (issue)

# Discussion

Everything seems quite trivial.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
    - Changelog update should be a separate commit.
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by catap** [comment]
Yes, it really works

Screenshot 2023-08-12 at 01 59 06

**Comment by jmercouris** [comment]
Well, basically we couldn't reliably control the distribution of WebKitGTK+, it was always behind. Furthermore, WebKitGTK+ on my mac at the time, would crash a lot.

**Comment by catap** [comment]
FYI: I'm working to bring Nyxt to macOS via MacPorts. Frankly speaking it is almost ready. I do have a few minor polish and soon I'll open a PR to MacPorts.

=> you may simple advertise that users may use MacPorts to easy install it ;)

**Comment by jmercouris** [comment]
MacPorts is able to make a standalone bundle, which I was not able to do successfully. @catap if you are able to do so, I will give you 1000 brownie points, at minimum.

**Comment by catap** [comment]
> MacPorts is able to make a standalone bundle, which I was not able to do successfully. @catap if you are able to do so, I will give you 1000 brownie points, at minimum.

This depends on how you define bundle I guess. If as an application which user may click => I've already did it. But it should be installed via `port install nyxt` and can't be transfered to another machine.

> For us to safely advertise Nyxt on MacPorts, someone would have to bump WebKit to 2.40.5 (as of today) and assume the maintainer responsibility.

Becuase `webkit` is legacy port. I assume that you need to check `webkit2` which is 2.28.6 or not that old.

Anyway, I agree that gtk need to be updated.

**Comment by catap** [comment]
> Thanks for letting me know. Indeed, I should have checked [this package instead](https://ports.macports.org/port/webkit2-gtk/). This release is from April 2020. If you try to update the package on MacPorts please let us know. Thanks.

Deal!

**Comment by catap** [comment]
Nyxt with patches from this PR were included into MacPorts: https://ports.macports.org/port/nyxt/details/

Update of webkit2 in progress.

**Comment by jmercouris** [comment]
Thank you for the update. Looking over this PR (after I test it), I don't see why we couldn't merge it into master as well!

**Comment by jmercouris** [comment]
Tested and merged! Thank you!

**Pull request closed without merging**
