### PR TITLE
vcs-mode.lisp: enable path specification from the minibuffer.

### PR DESCRIPTION
**Pull request by aadcg**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Does this work to create parent directories?
E.g. say I have an existing `~/projects` folder and I want to clone Nyxt to "~/projects/lisp/nyxt" will it create the `lisp` folder?

**Comment by aadcg** [comment]
> Does this work to create parent directories?

Yes.  Are you just wondering, or did you try and smth didn't work for you?

**Comment by Ambrevar** [comment]
I was just wondering! :)

**Comment by Ambrevar** [comment]
Thanks!

**Pull request merged**
