### PR TITLE
Fix configure slot

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Fixes #1425.

**Comment by Ambrevar** [comment]
These `define-user-class` are annoying to maintain.

Instead, I think we should automatically define the user class when the class is exported.

Our `define-class` is currently a copy-paste of `defclass*`.

**Comment by Ambrevar** [comment]
But this change belongs to #1102 I think.  For after 2.0.

**Comment by jmercouris** [comment]
I still would prefer a class option rather than an implication that an exported class is to be configured

**Comment by jmercouris** [comment]
Tested, thank you!

**Pull request merged**
