### PR TITLE
mode/repl: Evaluate in the background to avoid blocking the REPL.

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

A simple fix: evaluate the REPL cells in the background, so that `(sleep 5)` won't freeze Nyxt for 5 seconds.

# Discussion

It would be neat if the result would automatically display upon termination.  For now the user must either reload the buffer and evaluate another cell.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by Ambrevar** [comment]
Cc @aartaka .

**Review by aartaka — APPROVED** [review]
I've tried it, seems to work wonderfully! The only suggestion I have is: instead of simply reporting `Calculating...`, you can say `Calculating, reload to see the result.` or some other explanation of how to get sweet and precious evaluation results!

Another cool thing could be to automagically reload once the evaluation is done, but we need to cache user inputs and cursor position for that, so I'd say it's too eavly for that.

**Comment by Ambrevar** [comment]
But can't we just write the result on finish using JS?  it's easy since we have the ID of the cell, nah?

**Comment by Ambrevar** [comment]
And no need to reload the page.  Also see https://github.com/atlas-engineer/nyxt/issues/2374, I believe there is no need to reload the page at all.

**Comment by aadcg** [comment]
Really exciting feature. Thank you @Ambrevar.

If you can figure out the JS thing, even better!

**Comment by Ambrevar** [comment]
Done with 3f3879b10bc81660a9b3e08a7d3088eb382ee547.

The flaky design can be further improved, but let's address this in https://github.com/atlas-engineer/nyxt/issues/2374.

OK to merge?

**Comment by aadcg** [comment]
Ok to merge.

**Pull request merged**
