### PR TITLE
Fix source dir

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Addresses the wrong source dir resolution mentioned in #2953.

This does _NOT_ fix the embedded editor crash.

# Discussion

- Maybe rebase onto #2925 ?  This NASDF change needs to be propagated to the other systems.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [x] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@bubbleguuum This should fix your issue, but note that something else is going on, and somehow your Nyxt's ASDF is not finding the Nyxt system.  We also need to fix that part.

**Comment by aadcg** [comment]
> Maybe rebase onto Update NASDF to 0.1.4. #2925 ? This NASDF change needs to be propagated to the other systems.

Sounds good to me.

**Comment by Ambrevar** [comment]
> but note that something else is going on, and somehow your Nyxt's ASDF is not finding the Nyxt system. We also need to fix that part.

Answer: This is because of this:

```lisp
(defmethod files:resolve ((profile nyxt-profile) (directory nyxt-source-directory))
  (let ((asd-path (ignore-errors (asdf:system-source-directory :nyxt))))
    (if (uiop:directory-exists-p asd-path)
        asd-path
        ;; Maybe not be found when the ASDF registry was cleared (for instance,
        ;; Nyxt was installed via the Makefile).
        nasdf:*dest-source-final-dir*)))
```

On first resolution, the ASD file may not be found (in particular if the ASDF registry was reset -- which is what the Makefile does).  So we must get the source location from what was last recorded during the build.  Which is what this patch does.

**Comment by aartaka** [comment]
> This does _NOT_ fix the embedded editor crash.

Wait, does it crash? 0_o

> # Discussion
> * Maybe rebase onto [Update NASDF to 0.1.4. #2925](https://github.com/atlas-engineer/nyxt/pull/2925) ?  This NASDF change needs to be propagated to the other systems.

Not yet, it's too unstable.

**Comment by Ambrevar** [comment]
So how shall we proceed?

Maybe we could find a way to get the `output-files` value from the Nyxt image... Any idea?

**Comment by aadcg** [comment]
> > This does _NOT_ fix the embedded editor crash.
> 
> Wait, does it crash? 0_o

@aadcg please read the whole thread on #2953 for all the details.

Long story short: the crash is due to DATADIR, because editor mode was trying to find a file in a place where it doesn't exist. We could surround `chdir` with a `ignore-errors` perhaps. 


> > * Maybe rebase onto [Update NASDF to 0.1.4. #2925](https://github.com/atlas-engineer/nyxt/pull/2925) ?  This NASDF change needs to be propagated to the other systems.
> 
> Not yet, it's too unstable.

Then let's move ahead and merge this PR.

@Ambrevar feel free to assign me some of the stages relative to the tedious NASDF update.

**Comment by Ambrevar** [comment]
This is not ready to be merged.  I'm working on it.

**Comment by Ambrevar** [comment]
@bubbleguuum Can you try this again?

**Comment by bubbleguuum** [comment]
@Ambrevar 

Still problematic as `make install` now uses `DATADIR=$PREFIX/share` instead of (previously) `DATADIR=$PREFIX/share/nyxt`:
In my case `$PREFIX` is `/usr`:

```
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/applications/nyxt.desktop"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/icons/hicolor/128x128/apps/nyxt.png"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/icons/hicolor/16x16/apps/nyxt.png"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/icons/hicolor/256x256/apps/nyxt.png"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/icons/hicolor/32x32/apps/nyxt.png"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/icons/hicolor/512x512/apps/nyxt.png"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/bin/nyxt"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/source/about.lisp"
[  127s] ; installed #P"/home/abuild/rpmbuild/BUILDROOT/nyxt-3prerelease6+git20230511.2cc6b38-0.x86_64/usr/share/source/auto-rules.lisp"
....
```


That's with 2 make invocations, the first one for build and the second for install, as there are these 2 stages in a RPM spec file:

```
make all PREFIX=/usr
...
make install PREFIX=/usr 
```

**Comment by bubbleguuum** [comment]
Apparently `make install` copy all data files in `/usr/share`. Maybe that's intended for working with nixos or some self containing package such as Flatpak. But on a regular package for a distro we want this:

/usr/share/application/*
/usr/share/icons/*

And everything else (including source) under

/usr/share/nyxt

Currently if I pass `DATADIR=/usr/share/nyxt` to make install, everything above is installed in `/usr/share/nyxt`, including the applications and icons directories....

Previously, everything was installed with the folder hierarchy as described above.

**Comment by Ambrevar** [comment]
Oops!  I had tested the wrong NASDF...  Should be working now.

Note that Nyxt does not expect you to set DATADIR, leave it to the default.  You only need to set `PREFIX` like you did.

**Comment by bubbleguuum** [comment]
install path for data files is fixed (with `DATADIR` not passed to make) but it crashes very early on startup, supposedly attempting to determine the source path:

```
~/osc/home:bobbie424242/nyxt-git> nyxt
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD tid=24828 "main thread" RUNNING
                                  {1005748003}>:
  The value
    NIL
  is not of type
    PATHNAME

Backtrace for: #<SB-THREAD:THREAD tid=24828 "main thread" RUNNING {1005748003}>
0: (NFILES:EXPAND #<NYXT:NYXT-SOURCE-DIRECTORY {1002A50873}>)
1: (NYXT:START :URLS NIL)
2: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
3: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1005CEA3FB}>)
4: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
5: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
6: (SB-IMPL::%START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment]
Pfeeew, there are a lot of corner cases!
I've done some extra testing, this time everything should pass.

@bubbleguuum Can you give it another look?

**Comment by bubbleguuum** [comment]
It works fine. Thanks !

**Comment by Ambrevar** [comment]
Hooray!!!  Thank you so much for your patience and your report.  This was a tough one!

**Comment by Ambrevar** [comment]
Merged with 2992b455b05823199f56c8a9bb80dd9a351234db.

**Pull request closed without merging**
