### PR TITLE
gtk.lisp: update prompt-buffer on mouse button events

### PR DESCRIPTION
**Pull request by tiberious726**
In the X11 tradition, mouse-2 pastes from the XA_PRIMARY clipboard, so
the prompt-buffer should update accordingly.

The prompt buffer will update regardless of which mouse button is
pressed, as we don't have a good way to decode if the user has
remapped their mouse buttons here, or if they have assigned custom
actions to other buttons

### CODE REVIEW

**Comment by tiberious726** [comment]
I wasn't sure what the "watcher" referred to by this comment was:
;; Rebind prompt-buffer to ensure the watcher does not mix up the
;; different prompt-buffers.
So I left the logic in place, but I'm not sure the rebinding in the other thread is still necessary.

**Comment by jmercouris** [comment]
I see, thank you for this patch, I will review this and get back to you. There is actually a lot I would like to change about the way input is handled for 3.0.0.

**Comment by Ambrevar** [comment]
Looks good to me.
@jmercouris Anything blocking this?
The whole architecture of button events could be improved, but this patch seems OK to merge in the mean time.

**Comment by jmercouris** [comment]
OK, feel free to merge it then.

**Pull request merged**
