### PR TITLE
prompt-buffer: Improve input area focus UI.

### LINKED ISSUE #2951: Show me where my words go -- input field border
**Purpose**
A subtle highlight to show new users and remind veteran users where key inputs will go as prompt buffer opens up.

**What is your proposed change?**

FOR cases WITHOUT suggested text in the input area: **I propose a border of some kind, around that input area** (probably thin, & in our `accent` color).

Would apply to:
   - the `execute command` prompt buffer input space
   - the `describe-any` prompt buffer input space
   - the `describe-mode` prompt buffer input space
   - the `describe-slot` prompt buffer input space
   - describe: `class`, `command`, `package`, `function`, `variable`

NOT for things like:
- `Open URL` or `Open URL in new buffer` which already have highlighted to bring user attention to the right place.

**Rationale**

1. Anticipate the needs of users (opening `C-space` &rarr; next thing is inputing &rarr; key questions _where do i type?_ &rarr; key answer: right freaking there in the blue accented input area.)
2. We want to connect our users with the keyboard and our prompt buffer at all times. Reminding them exactly where inputs will land in that UI will give a sense of security.
3. I see it in other apps and browsers and it seems sensible.
4. a clear display here gives users good feedback that `execute-command` / `describe-any`... is doing what they intend.

**Constraints**
**We do NOT want the colored border on at all times, ideally the colored border disappears as the first input character displays.** 
We want the colored border to be subtle, not so thicc that it distracts users from their task. 
We want the colored border to only encompass the input area, nothing else.

**Additional context/User story**

**Screenshots/Mock ups**
Group 192

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team.
- [x] One or more developers have signed off on this change. @aartaka was into it
- [x] One or more user researchers have signed off on this change.

Cool? Yes no? Thoughts?

### PR DESCRIPTION
**Pull request by aadcg**
Reverts changes introduced by 5d3877e52f8faccd8144227db4997e06f58b9ba2, which were a regression.

# Description

Fixes #2951

# Discussion

@lansingthomas, interested in your feedback. Please find a demo below:

https://github.com/atlas-engineer/nyxt/assets/45483512/4d3187ce-9bcf-4037-af25-54869f901625

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [x] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aartaka** [comment]
> Reverts changes introduced by [5d3877e](https://github.com/atlas-engineer/nyxt/commit/5d3877e52f8faccd8144227db4997e06f58b9ba2), which were a regression.

Oh come on, this border, even if slightly unaesthetical, saved me more than once from confusing prompt buffer and main buffer focused state.

**Comment by jmercouris** [comment]
This box shadow version is better though I'd like to see the box shadow on the left/right sides eliminated and only have it on the top/bottom. Ideally our box shadow would trace the shape of the left/right sides, but until then better to just have it on the top/bottom.

**Comment by jmercouris** [comment]
I'll play with it, thanks

**Comment by aartaka** [comment]
> This box shadow version is better though I'd like to see the box shadow on the left/right sides eliminated and only have it on the top/bottom. Ideally our box shadow would trace the shape of the left/right sides, but until then better to just have it on the top/bottom.

Which is, like, the current one?

**Comment by jmercouris** [comment]
No, it is inset rather than outlined.

**Comment by lansingthomas** [comment]
I appreciate the demo and the screenshots.

Is this helpful for getting the shape sorted out?
`<svg xmlns="http://www.w3.org/2000/svg" width="1246" height="33" viewBox="0 0 1246 33" fill="none">
<path d="M12.5 16.5L2 1H1243.5L1232.5 16L1243.5 32H2L12.5 16.5Z" stroke="#37A8E4" stroke-width="2"/>
</svg>`

**Comment by jmercouris** [comment]
Unfortunately @lansingthomas that SVG does not help.

**Comment by jmercouris** [comment]
The problem is that we would need to have yet another layer to clip against below the input layer, so we'd have to introduce yet another div. I think due to the technical difficulties of doing so, we should just proceed with the top and bottom highlighted. It works for now.

**Pull request merged**
