### PR TITLE
Replace hu.dwim.defclass-star with class* where needed

### PR DESCRIPTION
**Pull request by hendursaga**
Just a little tidy-up!

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks!

It does not pass the CI though, it seems that `class*` is unknown to `history-tree`.

**Comment by hendursaga** [comment]
Sorry about that! This is confusing - it worked for me, but maybe that was because for whatever reason, class* was already loaded in my browser instance as a nickname or something?? I suppose you could discard this if you want.

**Comment by Ambrevar** [comment]
After some digging, I found out that we had some issues with our test CI.  I've fixed them.

**Comment by Ambrevar** [comment]
Merged with 9f4e26f46a3d6873eca0ab3923063e441e7bd9c3.
Thanks!

**Pull request closed without merging**
