### PR TITLE
Fix source location on deploy

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

Previously the installed binary failed to see:
- The new location of the source.
- the new path to nyxt.asd (2nd commit).

This partially addresses the concerns raised in #2360.

# Discussion

Today I discovered an awesome (and completely arcane) feature of Common Lisp (credit goes to https://old.reddit.com/r/Common_Lisp/comments/vc6hix/source_location_for_deployed_binary/icciw5y/): **logical pathnames**.

Everyone keeps saying they are arcane and only useful for compatibility with old systems.  Well, seems that we found a pretty good use case here!

I know one Common Lisp application that uses it precisely for source relocation: SBCL.  So I borrowed some code from it! :)

# Sacrifice

Logical pathnames only accept case-insensitive alpha-numeric characters as well as `-`.  
This is not a big deal since it's what we are using now, but if some day we want to add a file `foo+bar.lisp`, it won't work.  

Something to keep in mind.

# To do:

The major drawback of this approach is that SLIME / SLY compilation warnings under SBCL will use the logical pathname as reference, and thus Emacs' `next-error` fails to find the location.

I can think of 2 fixes:

- [x] Add a conditional in the nyxt.asd to only use logical pathnames when packaging.  Easy.
- [x] Ask SBCL if they can report warnings using the physical pathname instead of the logical one.

    Actually the problem is not with SBCL but with SLY (and maybe SLIME).  See https://github.com/slime/slime/issues/727.

  Mention this in the `nfile` doc.

- [x] (Optional) Ask https://github.com/Shinmera/deploy is they have a solution.

  They don't: https://github.com/Shinmera/deploy/issues/19.

- [x] Do not crash if `set-nyxt-source-location` fails.
- [ ] Ensure that `CL_SOURCE_REGISTRY` is set to the right location as it seems to be a problem for @bubbleguuum.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by aadcg** [comment]
```lisp
(swank-backend:find-source-location #'nyxt:make-buffer)

(:LOCATION (:FILE "/home/aadcg/common-lisp/nyxt/source/buffer.lisp")
[...]
```

```lisp
(sb-introspect:find-definition-source  #'nyxt:make-buffer)
#S(SB-INTROSPECT:DEFINITION-SOURCE
   :PATHNAME #P"NYXT:SOURCE;BUFFER.LISP.NEWEST"
[...]
```

where `pathname`:

```lisp
#<LOGICAL-PATHNAME {100EB7F8A3}>
--------------------
Namestring: "NYXT:SOURCE;BUFFER.LISP.NEWEST"
Physical pathname: : #P"/home/aadcg/common-lisp/nyxt/source/buffer.lisp"
Host: #<SB-KERNEL:LOGICAL-HOST "NYXT"> ((("NYXT:source;**;*.*.*" #P"/home/aadcg/common-lisp/nyxt/source/**/*.*") ("NYXT:libraries;**;*.*.*" #P"/home/aadcg/common-lisp/nyxt/libraries/**/*.*")) other translations)
Directory: (:ABSOLUTE "SOURCE")
Name: "BUFFER"
Type: "LISP"
Version: :NEWEST
Truename: #P"/home/aadcg/common-lisp/nyxt/source/buffer.lisp"
```

Seems to be working fine for me. No objections.

**Comment by Ambrevar** [comment]
Ready to merge.

**Comment by aadcg** [comment]
@Ambrevar I ran `guix shell --container -D -f build-scripts/nyxt.scm -- make all NYXT_SUBMODULES=false` in this checkout and the generated binary runs nyxt 2.2.4. I'm confused. What am I missing?

**Comment by Ambrevar** [comment]
You need to  give me more details ;)

What's the shell output?

How do you start Nyxt?  

What's the output of `nyxt --version`?  Does Nyxt _look_ like 2.2.4 or more like `3-series` (the startup page should make this obvious).


"in this checkout": I suppose you meant "on this branch"?

**Comment by aadcg** [comment]
Sorry, I made a terrible mistake. I started it with `nyxt`, instead of `/path/to/nyxt/binary`!

I'm not able to start Nyxt though.

```
aadcg@guix-xps13 ~/common-lisp/nyxt $ ./nyxt -I
<INFO> [11:00:57] Listening to socket #P"/run/user/1000/nyxt/nyxt.socket".
Nyxt version 3
<WARN> [11:00:57] Warning: Error on GTK thread: Typelib file for namespace 'Gtk', version '3.0' not found
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
```

**Comment by Ambrevar** [comment]
Because if you use `nyxt.scm` the binary is produced against a libraries that are in a temporary profile but not available in your use profile.  To fix it, I use the following wrapper:

```sh
_guix_profile=$HOME/.guix-temp-profiles/nyxt/nyxt
[ -e "$_guix_profile" ] && source "$_guix_profile"/etc/profile
exec ~/common-lisp/nyxt/nyxt "$@"
```

**Comment by bubbleguuum** [comment]
@Ambrevar 

running nyxt with this patch and packaged for openSUSE, I get this error on launch:

```
Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                {1006868003}>:
  Failed to find the TRUENAME of /home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/:

    No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006868003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {1006F37C93}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {1006F37C93}>)
2: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {1006F37C93}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {1006F37C93}>)
4: (SB-KERNEL::%SIGNAL #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {1006F37C93}>)
5: (ERROR SB-INT:SIMPLE-FILE-ERROR :PATHNAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" :MESSAGE "No such file or directory" :FORMAT-CONTROL "Failed to find the ~A of ~A" :FORMAT-ARGUMENTS (:TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/"))
6: (SB-IMPL::FILE-PERROR #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" 2 "Failed to find the ~A of ~A" :TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
7: (SB-IMPL::QUERY-FILE-SYSTEM #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" :TRUENAME T)
8: (TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
9: (NYXT::SET-NYXT-SOURCE-LOCATION #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
10: (NYXT:START :URLS NIL)
11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1006D5F75B}>)
13: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
15: (SB-IMPL::START-LISP)
```

**Comment by Ambrevar** [comment]
Thanks for your report!

Can you run

```lisp
nyxt --no-auto-config --no-config --eval '(asdf:clear-configuration)' --eval '(format t "~&dir: ~a~%location: ~a~%" (asdf:system-source-directory :nyxt) (multiple-value-list (asdf:locate-system :nyxt)))' --eval '(force-output)' --quit
```

and report the output?  Thanks!

**Comment by bubbleguuum** [comment]
Stack trace looks the same:

```
Unhandled SB-INT:SIMPLE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                {1006A00003}>:
  Failed to find the TRUENAME of /home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/:

    No such file or directory

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1006A00003}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {10070C8353}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {10070C8353}>)
2: (INVOKE-DEBUGGER #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {10070C8353}>)
3: (UIOP/IMAGE:HANDLE-FATAL-CONDITION #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {10070C8353}>)
4: (SB-KERNEL::%SIGNAL #<SB-INT:SIMPLE-FILE-ERROR "Failed to find the ~A of ~A" {10070C8353}>)
5: (ERROR SB-INT:SIMPLE-FILE-ERROR :PATHNAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" :MESSAGE "No such file or directory" :FORMAT-CONTROL "Failed to find the ~A of ~A" :FORMAT-ARGUMENTS (:TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/"))
6: (SB-IMPL::FILE-PERROR #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" 2 "Failed to find the ~A of ~A" :TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
7: (SB-IMPL::QUERY-FILE-SYSTEM #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/" :TRUENAME T)
8: (TRUENAME #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
9: (NYXT::SET-NYXT-SOURCE-LOCATION #P"/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db/")
10: (NYXT:START :URLS NIL)
11: ((LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE))
12: (UIOP/IMAGE:CALL-WITH-FATAL-CONDITION-HANDLER #<FUNCTION (LAMBDA NIL :IN UIOP/IMAGE:RESTORE-IMAGE) {1006EF7A9B}>)
13: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
15: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

**Comment by bubbleguuum** [comment]
The original RPM's .spec file that I modified to build git nyxt has this `export CL_SOURCE_REGISTRY` line. I don't why, but maybe it is causing this issue ? :

```
export CL_SOURCE_REGISTRY="(:source-registry (:directory #P\"$PWD/\") (:tree #P\"$PWD/_build/\") :inherit-configuration)"
%make_install PREFIX=/usr NYXT_SUBMODULES=false
```

**Comment by bubbleguuum** [comment]
Interestingly, if nyxt is compiled (by `osc build` in a sandbox) without that `export CL_SOURCE_REGISTRY` line above, compilation fails with:

```
[   27s] + cd nyxt-2.2.4+git20220618.f5f3d4db
[   27s] + make all NYXT_SUBMODULES=false
[   27s] sbcl --dynamic-space-size 3072 --no-userinit --non-interactive --eval '(require "asdf")' --eval '(when (string= "false" "true") (setf asdf:*default-source-registries* (list (quote asdf/source-registry:environment-source-registry))) (asdf:clear-configuration) (asdf:load-asd "/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db//nyxt.asd") (asdf:load-system :nyxt/submodules))' --eval '(asdf:load-asd "/home/abuild/rpmbuild/BUILD/nyxt-2.2.4+git20220618.f5f3d4db//nyxt.asd")' --eval '(when (find-package :ql) (funcall (read-from-string "ql:quickload") :cffi))' --eval '(when (and (find-package :cffi) (uiop:getenv "GUIX_ENVIRONMENT")) (pushnew (pathname (format nil "~a/lib/" (uiop:getenv "GUIX_ENVIRONMENT"))) (symbol-value (read-from-string "cffi:*foreign-library-directories*" )) :test (quote equal)))' --eval '(asdf:load-system :nyxt/gi-gtk-application)' \
[   27s] 	--eval '(asdf:make :nyxt/gi-gtk-application)' \
[   27s] 	--eval '(uiop:quit)' || (printf "\n%s\n%s\n" "Compilation failed, see the above stacktrace." && exit 1)
[   27s] This is SBCL 2.2.4-1.2-suse, an implementation of ANSI Common Lisp.
[   27s] More information about SBCL is available at <http://www.sbcl.org/>.
[   27s] 
[   27s] SBCL is free software, provided as is, with absolutely no warranty.
[   27s] It is mostly in the public domain; some portions are provided under
[   27s] BSD-style licenses.  See the CREDITS and COPYING files in the
[   27s] distribution for more information.
[   27s] Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING
[   27s]                                                               {10018B8003}>:
[   27s]   Component ASDF/USER::ALEXANDRIA not found, required by #<SYSTEM "nyxt">
[   27s] 
[   27s] Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10018B8003}>
[   27s] 0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component ASDF/USER::ALEXANDRIA not found, required by #<SYSTEM "nyxt"> #<unused argument> :QUIT T)
[   27s] 1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* Component ASDF/USER::ALEXANDRIA not found, required by #<SYSTEM "nyxt">)
[   27s] 2: (INVOKE-DEBUGGER Component ASDF/USER::ALEXANDRIA not found, required by #<SYSTEM "nyxt">)
[   27s] 3: (ERROR ASDF/FIND-COMPONENT:MISSING-DEPENDENCY :REQUIRED-BY #<ASDF/SYSTEM:SYSTEM "nyxt"> :REQUIRES ASDF/USER::ALEXANDRIA)
[   27s] 4: (ASDF/FIND-COMPONENT:RESOLVE-DEPENDENCY-NAME #<ASDF/SYSTEM:SYSTEM "nyxt"> ASDF/USER::ALEXANDRIA NIL)
[   27s] 5: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10069E47AB}>)
[   27s] 6: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
[   27s] 7: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
[   27s] 8: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {10069D03A3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> T)
[   27s] 9: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10069E45FB}>)
[   27s] 10: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
[   27s] 11: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
[   27s] 12: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {10069D03A3}> #<ASDF/LISP-ACTION:PREPARE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> T)
[   27s] 13: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10069E444B}>)
[   27s] 14: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
[   27s] 15: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
[   27s] 16: (ASDF/PLAN:TRAVERSE-ACTION #<ASDF/PLAN:SEQUENTIAL-PLAN {10069D03A3}> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "nyxt" "package"> T)
[   27s] 17: (ASDF/PLAN:MAP-DIRECT-DEPENDENCIES #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "nyxt"> #<FUNCTION (LAMBDA (ASDF/PLAN::O ASDF/PLAN::C) :IN ASDF/PLAN:TRAVERSE-ACTION) {10069E429B}>)
[   27s] 18: ((LAMBDA NIL :IN ASDF/PLAN:TRAVERSE-ACTION))
...

```

**Comment by bubbleguuum** [comment]
Urgh, it's now working. It was caused by a compilation mistake.

In RPM spec files, compiling is separate from installing, and I had `PREFIX=/usr` missing in the `%build` rule:

```
%build
export CL_SOURCE_REGISTRY="(:source-registry (:directory #P\"$PWD/\") (:tree #P\"$PWD/_build/\") :inherit-configuration)"
make all PREFIX=/usr NYXT_SUBMODULES=false

%install
export CL_SOURCE_REGISTRY="(:source-registry (:directory #P\"$PWD/\") (:tree #P\"$PWD/_build/\") :inherit-configuration)"
%make_install PREFIX=/usr NYXT_SUBMODULES=false
```

All is good now, sorry for the trouble !

**Comment by Ambrevar** [comment]
So Nyxt starts and `describe-function` works and shows your the source code?  (Only for Nyxt functions.)

**Comment by bubbleguuum** [comment]
Yes it does.

**Comment by bubbleguuum** [comment]
GTK dir also points to the correct dir:

```
<INFO> [13:14:48] GTK extensions directory: #P"/usr/share/nyxt/libraries/web-extensions/"
```

**Comment by Ambrevar** [comment]
You might be doing something fishy with `CL_SOURCE_REGISTRY`.

It's used by `register-submodules` in `nyxt.asd` and it's set to the `_build` folder.  It's only useful if you use Git submodules to fetch the Common Lisp dependencies.

Are you using them in your package recipe?  You've set `NYXT_SUBMODULES` to `false`, but then in https://github.com/atlas-engineer/nyxt/pull/2371#issuecomment-1159666639 it failed to find Alexandria, so I'm assuming that you _need_ to enable submodules.

If you can post the full recipe I can help you fix it :)

**Comment by bubbleguuum** [comment]
Here's the project on OBS (Open Build Service):

https://build.opensuse.org/package/show/home:bobbie424242/nyxt-git

When building that package, OBS fetches git master (including the `_build`) folder.

Here's the full build log output:

https://build.opensuse.org/build/home:bobbie424242/openSUSE_Tumbleweed/x86_64/nyxt-git/_log

**Comment by Ambrevar** [comment]
> When building that package, OBS fetches git master (including the `_build`) folder (using the service described in the `_service` file).

OK, then you should not pass `NYXT_SUBMODULES=false`.  Can you try removing all these occurrences as well as the `export CL_SOURCE_REGISTRY=...` occurrences, see if it works for you?

**Comment by bubbleguuum** [comment]
Confirming that it works.

**Comment by Ambrevar** [comment]
Thanks a lot for your continuous feedback!

**Comment by Ambrevar** [comment]
Merged with 9f490ee667d765e3d86363334f468bc2ab077fde.

**Pull request closed without merging**
