### PR TITLE
Import `compose', `curry' and `rcurry' from Alexandria.

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

These higher-order functions are even more useful if they are more concise than
the (lambda () ...) equivalent.  But the `alex:' prefix does not help, so let's
fix this!

# Discussion

Is there more you wish to import?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by aartaka** [comment]
`alex:mappend` (even though it's not about functional style, it is a frequent occurence), `sera:eqs`, and maybe `sera:filter`?

**Comment by Ambrevar** [comment]
Agreed about `alex:mappend` and `sera:filter`.

For `sera:eqs`, I don't know, if we import this one then we might as well import its friends, `sera:eqls` and `sera:equals`.

**Comment by aartaka** [comment]
> For `sera:eqs`, I don't know, if we import this one then we might as well import its friends, `sera:eqls` and `sera:equals`.

Why not :P

**Comment by Ambrevar** [comment]
Because we already have our own `equals` :p

**Comment by Ambrevar** [comment]
Done with bb8402065e0ce7a91a89ac80aee66f14f04ea6df.  I didn't add a merge commit it's all clean commits!

**Pull request closed without merging**
