### PR TITLE
Progress bar fix

### PR DESCRIPTION
**Pull request by shamazmazum**
These two commits fix the progress bar (you can download any file to see that it's broken).

The first commit fixes a wrong method qualifier introduced recently, but the second one is rather misterious: the progress bar's width was set in px units rather than in percents. I wonder how it worked earlier :) Will be grateful if someone can explain.

### CODE REVIEW

**Comment by Ambrevar** [comment]
@jmercouris may know whay the px units.

Other than that looks good to me, thanks for the fix!

**Comment by shamazmazum** [comment]
Hi! I hope this won't be forgotten :)

**Comment by Ambrevar** [comment]
Cc @jmercouris

**Comment by jmercouris** [comment]
Just tested, also it wasn't PX, it was percentage before too :-)

**Comment by shamazmazum** [comment]
Thanks!

**Pull request merged**
