### PR TITLE
browser.lisp: fix spawning new windows from internal buffers

### PR DESCRIPTION
**Pull request by aadcg**
A dirty fix for issue #1140.

There was quite a bit for me to unpack while looking at this. I don't know much about browsers honestly.

I hate this solution but I'm afraid my understanding isn't still quite where it should be.

Namely, I wonder if it makes sense that there is a `new-window-p` slot in the `request-data` class, and the `open-external-link-in-new-window-p` slot in the `browser` class.

I feel that some rewriting is probably the right thing to do but I feel I'm not up to it yet.  I need to understand the architecture of Nyxt a bit better first.

If you have something on your mind that you would like to detail, I can probably follow it and take actions accordingly.

### CODE REVIEW

**Comment by jmercouris** [comment]
A solution is a solution even if not ideal! I guess this does fix the problem :-D. I would like some time to think about what potential rearchitecting (as you've hinted at) may be necessary for a cleaner (generalized) solution.

**Comment by Ambrevar** [comment]
I can't remember the exact flow of events of the top of my head, but since I wrote this I have a feeling that this was done poorly :)  It's also very old code, so it's probably a good time to refactor it now that we've got a more stable code base.

I'll have a look later, I'm sure we can come up with a clean design here.
It's also probably not much code and André's intuition may be right.

**Comment by aadcg** [comment]
Feel free to take a deeper look and to have a short discussing over a (possible) redesign.

While I feel I'm of little valuable to the discussion, I'd be happy to make any possible changes you find necessary :)

**Comment by Ambrevar** [comment]
I just had a look: at first glance, I thought your fix was actually the right thing to do here... Until I realized that the mistake lied one level up, and actually the log message gives us a hint here:

```lisp
          (log:debug "Load URL from internal buffer in new buffer: ~a" (object-display url))
          (open-urls (list (object-string url)))
```

The problem is that we are not supposed to call `open-urls` here, a simple `make-buffer-focus` suffices!

Fixed with 1212f4722a6c2936f603de5133f58cc3497db7bd.
Thanks for investigating @aadcg !

**Comment by Ambrevar** [comment]
gg

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> The problem is that we are not supposed to call open-urls here, a simple
> make-buffer-focus suffices!

I'm trying to follow you, but I'm wondering if this solution works what
if all buffers are internal-buffers.  So, perhaps, make-buffer-focus can
move the focus to the new created buffer, before the url is loaded?

Thank you @ambrevar!

**Comment by Ambrevar** [comment]
Sorry, I don't understand the problem.  Can you provide a recipe?

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> Sorry, I don't understand the problem. Can you provide a recipe?

Sorry, I noticed that there were misprints in my comment!  I edited.

I thought about it again, and it seems to me that your solution will
work for sure in the case I wondered about.  But I'll check it myself
when I overcome my building issues.

**Comment by Ambrevar** [comment]
Sorry, still don't understand! :)

The context here is the current buffer.  The other buffers don't matter here.  So having only internal-buffers in our buffer list should not change anything.

`make-buffer-focus` creates a buffer, loads the URL in the background in focuses to it.  I don't think that loading the URL before or after the focus would change anything either.

Does that make sense?

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I don't think that loading the URL before or after the focus would
> change anything either.

Exactly, that was what made me wonder.  All clear now.

**Pull request closed without merging**
