### PR TITLE
global: Fix compilation notes.

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

This was due to +version+ being a constant, and SBCL being smart enough to resolve the `if' condition at compile time, thus complaining that a branch had been elided.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [x] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aadcg** [comment]
@Ambrevar thanks for this fix! Notice that ccl doesn't seem to like this change... :(

**Comment by aartaka** [comment]
Note that SBCL emits `sb-ext:code-deletion-note` on code deletion. If we can somehow handle this, we'll have no need for read-time hacks.

**Comment by Ambrevar** [comment]
I wouldn't call this a hack, since it makes sense for the body of `version` to be defined at read-time.

However CCL does not know the value of the `+version+` constant.  We can wrap it in `eval-always`.

@aartaka Any idea how to catch compilation errors with SBCL?

**Comment by aartaka** [comment]
> I wouldn't call this a hack, since it makes sense for the body of `version` to be defined at read-time.

Yes, that does make sense.

> However CCL does not know the value of the `+version+` constant. We can wrap it in `eval-always`.

Yes!

> @aartaka Any idea how to catch compilation errors with SBCL?

No idea except rebinding the debugger hook, which is wrong :(

**Comment by Ambrevar** [comment]
CCL fails but I can't see why.  A read error for `(defun version ...)`.  Maybe a compiler bug?

Unless someone can find a good workaround, I suggest to drop this pull request.

**Comment by Ambrevar** [comment]
> CCL fails but I can't see why. A read error for `(defun version ...)`. Maybe a compiler bug?

I should have noted that I cannot reproduce this locally, which is even more puzzling...

**Comment by aartaka** [comment]
I've tried to make the backtraces and error printing more consistent, but it's still imperfect and doesn't reveal much more of our error...

**Comment by jmercouris** [comment]
Please reopen when ready.

**Pull request closed without merging**
