### PR TITLE
Theme restructure

### LINKED ISSUE #3005: New Structure for color themes
@aartaka and I have some new surface colors in the oven, and I want to share the recipe here so you can say yes to it.
- feedback is appreciated, but not required.
- know that the next piece is revisiting the structure for typography (fonts per purpose), and this proposal will help with that.

### **Purpose**
1. establish a coherent structure for our default surface color theme, and future surface color themes; to help users see and interpret content, interact with the correct elements, and understand actions.
2. expand the color theme structure to cover all the current and future use cases we can think of. (so we don't need to hack in random values; to avoid future problems)
3. clarify the language around color themes.

### **Progress so far** 
Nyxt UI elements, potential new elements, css classes we might use later, and system states have been inventoried to assess [1] _how many colors do we require_ for a good UI, and [2] _how many color variations are required_ for each.
- the result of that inventory is that we require 8 colors and that each of those requires between 0 and 2 variations. 

We have been working to establish some programmatic norms around color selection to scale our choices today into future themes, and to aid with necessary typography selection.

### **What is your proposed change?**
The existing structure uses {background, primary, secondary, accent, warning} and an alternative for each. (10 colors total)

The better way is to structure the color themes by purpose, then provide 2 variations for each, for a total of 24 colors. like this:

#### 8 Main Colors
`primary`
- typically for: primary UI surfaces, panels etc.

`secondary`
- typically for: secondary UI elements, bars borders etc.

`background`
- typically for: large background elements

`warning`
- typically for: dangerous / potentially consequential actions, errors, failed downloads and page loads

`success`
- typically for: action completion, REPL successful run, successful/in-progress downloads, successful page loads

`action` (previously `accent`)
- typically for: focus affordance, action indicators, next-step prompting, background for selected elements

`codeblock` (previously `background-alt`)
- typically for: code, citation

`highlight` (as in #2994, possibly)
- typically for: highlighted text (selection), mission-critical information, search highlight, hints?

#### then we include the variations
 ONE tint, and ONE shade for each main color. This is to accomodate all the states of our widgets. For button it's:
- Regular state (main color.)
- Hovered state (shade color.)
- Pressed state (tint color.)
- Tab-focused state (shade surface or tint border.)

### **Rationale**
1. accommodate more complex UI components, we will require more colors for some elements (like dropdown menus with more states, and proper visual affordances for input fields), so let's add them now.
2. the current theme structure is somewhat arbitrary.
3. This proposal keeps the agreed on and brand ready colors from the old theme, and simply re-names them in helpful categories.
   - accent &rarr; `action`
   - background-alt &rarr; `codeblock`
   - primary, secondary, background, warning --- remain the same
4. YES contrast ratios have been considered, the logic from our surface structure here today also works with our text colors (`on-colors`) -- the on-color specifications will come with typography structure soon.
5. this will unblock that PR #2994 about text searching

### **Constraints**
- NO adding colors willy nilly. Artyom and I are meeting on Monday to try and use the new system to select color variations, and the proposed new colors `highlight` and `success`.
- NO changing brand guidelines; our purpose is to increase complexity and effectiveness without rethinking brand identity.
- NO breaking user created themes from previous versions.

# Pre-Build Checklist:
_talk through the change with someone, then come back and mark off what you can_
- [x] I have consulted with the team.
- [x] One or more developers have signed off on this change.
- [x] One or more user researchers have signed off on this change.

EDIT (by Artyom): Add more examples, fix some markup,

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This refactors our theming to the structure from #3005. With these, we should have more than enough colors and styles for any case.

This also uses new `codeblock` for code blocks in the manual and elsewhere
manual-codeblock
and a new `hightlight` color for search markers:
highlight-search

DRAFT: it's far from fixing everything. What's especially lacking is updates to documentation. @aadcg, I'll be grateful if you take a look, because you're the original maintainer for `libraries/theme/README` and are better in documentation than I am :)

What's left:
- [x] Update `libraries/theme/README`.
- [x] Update the manual.
- [x] Add `+/-` color generation when not provided explicitly.
- [x] Update theme tests:
  - [x] More exhaustive test theme creation.
  - [x] Test `+/-` color auto-generation.
  - [x] Test backwards-compatible aliases.
  - [x] Test contrast for new color pairs.
- (Sometime in the future) Contribute support for CSS4 selectors to LASS. See https://github.com/Shinmera/LASS/issues/19
- [x] (Deferrable?) Add color classes in addition to existent `.action` (previously `.accent`) and use them in e.g. debugger.
  - See also: #3102. 

Fixes #3005.
Closes #2994.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [X] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
    - Changelog update should be a separate commit.
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aartaka** [comment]
@lansingthomas, I've ran tests and the cold ruthless machine told me that these color pairs fall below their contrast requirements:
- Light theme:
  - `primary-` and `on-primary`: 4.232688 < 4.5
- Dark theme:
  - `primary-` and `on-primary`: 3.9166906 < 4.5
  - `secondary-` and `on-secondary`: 2.7702744 < 4.5
  - `secondary` and `on-secondary`: 6.36014 < 6.5
  - `secondary+` and `on-secondary`: 8.499446 < 8.5
  - `action-+` and `on-action`: 8.489511 < 8.5

Some of these are almost there, but a couple of them are quite far. Can you fix it? Should be simple enough, and for the non-trivial ones, I trust your judgement :stuck_out_tongue_winking_eye:

**Comment by lansingthomas** [comment]
Lets get on a call -- something is happening.

In light theme I see the surface color `primary-` as #686868 and the on-color `contrast-text` as #FFFFFF

primary- with contrast-text (light theme)

**Comment by lansingthomas** [comment]
I am seeing different contrast results in dark theme as well. I think we have our wires crossed.
This should be dark theme: `primary-` & `contrast-text

Screenshot 2023-07-31 at 12 15 33 PM

Damn these cold ruthless machines!!

**Comment by aartaka** [comment]
Interesting, so it might be that the tests are using a buggy contrast checker. @aadcg, any idea?

**Comment by jmercouris** [comment]
I shall work on this task :-)

**Comment by lansingthomas** [comment]
@jmercouris colors pleeeeeeeeeeeeeeeeze.
Frame 53

**Comment by jmercouris** [comment]
Patience my friend, I am trying to fix the keys...!

**Comment by aartaka** [comment]
Okay, I'm back to UI tasks, should I take over this PR?

**Comment by aartaka** [comment]
Tests fail, even with the fix for the luminance formula in e5de7f9342a41ba73df5ff612aa7032b8a446ae4. @lansingthomas, seems like we've missed something in the dark theme:
- `#ededed` on `#a55d3f` is 4.26, which is lower than 4.5.
- `#ededed` on `#874215` is 6.36, which is lower than 6.5.
- `#ededed` on `#6d3209` is 8.499, which is lower than 8.5 (wow, that's a close one, most contrast checkers round it up to 8.5!)
- `#ededed` on `#4c21ab` is 8.489 (really close too!)

Cross-checked with https://venngage.com/tools/color-contrast-checker and https://app.contrast-finder.org/

**Comment by aartaka** [comment]
@lansingthomas, it's too late for me to be effective at fixing/discussing it, so let's either
- Wait until Monday and have a call then. With new colors, this PR will be ready and I'll merge it given an approving review.
- Or you can adjust colors yourself (they are close already and you're good at preserving brand palettes), so that I can simply apply the new colors, wait for the review, and merge it on Monday.

**Comment by lansingthomas** [comment]
@aartaka good catch!

I'll post some new colors here in a few mins.

**Comment by lansingthomas** [comment]
These meet contrast spec properly :D 
`#481FA2` a slightly darkened purple for the dark:theme `action+` category

for the three dark:theme `seconday` categories
`secondary-` - `#9F592D`
`secondary` - `#844115`
`secondary+` - `#683008`

**Comment by lansingthomas** [comment]
Corrected SVG for documentation.
Surface Colors (Dark Theme) (3)

**Comment by aartaka** [comment]
Tests pass, I'll clean it up and ping someone for review.

Somewhat off-topic: @lansingthomas, our dark theme has a nice memorable name, why not have one for the light theme? I remember one of mock-ups having a set of associations, like "adventure", "sea" etc. I feel that names connected to the sea are the most fitting for the light theme. But I'm getting carried away :sweat_smile:

**Comment by jmercouris** [comment]
@aartaka ready?

**Comment by aartaka** [comment]
No, not yet! I'm trying to make libraries/theme/README and the manual :sparkles: perfect :sparkles:

**Comment by aartaka** [comment]
Okay, README is done. Y'all can get to reviewing, and I'll take care of the manual/changelog in the meanwhile.

**Comment by jmercouris** [comment]
OK!

**Comment by lansingthomas** [comment]
ooof--- i just wrote like 25 names in here and the browser crashed................. pain.

**Comment by aartaka** [comment]
I've updated theming examples in the manual and tested that they look okay-ish. I've pushed a new changelog entry too. Ready for review.

**Comment by lansingthomas** [comment]
I want to establish a naming convention for the themes:
`what we are naming` (some memorable-fun-brand associated word)

As we have done for `Dark theme (amphora)`

associations: stability, Greek, sun/light, the sea

Best so far for light theme:
Light theme (Helios)
Light theme (Ikaria)
Light theme (daylight)

**Comment by lansingthomas** [comment]
Light theme (radiance)
Light theme (luminous)
Light theme (zenith)
Light theme (daybreak)

**Comment by lansingthomas** [comment]
Light theme (Icarus)
Light theme (Ikaria)

**Comment by lansingthomas** [comment]
I like:
Light theme (Helios)

**Comment by aartaka** [comment]
> Light theme (radiance) Light theme (luminous) Light theme (zenith) Light theme (daybreak)

These (especially "daybreak" and, to a lesser degree, "zenith" (zenith is kind of too warm (pun not intended) to work with the cold-ish and light colors we have there)) sound good!

**Comment by lansingthomas** [comment]
I have it!

Light theme (fos)

fos is greek for light -- and its also Free Open Source!

**Comment by lansingthomas** [comment]
and we have preserved: Helios, Eos, Apollo,... for more divine products

**Comment by aartaka** [comment]
I'm pushing a small amendment to the manual, mentioning the built-in themes.

**Comment by aartaka** [comment]
Wel _now_ it's certainly review-ready!

**Comment by jmercouris** [comment]
Thanks Artyom, will have a look!

**Comment by jmercouris** [comment]
I've taken a look, just some minor comments. The pre code background is impossible to see. It was better before. The codeblock color. I'll go over it with Thomas and do the final merge tomorrow.

**Comment by jmercouris** [comment]
Only thing I did was fix "rewamp" -> "revamp".

**Comment by lansingthomas** [comment]
Recap-- John and I spoke today and tried a few styles for codeblock.  We ended up picking some new grays and removing the stroke. If anyone has a codeblock style from out in the wild that they like or love -- send me a screenshot! I am collecting them. 

The new structure makes it easy to create new themes and everyone should be writing code in good looking places :D

**Comment by jmercouris** [comment]
Thank you Artyom!

**Comment by lansingthomas** [comment]
Now featuring more grey! 

Surface Colors (light theme) (9)

**Comment by aartaka** [comment]
Papyrus colors weren't rhyming well with the other ones?

**Comment by lansingthomas** [comment]
Yeah they weren't hitting right.  The default one should be simple. So, meh.

Artyom we should do another theme! 

I previewed you the one un-published theme I have (invader)...
and I am thinking about another based on Zima blue (see Love, Death, and Robots S1, E14)
...

it is fun an easy to make themes with the structure we established.

**Comment by jmercouris** [comment]
I am pretty sure I did a merge commit, I went to master, then did "m" for merge and selected this branch. What should I have done different?

**Comment by aartaka** [comment]
>- What's the plan with regards to backwards compatibility? Will it be backwards compatibility "forever" or only until we release version 4? If the latter, then an issue needs to be opened.

I want to retain backwards-compatibility for as long as possible, so I'd say it stretches beyond 4.*. But it depends on how much maintenance burden it adds. I've written it in the dumbest and literal way I could, so that it's easier to maintain. But who knows...

**Comment by aartaka** [comment]
No, the set of colors and color groups is defined now. I'll update the SVG.

**Comment by aartaka** [comment]
Oh, right, the `text+` code issue...

**Comment by aartaka** [comment]
SVG updated in 1387166bfa6c8eb585a98a6cc78091f8eee03849 on master.

**Comment by lansingthomas** [comment]
`text` over `text+` for codeblocks is fine.

**Comment by lansingthomas** [comment]
in fact its magnificent. YES

**Comment by lansingthomas** [comment]
Going with Daybreak -- in the spirit of keeping things simple for this one.

Surface Colors (light theme) (12)

**Comment by jmercouris** [comment]
what happened to Fos?

**Comment by lansingthomas** [comment]
we spoke on the phone -- To maintain a Mediterranean theme, and to preserve the more divine greek names for other apps/extensions we are going to use an island name for light theme.

Santorini

**Comment by lansingthomas** [comment]
Surface Colors (light theme) (13)

**Comment by lansingthomas** [comment]
Further name changes will require a rebuttal to arguments above AND a better name.

**Comment by lansingthomas** [comment]
and a handwritten letter from the prime minister of Greece.

**Comment by aartaka** [comment]
>and a handwritten letter from the prime minister of Greece.

🤣

**Pull request merged**
