### PR TITLE
element-hint: Annotate full document by default.

### PR DESCRIPTION
**Pull request by Ambrevar**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Fixes #763.

**Comment by Ambrevar** [comment]
Oops, merged by mistake :(
@jmercouris, let me know if you don't like it.

**Comment by jmercouris** [comment]
It happens :-D

please add a P to indicate it is a predicate!

**Comment by Ambrevar** [comment]
Done.

**Comment by jmercouris** [comment]
Merci!

**Pull request merged**
