### PR TITLE
Edit data paths with external editor

### PR DESCRIPTION
**Pull request by Ambrevar**
This addresses https://github.com/atlas-engineer/nyxt/issues/1576.

What's left to do:

- [x] Add button on `help` page to run this command.
- [x] Allow creating the file if it does not exist.  Does it always make sense?  Just no if file is editable I guess.
- The weak hash table highlights that prompt buffer don't get garbage collected properly.  Recipe:

```lisp
> (hash-table-count *data-paths*)
N
> ; open a prompt buffer, then close it.
> (setf (old-prompt-buffers *browser*) nil)
> (tg:gc :full t)
NIL
> (hash-table-count *data-paths*)
P
```

Result: `P > N` while we should have `P=N`.

Any idea where the reference to old prompt buffers is kept?

### CODE REVIEW

**Comment by jmercouris** [comment]
Perhaps it is kept in a window object?

**Comment by Ambrevar** [comment]
@jmercouris @aartaka Do you know a way to keep track of instantiated
object in Common Lisp?

I suppose we could set `initialize-instance :after (t)` and record
everything that belongs to the Nyxt package.

Anything better?

Can we somehow track references?

**Comment by jmercouris** [comment]
I'll ask on IRC. I don't know of a way to do this.

**Comment by jmercouris** [comment]
Some great advice from IRC:

```
<Bike> what the thing i'm recalling does is give you a path from roots
    to a given object. since the object you're looking for is already
    alive for some reason, you're not making it any more impossible to
    collect
<Bike> here we go, sb-ext:search-roots
<Bike> "Find roots keeping the targets of [a weak pointer] alive"
<Bike> sounds useful for finding leaks, but i've never used it myself

```

**Comment by Ambrevar** [comment]
Great find!

With this, all that's missing is a systemic indexation of Nyxt objects
with weak pointers.

Would initialize-instance suffice there?

**Comment by jmercouris** [comment]
I don't see why not...!

**Comment by Ambrevar** [comment]
Alright, I tried this:

```lisp
(defvar *all-nyxt-objects* '()
  "Weak list.")

(defmethod initialize-instance :after ((object t)  &key)
  (when (member (symbol-package (sera:class-name-of object))
                (list (find-package :nyxt)
                      (find-package :nyxt-user)))
    (push (tg:make-weak-pointer object) *all-nyxt-objects*)))

(defun cleanup-all-nyxt-objects ()
  "`*all-nyxt-objects*' must not be changed while this is running."
  (let ((all-nyxt-objects *all-nyxt-objects*)) ; Just make sure we are handling a consistent object.
    (maplist (lambda (l)
               (when (and (second l)
                          (null (tg:weak-pointer-value (second l))))
                 (setf (rest l) (rest (rest l)))))
             all-nyxt-objects)
    (setf *all-nyxt-objects*
          (if (tg:weak-pointer-value (first all-nyxt-objects))
              (rest all-nyxt-objects)
              all-nyxt-objects))))
```

Then you can print the root of the object with

```lisp
(sb-ext:search-roots (second *all-nyxt-objects*) :print :verbose )
```

Or all roots in one go with

```lisp
(sb-ext:search-roots  *all-nyxt-objects* :print :verbose)
```

Awesome!

It helps, but it won't automatically reveal _why_ an object is not collected, it requires some deeper investigation.

You can force a garbage collection with `tg:gc`.  You can run `cleanup-all-nyxt-objects` manually to free the list of the collected objects.  I could have used a weak hash table to do this automatically, but then I don't know how to access the weak pointers in the hash table to feed them to `sb-ext:search-roots`.

I'll polish this and include it in Nyxt when `debug` is on or something like that.

**Comment by Ambrevar** [comment]
I believe this is ready to be merged.  The memory leak issue is unrelated to this anyways and will be worked out as part of #1612.

**Pull request merged**
