### PR TITLE
mode/bookmark.lisp: Make list-bookmarks interactive again

### PR DESCRIPTION
**Pull request by shamazmazum**
Make an entry in `*Bookmarks*` buffer disappear after you press delete button. I already did that before but that change was removed for some reason.

### CODE REVIEW

**Comment by jmercouris** [comment]
Apologies the change was removed, probably it got lost during our many architectural restructures!

**Comment by jmercouris** [comment]
In my testing it doesn't appear to work; the following appears in the REPL:

```
<WARN> [21:22:20] Warning: Error when running NIL: The function COMMON-LISP:NIL is undefined.
```

**Comment by jmercouris** [comment]
This is however very likely an error on our part, as I've noticed it elsewhere as well.

**Comment by shamazmazum** [comment]
@jmercouris yeah, I also cannot stop download with the same error ;)

**Comment by shamazmazum** [comment]
> In my testing it doesn't appear to work; the following appears in the REPL:
> 
> ```
> <WARN> [21:22:20] Warning: Error when running NIL: The function COMMON-LISP:NIL is undefined.
> ```

Aha, it seems that lisp can only be called with `nyxt/ps:lisp-eval` now. The breaking commit is 30140ab.
@Ambrevar can you explain how can I pass `url` to lisp in this code (`source/modes/bookmark.lisp`)?

~~~~
(ps:ps (defun delbkm (url)
                 (let ((section (ps:chain document active-element
				          (closest ".bookmark-entry"))))
			(ps:chain section parent-node (remove-child section)))
                 (fetch (+ "lisp://" (escape (+ "(nyxt/bookmark-mode:delete-bookmark \"" url "\")/")))
			(ps:create :mode "no-cors"))))))))
~~~~

**Comment by Ambrevar** [comment]
Oh yes, this `fetch` looks horribly wrong now! :p 

So here actually we can remove the whole delbkm trick since now lisp URLs are much shorter.  If you do not give it a title, it looks like this : `lisp://1234`, with `1234` the callback ID.

But this raises another problem that I didn't realize before: JS code can no longer pass JS data to the `lisp://` URLs.

@aartaka Any idea how to solve this?  I guess we would have to re-introduce argument support.

**Comment by shamazmazum** [comment]
A quick fix would be partially reverting b7dd2f1 and adding one JS function for each bookmark. Will this do?

**Comment by Ambrevar** [comment]
I think so.

**Comment by shamazmazum** [comment]
Done. Can you also help me with #2376 after this PR is merged? That issue is not directly related to this PR but is about bookmarks too.

**Comment by aartaka** [comment]
> But this raises another problem that I didn't realize before: JS code can no longer pass JS data to the `lisp://` URLs.
>
> @aartaka Any idea how to solve this? I guess we would have to re-introduce argument support.

Indeed, that's problematic. 

The good news is: the whole _raison d'être_ of this optimization is now gone with the fix to #2062, and we can attach as much wordy `nyxt/ps:lisp-eval`s to buttons as we wish to.

The bad news: we might still need to somehow pass arguments to `lisp://` URLs in the future (for reasons unconnected to code minification) and it's a non-trivial problem. We can use the mechanism from `nyxt://` URLs (namely, keyword arguments as query parameters), for one. But then, we don't always have control over the code in `lisp-eval` to the degree that we have control over the internal pages with `nyxt:://` URLs...

**Comment by shamazmazum** [comment]
I added a fix for #2376. Can you merge?

**Comment by shamazmazum** [comment]
On second thought I realized that this is unclear how the last commit fixes #2376 and how removes are different from `set-difference`. Removes keep the order, naturally, but it's unclear to me why #2376 happens with `set-difference`.

**Comment by shamazmazum** [comment]
@Ambrevar OK, I did my best to explain the fix :)

**Comment by Ambrevar** [comment]
The CI is failing:

```
; compiling file "NYXT:SOURCE;RENDERER;GTK.LISP.NEWEST" (written 20 JUN 2022 10:55:46 AM):
Heap exhausted during garbage collection: 160 bytes available, 176 requested.
```

Da hell?!?  Any idea anyone?

**Comment by shamazmazum** [comment]
I wonder if this has something to do with the patch :) I can compile with only 2 Gb heap. How many memory roswell gives to sbcl?

**Comment by Ambrevar** [comment]
Could be, but then https://github.com/atlas-engineer/nyxt/actions/runs/2529165821 (which is the exact same as this branch) passed!

**Comment by shamazmazum** [comment]
Played I bit more. I think you have to enhance size of the heap or you may encounter similar problems in the future. Default of 1 Gb is too damn small.

**Comment by Ambrevar** [comment]
Yup, it happend on https://github.com/atlas-engineer/nyxt/pull/2393 as well.  OK, I'll increase the size then.

(To clarify, the problem is only on the CI.  When built locally, we default to 3 GiB.)

**Comment by Ambrevar** [comment]
Merged with 96d0b1ff3cd7d1f105acde9b7da0b204b47b4fcf.  Thanks a lot for your contribution (and your patience!)

**Comment by shamazmazum** [comment]
Thanks!

**Pull request closed without merging**
