### PR TITLE
Enable automatic WebKit extensions loading.

### PR DESCRIPTION
**Pull request by aartaka**
This adds an ability to load arbitrary [WebKitWebExtension](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebExtension.html)s at `gtk-buffer` creation. Use-case: [bloKit](https://github.com/dudik/blockit).

# Things To Discuss:

- Maybe we should load extensions in all buffers, including `nosave` ones? For now, there's an overloaded `expand-path` method for `gtk-extensions-data-path` and `nosave-data-profile` that returns nil, so `nosave` buffers are extension-less.
- Is `gtk-extensions-data-path` a good name? Maybe `webkit-extensions-data-path`? Use of the `gtk-` prefix is consistent with all the renderer-gtk.lisp, though

# How Has This Been Tested
- Compiles.
- Runs.
- [test-extension from `cl-webkit`](https://github.com/joachifm/cl-webkit/tree/master/demo/test-extensions) loads and prints the "Page X created for (null)" message in the inferior lisp.

How does it look to you?

### CODE REVIEW

**Comment by Ambrevar** [comment]
Looks good to me!

About the nosave data profile, I don't know.  Can the user control which extensions gets enabled, or are they necessarily loaded?

@jmercouris Thoughts on this and on the extension path?

**Comment by aartaka** [comment]
> About the nosave data profile, I don't know. 

Well, the current behavior is consistent with the rest of the code, so let's stick to it.

> Can the user control which extensions gets enabled, or are they necessarily loaded?

All of the extensions in the directory are loaded. It's probably possible to make it configurable, but that's not trivial and will require some C code :)

**Comment by jmercouris** [comment]
I am OK with it :-)

thank you Artyom!

**Comment by Ambrevar** [comment]
If WebKitGTK would take multiple directories, then we could easily
choose which extension to load based on the directories passed to the
entry point.

**Comment by jmercouris** [comment]
Or extensions could be symlinked in and out of the directory if it is not possible to pass in a list of directories

**Comment by Ambrevar** [comment]
Indeed!

**Comment by aartaka** [comment]
> If WebKitGTK would take multiple directories, then we could easily choose which extension to load based on the directories passed to the entry point.

There's not such feature in WebKitGTK, as far as I know.

**Pull request merged**
