### PR TITLE
helper: define-command-prompt

### PR DESCRIPTION
**Pull request by Ambrevar**
The main purpose of this change is to check for the availability of the prompt buffer, and warn when it's not up.

Can we do better?

What do you think about inserting the implicit symbol `prompt-buffer` in the arg list?  Shall we name it `%prompt-buffer%` instead?

### CODE REVIEW

**Comment by Ambrevar** [comment]
@jmercouris Thoughts on this?

**Comment by jmercouris** [comment]
What about still keeping `&key prompt-buffer` within the lambda list? Makes it a little more flexible?

**Comment by Ambrevar** [comment]
And automatically replace it with `&key (prompt-buffer (current-buffer))`?

**Comment by Ambrevar** [comment]
But then how would the macro tell the different between the key argument
that designate the prompt-buffer, and the other ones?

**Comment by jmercouris** [comment]
Nevermind, you are right, there would be ambiguity. No other suggestions.

**Comment by Ambrevar** [comment]
Got an idea, we can make the first argument special.

I've updated the pull request to reflect this.
@jmercouris @aartaka What do you think?

**Comment by jmercouris** [comment]
I like this approach a lot. I concur. No other comments from me :-)

**Comment by aartaka** [comment]
Feels alright :)

**Pull request merged**
