### PR TITLE
Added method to delete buffers matching a regexp

### PR DESCRIPTION
**Pull request by aadcg**
Hi Nyxt!

This was begging to be written!

Let me know what do you think :)

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks for the initiative!

I'm not sure I can see a use case though, doesn't fuzzy matching already cut it for this job?
Can you provide an example where a regexp would be a clear advantage?

**Comment by aadcg** [comment]
I'm not sure if I understood.  

Is there a method to delete a bunch of buffers that match a string?

**Comment by Ambrevar** [comment]
Are you trying to do it interactively or programmatically?

If interactively:

- C-space delete-buffer
- "write something"
- M-a
- return

"M-a" select all the matches.

If programmatically, then it's almost a one liner.  We could add a
helper function for filtering buffers though.

**Comment by aadcg** [comment]
I was trying to do this interactively. Now it all makes sense. 

I guess next time I'll make sure that I won't spend time on something that already exists :D

**Comment by jmercouris** [comment]
There still is a typo fix in minibuffer-helper.lisp that should be fixed :+1: 

Also, there is something to be said about supporting regex match in addition to our fuzzy match, maybe we can still add this.

**Comment by jmercouris** [comment]
Well, not this exact iteration, but a way to delete / match based on regex.

**Comment by Ambrevar** [comment]
I'll add support for regexp matches in the new minibuffer.
Then it will be supported everywhere.

**Comment by Ambrevar** [comment]
@aadcg: Sorry for the time waste :/
In doubt, in the future feel free to ask in a new issue before you get
started writing code, it does not cost anything :)

**Comment by aadcg** [comment]
> Sorry for the time waste :/

It wasn't a waste of time as I learned some stuff along the way!

Next time I will be in closer contact for sure.

@jmercouris regarding the typo, I'm fine if you author the commit of course.

**Comment by Ambrevar** [comment]
I've merged your typo commit.

I've edited the commit message to this:

> Fix typo in `if-confirm' docstring.

We try to follow these conventions:

- Use the imperative tense ("fix" instead of "fixed").

- Try to mention _what_, _where_ and _why_.
  If _why_ is trivial, skip it.  Otherwise add an explanation in a
  separate paragraph.

I prefer to write proper sentences starting with a capital and ending
with a period.

Cheers!

**Comment by aadcg** [comment]
Pierre Neidhardt <notifications@github.com> writes:

> I've merged your typo commit.

Thank you.

> We try to follow these conventions:
>
> - Use the imperative tense ("fix" instead of "fixed").
>
> - Try to mention _what_, _where_ and _why_.
> If _why_ is trivial, skip it. Otherwise add an explanation in a
> separate paragraph.
>
> I prefer to write proper sentences starting with a capital and ending
> with a period.

Will certainly keep this in mind!

-- 
André Alexandre Gomes
"Free Thought, Free World"

**Pull request closed without merging**
