### PR TITLE
Theme refactor

### PR DESCRIPTION
**Pull request by aadcg**
Addresses #2289 and #2188.

# Screenshots
#### Before
old-prompt-buffer

#### After
new-prompt-buffer

#### Before
dark-old-prompt-buffer

#### After
dark-new-2-prompt-buffer

# Discussion

Whether we need more colors besides primary and secondary. Conclusion: we don't.
Handling buttons and hovering. Solution: apply an opacity of 50% to all hoverable elements.

- [ ] Can someone check how the theme looks relative to `bookmark-mode`? 

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by aartaka — COMMENTED** [review]
It looks more or less bearable, I'd say. Which screens does it not work on?

The only set of things that I've noticed were:
- Button hovering is quite broken -- it should switch between the `on-primary` and some other contrasting color (seems like our idea that we only need pairs of colors is not complete -- we need triplets or a separate set of element states -- like lighter button color (`primary` -> `secondary`) when hovered, for example). 
- Why use white-on-black as the source header in prompt-buffer? You can use either of `primary` or `secondary` here, I suppose -- they are delineated by indentation in addition to color, after all :)

**Comment by aartaka** [comment]
REPL looks quite unintelligible too :D

**Comment by aartaka** [comment]
More findings:
- Status buffer lacks colors, how about we use black for buttons and modes, while using `primary` and `secondary` for the rest?
- `secondary` has an ill contrast with white, so using it for buttons makes them indiscernible.

**Comment by aadcg** [comment]
About the triplets, I'm not quite sure yet. When we'll get to where I envision, I hope to convince you :p

I follow your concerns. Can we address this in another way? Instead of thinking about globally, let's firstly focus in one subset of the UI - the status buffer. 

When I did the changes, I did mechanically (query-replace) and blindly, since anyway it would require analyzing each and every case.

I need you help with CSS. Could you please look at commit 7e7483e52 and take a look at my comment on line 696?

**Comment by aadcg** [comment]
> REPL looks quite unintelligible too :D

Solved.

> Why use white-on-black as the source header in prompt-buffer? You can use either of primary or secondary here, I suppose -- they are delineated by indentation in addition to color, after all :)

Should be good now.

The status buffer was also massaged.

Hovering is still a big issue. I'm ruminating on the subject.

**Comment by aadcg** [comment]
Added screenshots to the first post in this PR.

**Comment by aadcg** [comment]
@aartaka Do you agree with 0c258a220?

**Comment by aadcg** [comment]
Please re-read my first post. Screenshots included.

I didn't squash the commits so that the changes can be tracked with ease. Taking a look commit-wise will help to review.

@jmercouris, you have been too quiet on this topic :thinking:

**Comment by jmercouris** [comment]
I am thinking. I like too much how our theme looks, but your argument is also irrefutable about minimum contrasts and usability. I am trying to think of how to solve this dilemma. The one approach I liked so far was that which was suggested by Artyom of keeping the default theme and adding high contrast variants for those who wish/require to use them.

**Comment by jmercouris** [comment]
Also we should change the glyph for the source icon, seems too many people lack this in their system font!

**Comment by aadcg** [comment]
@jmercouris is there a specific thing you don't like about the new theme? I'm not sure about prompt's buffer top line having an `accent` color background for instance. I think it's possible to make the theme better (more accessible) without compromising on the aesthetics of the old way. 

>  Also we should change the glyph for the source icon, seems too many people lack this in their system font!

Any suggestion?

**Comment by aadcg** [comment]
> maybe we should use LASS for styling? This way, we'd need no quirky macros for CSS theming...

It looks interesting, but do we want to do it now? Which macro are you referring to?

**Comment by jmercouris** [comment]
I believe Artyom is referring to the macro that generates CSS. Lass may be good, assuming it has an escape hatch! I have not investigated it thoroughly!

**Comment by aadcg** [comment]
Ready to merge from my side.

**Comment by aadcg** [comment]
@jmercouris, you can push commits to this branch!

**Review by aartaka — CHANGES_REQUESTED** [review]
As a follow-up to our last week discussion: get the bright yellow accent back to the dark theme, and we're good to go :P

**Comment by aadcg** [comment]
I'm merging this for now. I have concerns related to the dark theme (too long to describe). I believe @aartaka uses it a lot, so I expect some feedback in the future.

**Comment by Ambrevar** [comment]
Thanks a lot!

**Pull request closed without merging**
