### PR TITLE
Fix delete buffer race

### LINKED ISSUE #1546: "C-x k RET" leads me to a crash
It was my first time launching nyxt, I played with it for a few minutes, and then it crashed.
I tried to reproduce the crash, ~without success~ and managed to do it (see below the stack trace) 

I was visiting a results page of google and tried to kill the buffer using "C-x k RET" (I blame muscle memory). During the key combo, nyxt vanished.  Here's the full log from the console after my initial crash (a shorter one follows) :

## Full log and stacktrace

```
$ nyxt --version
Nyxt version 2.1.0

$ nyxt 
<INFO> [06:48:13] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.0
<INFO> [06:48:31] Update slot DEFAULT-MODES to (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%).
<WARN> [06:48:31] Warning: Error on separate thread: The file
                          #P"/home/youngfrog/.config/nyxt/auto-config.lisp"
                          does not exist:
                            Aucun fichier ou dossier de ce type
<INFO> [06:49:17] Update slot DEFAULT-MODES to (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%).
<INFO> [06:49:17] Appending to "/home/youngfrog/.config/nyxt/auto-config.lisp":
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%))))
<WARN> [06:49:40] Warning: Error on separate thread: There is no applicable method for the generic function
                            #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)>
                          when called with arguments
                            (NIL).
See also:
  The ANSI Standard, Section 7.6.6
<WARN> [06:49:45] Warning: Error on separate thread: There is no applicable method for the generic function
                            #<STANDARD-GENERIC-FUNCTION HISTORY-TREE:PARENT (1)>
                          when called with arguments
                            (NIL).
See also:
  The ANSI Standard, Section 7.6.6
<INFO> [06:50:19] Pressed keys: C-s
<INFO> [06:50:23] Pressed keys: C-h
<INFO> [06:50:31] Pressed keys: C-h
<INFO> [06:50:34] Press a key sequence to describe (cancel with 'escape escape'):
<INFO> [06:50:39] Press a key sequence to describe (cancel with 'escape escape'): "C-s" [C-#39]
<INFO> [06:50:55] Pressed keys: C-x
<INFO> [06:50:58] Pressed keys: C-x
<INFO> [06:50:59] Pressed keys: C-x
<INFO> [06:51:00] Pressed keys: C-x
<INFO> [06:51:44] Pressed keys: C-x
<INFO> [06:53:34] Loading "<redacted>".
<INFO> [06:53:35] Finished loading "<redacted>".
<INFO> [06:53:38] Pressed keys: C-x
<INFO> [06:53:50] Pressed keys: C-h
<INFO> [06:53:52] Pressed keys: C-s
<INFO> [06:53:54] Pressed keys: C-s
<INFO> [06:54:20] Pressed keys: C-x
<INFO> [06:54:21] Pressed keys: C-x
<INFO> [06:54:25] Pressed keys: M-g
<INFO> [06:54:37] Loading "<redacted>".
<INFO> [06:54:38] Finished loading "<redacted>".
<INFO> [06:54:48] Loading "<redacted>".
<INFO> [06:54:49] Finished loading "<redacted>".
<INFO> [06:54:55] Pressed keys: C-x
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING
                                    {1008B4A503}>:
  Owner with identifier "" does not exist

Backtrace for: #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING {1008B4A503}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {1008B8F5F3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {1008B8F5F3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {1008B8F5F3}>)
3: (ERROR "Owner with identifier ~s does not exist" "")
4: (HISTORY-TREE:SET-CURRENT-OWNER #<HISTORY-TREE:HISTORY-TREE {100657D713}> "")
5: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN WINDOW-SET-BUFFER))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN WINDOW-SET-BUFFER) {7F5D0CDAE7AB}> #<SB-THREAD:MUTEX "Anonymous recursive lock" owner: #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING {1008B4A503}>> T NIL)
8: (WINDOW-SET-BUFFER #<USER-WINDOW {10065774F3}> #<USER-WEB-BUFFER {100A12AA23}> :FOCUS NIL)
9: (SET-CURRENT-BUFFER #<USER-WEB-BUFFER {100A12AA23}> :FOCUS NIL)
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
13: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
15: (SB-THREAD::RUN)
16: ("foreign function: call_into_lisp")
17: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
<WARN> [06:54:55] Warning: Error: Joining thread failed: thread #<THREAD "Nyxt renderer thread" ABORTED {100807AA53}> did not return normally.
```

## Reproducing

I start from scratch using ```rm -rf ~/.local/share/nyxt ~/.config/nyxt```

I then create auto-config.lisp file, which will allow me to click on "Settings" then "Use emacs"
(otherwise a WARN is thrown -- see the first WARN from the log above), and run nyxt:

```
mkdir ~/.config/nyxt; touch ~/.config/nyxt/auto-config.lisp; nyxt
```
Inside Nyxt, do the following:
click "Common Settings", then "Use Emacs"
hit `M-l` and type `google.com` then `RET`
once the page has loaded, hit in rapid succession: `C-x k RET`
nyxt crashes for me.

### Backtrace for the repro

```
$ rm -rf /home/youngfrog/.local/share/nyxt ~/.config/nyxt; mkdir -p ~/.config/nyxt; touch ~/.config/nyxt/auto-config.lisp; nyxt
<INFO> [09:41:15] Listening to socket "/run/user/1000/nyxt/nyxt.socket".
Nyxt version 2.1.0
<INFO> [09:41:15] Loading Lisp file "/home/youngfrog/.config/nyxt/auto-config.lisp".
<INFO> [09:41:18] Update slot DEFAULT-MODES to (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%).
<INFO> [09:41:18] Appending to "/home/youngfrog/.config/nyxt/auto-config.lisp":
(DEFINE-CONFIGURATION BUFFER
  ((DEFAULT-MODES (APPEND '(NYXT::EMACS-MODE) %SLOT-DEFAULT%))))
<INFO> [09:41:22] Loading "https://google.com/".
<INFO> [09:41:22] Finished loading "https://www.google.com/#spf=1624434082342".
<INFO> [09:41:24] Pressed keys: C-x
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING
                                    {1007336D83}>:
  Owner with identifier "" does not exist

Backtrace for: #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING {1007336D83}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {10072AD4C3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {10072AD4C3}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Owner with identifier ~s does not exist" {10072AD4C3}>)
3: (ERROR "Owner with identifier ~s does not exist" "")
4: (HISTORY-TREE:SET-CURRENT-OWNER #<HISTORY-TREE:HISTORY-TREE {1009F13B83}> "")
5: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN WINDOW-SET-BUFFER))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<FUNCTION (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN WINDOW-SET-BUFFER) {7F85285A67AB}> #<SB-THREAD:MUTEX "Anonymous recursive lock" owner: #<SB-THREAD:THREAD "Prompter follow selection thread" RUNNING {1007336D83}>> T NIL)
8: (WINDOW-SET-BUFFER #<USER-WINDOW {1008BB30D3}> #<USER-WEB-BUFFER {1008DEBD43}> :FOCUS NIL)
9: (SET-CURRENT-BUFFER #<USER-WEB-BUFFER {1008DEBD43}> :FOCUS NIL)
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
13: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
15: (SB-THREAD::RUN)
16: ("foreign function: call_into_lisp")
17: ("foreign function: funcall1")

unhandled condition in --disable-debugger mode, quitting
<WARN> [09:41:24] Warning: Error: Joining thread failed: thread #<THREAD "Nyxt renderer thread" ABORTED {10082054D3}> did not return normally.

```

## System information

```
$ nyxt --system-information
Nyxt version: 2.1.0
Renderer version: GI-GTK
Operating system kernel: Linux 5.9.0-050900-generic
Lisp implementation: SBCL 2.1.0.0.HEAD.1-46cb065
Features: (WEBKIT2 WEBKIT2-2.32 WEBKIT2-PASTE-PLAINTEXT WEBKIT2-TRACKING WEBKIT2-MUTE
 WEBKIT2-EMOJI WEBKIT2-MEDIA WEBKIT2-SANDBOXING GTK-3-22 GTK-3-20 GTK-3-18
 GTK-3-16 GTK-3-14 GTK-3-12 GTK-3-10 GTK-3-8 GTK-3-6 GTK-3-4 GTK GDK-3-22
 GDK-3-20 GDK-3-18 GDK-3-16 GDK-3-14 GDK-3-12 GDK-3-10 GDK-3-8 GDK-3-6 GDK-3-4
 CAIRO-1-10 CAIRO-1-12 GDK-PIXBUF GLIB-2-30 GLIB-2-32 GLIB-2-34 GLIB-2-36
 GLIB-2-38 GLIB-2-40 GLIB-2-42 GLIB-2-44 GLIB-2-46 GLIB-2-48 GLIB-2-50
 GLIB-2-52 GLIB-2-54 GLIB-2-56 GLIB-2-58 GLIB NYXT-2 FSET-EXT-STRINGS
 CUSTOM-HASH-TABLE-NATIVE SWANK PLUMP-UTF-32 GLOBAL-VARS DECLARE-TYPES
 PARENSCRIPT NAMED-READTABLES 21BIT-CHARS CHUNGA FLEXI-STREAMS CLOSER-MOP
 CL-PPCRE-UNICODE CL-UNICODE BORDEAUX-THREADS SPLIT-SEQUENCE GRAY-STREAMS
 FAST-IO-SV FAST-IO SBCL-USES-SB-ROTATE-BYTE ASDF-SYSTEM-CONNECTIONS
 CL-JSON-CLOS CL-JSON THREAD-SUPPORT CL-PPCRE FLAT-NAMESPACE X86-64 UNIX CFFI
 FLAT-NAMESPACE SEQUENCE-EMPTYP QUICKLISP ASDF3.3 ASDF3.2 ASDF3.1 ASDF3 ASDF2
 ASDF OS-UNIX NON-BASE-CHARS-EXIST-P ASDF-UNICODE X86-64 GENCGC 64-BIT ANSI-CL
 COMMON-LISP ELF IEEE-FLOATING-POINT LINUX LITTLE-ENDIAN
 PACKAGE-LOCAL-NICKNAMES SB-CORE-COMPRESSION SB-LDB SB-PACKAGE-LOCKS SB-THREAD
 SB-UNICODE SBCL UNIX)

ASDF version: 3.3.4
Critical dependencies: (/home/runner/work/nyxt/nyxt/_build/submodules/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /home/runner/work/nyxt/nyxt/_build/quicklisp-client/dists/quicklisp/software/cl-gobject-introspection-20210124-git/cl-gobject-introspection.asd
 /home/runner/work/nyxt/nyxt/_build/submodules/cl-webkit/webkit2/cl-webkit2.asd)

Quicklisp dist version: 2021-05-31
Quicklisp client version: 2020-01-04
Local project directories: (/home/runner/work/nyxt/nyxt/_build/quicklisp-client/local-projects/)
Critical dependencies(#<SYSTEM cl-cffi-gtk / cl-cffi-gtk-20201220-git / quicklisp 2021-05-31>
 #<SYSTEM cl-gobject-introspection / cl-gobject-introspection-20210124-git / quicklisp 2021-05-31>
 #<SYSTEM cl-webkit2 / cl-webkit-20210531-git / quicklisp 2021-05-31>)
```

### PR DESCRIPTION
**Pull request by Ambrevar**
Should (finally!) fix #1546.

@aartaka @jmercouris @pdelfino @guojing0 Can you confirm that deleting 30+ buffers multiple times (try 5 tests at least) doesn't hang?

### CODE REVIEW

**Comment by jmercouris** [comment]
I cannot confirm the fix. I was able to delete all my buffers, but then froze shortly after navigating somewhere.

**Comment by jmercouris** [comment]
The inferior Lisp reports the following:

```
Heap exhausted during garbage collection: 32 bytes available, 160 requested.
Gen  Boxed   Code    Raw  LgBox LgCode  LgRaw  Pin       Alloc     Waste        Trig      WP GCs Mem-age
 3    2705      7  12891    293      0    606  542   534515744   6221792     2000000   16502   0  1.1607
 4       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 5       0      0      0      0      0      0    0           0         0     2000000       0   0  0.0000
 6     432      2    182     55      0     10    0    21643664    671344     2000000     681   0  0.0000
 7     555      1  10750   2182      0   2091  477   505779040   4713632     2000000   15579   0  0.0000
           Total bytes allocated    =    1061938448
           Dynamic-space-size bytes =    1073741824
GC control variables:
   *GC-INHIBIT* = true
   *GC-PENDING* = true
   *STOP-FOR-GC-PENDING* = false
fatal error encountered in SBCL pid 14778 tid 17488:
Heap exhausted, game over.

Error opening /dev/tty: No such device or address
```

Perhaps some tweaks to my SBCLRC are in order.

**Comment by jmercouris** [comment]
Increasing my --dynamic-space-size has fixed the issue. Perhaps we have a memory leak, perhaps not. In any case, the problem attempted to be solved here, has been solved.

**Comment by aartaka** [comment]
> Increasing my --dynamic-space-size has fixed the issue. Perhaps we have a memory leak, perhaps not. In any case, the problem attempted to be solved here, has been solved.

Should we do it by default when generating Nyxt binary, actually? That could guard users from occasional memory exhaustion failures (or make those less frequent at least).

**Comment by Ambrevar** [comment]
> I cannot confirm the fix. I was able to delete all my buffers, but then froze shortly after navigating somewhere.

This patch was meant to fix the freeze that happens _during_ buffer
deletion, so you bug is something else.  Maybe the dynamic space size
indeed.

> Should we do it by default when generating Nyxt binary, actually? That could guard users from occasional memory exhaustion failures (or make those less frequent at least).

Good idea!

**Comment by aartaka** [comment]
@Ambrevar, why adding those to 2-series directly, actually? Now I'm not sure how to get those two commits on master :(

**Comment by Ambrevar** [comment]
I've just merged them onto master.

I tend to work on 2-series and all the bug fixes that target 2-series
are thus based on that branch, this way we make the branch a first class
target for testing.

The other way around we would be primarily testing master and 2-series
would only be a second thought.

I think it's better to focus quality on 2-series, since we can test and
fine tune master later anyways.

Makes sense?

**Comment by aartaka** [comment]
> Makes sense?

It does, thanks for the explanation!

**Pull request merged**
