### PR TITLE
manual: Add link to cookbook.

### PR DESCRIPTION
**Pull request by Ambrevar**
Mitigates #203.

### CODE REVIEW

**Comment by jmercouris** [comment]
I almost think we should include a link to our site which redirects to the cookbook in case the URL ever changes, what do you think?

**Comment by Ambrevar** [comment]
Sure.  Can you set it up? :)

**Comment by jmercouris** [comment]
OK!

**Comment by jmercouris** [comment]
Done! : 1aa29f71

**Comment by Ambrevar** [comment]
Excellent, thank you very much!

**Comment by jmercouris** [comment]
No problem!

**Pull request closed without merging**
