### PR TITLE
renderer: Finalize classes when installing renderer.

### LINKED ISSUE #2721: Dangling `windows` when starting Nyxt from REPL multiple times
Commit 30c91a5be (in the context of PR #2666) introduces a bug.

Steps to reproduce:

- `(asdf:load-system "nyxt/gi-gtk")`
- `(nyxt:start :failsafe t)`
- notice that a single Nyxt window exists
- `(nyxt:quit)`
- notice that no Nyxt windows exist
- `(nyxt:start :failsafe t)`
- notice that 2 Nyxt windows exist

@Ambrevar could you please fix it?

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

@aadcg Does it fix #2721 for you?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [ ] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aadcg** [comment]
No. The issue persists.

**Comment by Ambrevar** [comment]
I can't reproduce on my end with this fix.

Could you try:

- start Nyxt.
- quit.
- Install the renderer.
- Inspect (with SLY) a renderer class, e.g. `(find-class 'renderer-buffer)`, and check if it's finalized and has the right superclasses.

**Comment by aadcg** [comment]
I have the feeling that you didn't understand the issue I reported on #2721.

The issue is related to starting/quitting Nyxt N times, which results in creating N windows when starting for the Nth time.

**Comment by aadcg** [comment]
As for what you requested:

```log
#<INTERFACE-CLASS {1004D5C1C3}>
--------------------
Name: RENDERER-BUFFER
Super classes: #<STANDARD-CLASS NYXT/RENDERER/GTK:GTK-BUFFER>
Direct Slots: 
Effective Slots: GTK-OBJECT, CONTEXT-NAME, HANDLER-IDS, GTK-PROXY-URL, PROXY-IGNORED-HOSTS, LOADING-WEBKIT-HISTORY-P
Sub classes: BUFFER
Precedence List: RENDERER-BUFFER, GTK-BUFFER, STANDARD-OBJECT, SLOT-OBJECT, T
Prototype: #<RENDERER-BUFFER {1007625873}>
--------------------
 Group slots by inheritance [ ]
 Sort slots alphabetically  [X]

All Slots:
[ ]  %CLASS-PRECEDENCE-LIST       = (#<INTERFACE-CLASS NYXT:RENDERER-BUFFER> #<STANDARD-CLASS NYXT/RENDERER/GTK:GTK-BUFFER> #<STANDARD-CLASS COMMON-LISP:STANDARD-OBJECT> #<SB-PCL::SLOT-CLASS SB-PCL::SLOT-OBJECT> #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>)
[ ]  %DOCUMENTATION               = NIL
[ ]  %TYPE                        = (CLASS #<INTERFACE-CLASS NYXT:RENDERER-BUFFER>)
[ ]  CAN-PRECEDE-LIST             = (#<STANDARD-CLASS PROMPTER:PROMPTER> #<STANDARD-CLASS NYXT/RENDERER/GTK:GTK-BUFFER> #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T> #<SB-PCL::SLOT-CLASS SB-PCL::SLOT-OBJECT> #<STANDARD-CLASS COMMON-LISP:STANDARD-OBJECT>)
[ ]  CLASS-EQ-SPECIALIZER         = #<SB-PCL::CLASS-EQ-SPECIALIZER #<INTERFACE-CLASS NYXT:RENDERER-BUFFER>>
[ ]  CPL-AVAILABLE-P              = T
[ ]  DIRECT-METHODS               = (NIL)
[ ]  DIRECT-SLOTS                 = NIL
[ ]  DIRECT-SUBCLASSES            = (#<USER-CLASS NYXT:BUFFER>)
[ ]  DIRECT-SUPERCLASSES          = (#<STANDARD-CLASS NYXT/RENDERER/GTK:GTK-BUFFER>)
[ ]  FINALIZED-P                  = T
[ ]  INCOMPATIBLE-SUPERCLASS-LIST = NIL
[ ]  NAME                         = RENDERER-BUFFER
[ ]  PLIST                        = NIL
[ ]  PROTOTYPE                    = #<RENDERER-BUFFER {1007625873}>
[ ]  SAFE-P                       = NIL
[ ]  SLOTS                        = (#<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK:GTK-OBJECT> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK:CONTEXT-NAME> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK:HANDLER-IDS> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK:GTK-PROXY-URL> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK:PROXY-IGNORED-HOSTS> #<SB-MOP:STANDARD-EFFECTIVE-SLOT-DEFINITION NYXT/RENDERER/GTK::LOADING-WEBKIT-HISTORY-P>)
[ ]  SOURCE                       = #S(SB-C:DEFINITION-SOURCE-LOCATION :NAMESTRING "/home/aadcg/common-lisp/nyxt/source/buffer.lisp" :INDICES 196609)
[ ]  WRAPPER                      = #<SB-KERNEL:WRAPPER (ID=4395) for RENDERER-BUFFER {504BE003}>
```

**Comment by Ambrevar** [comment]
> I have the feeling that you didn't understand the issue I reported on #2721.
> 
> The issue is related to starting/quitting Nyxt N times, which results in creating N windows when starting for the Nth time.

What do you think I didn't get?  Seems pretty clear to me.  I don't see N windows, just 1.

**Comment by Ambrevar** [comment]
The class inspection is correct.  Hmm...

@aartaka Can you reproduce?

**Comment by Ambrevar** [comment]
@aadcg Even if it does not fix it for you we can merge this as it fixes at least 1 bug.

**Comment by aadcg** [comment]
@Ambrevar I'll merge it then.

For the sake of completeness, could you please describe the bug that this PR fixes? Thanks.

**Comment by Ambrevar** [comment]
> For the sake of completeness, could you please describe the bug that this PR fixes? Thanks.

Describe where?

**Comment by aadcg** [comment]
In this PR. Just add a comment at the bottom please.

**Comment by Ambrevar** [comment]
This PR fixes a the class finalization bug: when restarting Nyxt from the REPL, the renderer classes would be in a broken state because they would not be finalized when the superclasses are changed.

This was particularly visible after quitting Nyxt and trying to inspect a renderer class, SLY would hang.

**Pull request merged**
