### PR TITLE
Update NASDF to 0.1.4.

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This re-uses NASDF 0.1.4 updated in our N-libraries, in Nyxt. Which highlight a lot of improvement space :D In particular, lots of symbols are not documented:

<details>
<summary> Compilation tests emit (huge log): </summary>

```
; Errors:
((#<PACKAGE "NYXT">
  (MAKE-SEARCH-ENGINE HOOK-KEYMAPS-BUFFER FFI-WINDOW-DELETE PROFILE-NAME
                      COMMAND-P FFI-BUFFER-URL INACTIVE-MODE-SOURCE
                      FFI-BUFFER-ZOOM-LEVEL ON-SIGNAL-KEY-PRESS
                      FFI-KILL-BROWSER NYXT-DATA-DIRECTORY PS-LABELS
                      RENDERER-SCHEME FFI-BUFFER-AUTO-LOAD-IMAGE-ENABLED-P
                      FFI-INITIALIZE FFI-WINDOW-MESSAGE-BUFFER-HEIGHT
                      ON-SIGNAL-NOTIFY-TITLE ON-SIGNAL-LOAD-REDIRECTED
                      ON-SIGNAL-LOAD-STARTED ADD-MODES-TO-AUTO-RULES +VERSION+
                      FFI-BUFFER-PROXY FFI-WINDOW-UNMAXIMIZE
                      RENDERER-REQUEST-DATA NYXT-TEMPORARY-DIRECTORY GLYPH
                      FFI-WINDOW-SET-BUFFER BUFFER-P FINALIZE-BUFFER
                      FFI-WINDOW-ADD-PANEL-BUFFER FFI-WINDOW-MAXIMIZE
                      FFI-FOCUS-PROMPT-BUFFER ALIST-OF
                      FORMAT-STATUS-LOAD-STATUS FFI-TRACKING-PREVENTION
                      FFI-BUFFER-COOKIE-POLICY MAYBE* FFI-BUFFER-MAKE
                      NETWORK-BUFFER-P FFI-BUFFER-COPY HOST-ONLY-URL-P
                      KEYWORD-SOURCE FFI-BUFFER-MEDIA-ENABLED-P
                      FFI-BUFFER-TITLE FFI-BUFFER-GET-DOCUMENT
                      DOCUMENT-SCROLL-POSITION NOSAVE-BUFFER-P
                      BACKGROUND-BUFFER-P DISPATCH-INPUT-SKIP
                      FFI-BUFFER-LOAD-HTML FFI-WIDTH *OPEN-PROGRAM*
                      FFI-GENERATED-INPUT-EVENT-P ON-SIGNAL-LOAD-FINISHED
                      FFI-BUFFER-CUT STATUS-BUFFER-P INTERNAL-URL-P
                      DEFAULT-MODES ON-SIGNAL-LOAD-FAILED MODES
                      FFI-BUFFER-LOAD-ALTERNATE-HTML FORMAT-STATUS-BUTTONS
                      BUFFER-HISTORY FFI-GENERATE-INPUT-EVENT FORMAT-STATUS
                      CONTEXT-BUFFER-P ON-SIGNAL-NOTIFY-URI SEARCH-ENGINE
                      XDG-DOWNLOAD-DIR FFI-MUTED-P
                      FFI-WINDOW-DELETE-PANEL-BUFFER FFI-FOCUSED-P WINDOW-MAKE
                      FORMAT-STATUS-MODES EQUALS FFI-WINDOW-MAKE
                      USE-NYXT-PACKAGE-NICKNAMES FFI-BUFFER-EVALUATE-JAVASCRIPT
                      FORMAT-STATUS-TABS NYXT-SOURCE-REGISTRY FFI-HEIGHT
                      FFI-ADD-CONTEXT-MENU-COMMAND FFI-DISPLAY-URL
                      PROMPT-RENDER-SUGGESTIONS HOOK-RESOURCE
                      FFI-BUFFER-REMOVE-USER-STYLE PROMPT-BUFFER-CANCELED
                      ON-SIGNAL-BUTTON-PRESS ECHO-DISMISS MODE-CLASS
                      FFI-WINDOW-TO-FOREGROUND EXTERNAL-VISIBILITY-PACKAGES
                      HTML-STRING-P CONFIG-DIRECTORY-FILE
                      INTERNAL-VISIBILITY-PACKAGES RENDERER-BROWSER SLOT-FORM
                      DOCUMENT-GET-PARAGRAPH-CONTENTS FFI-PRINT-STATUS +ESCAPE+
                      WINDOW-LIST +NEWLINE+ FFI-INSPECTOR-SHOW REQUEST-DATA
                      EXTERNAL-EDITOR-PROGRAM ON-SIGNAL-LOAD-CANCELED
                      PROMPT-BUFFER-P FFI-WINDOW-UNFULLSCREEN
                      LIST-PROFILE-CLASSES MODABLE-BUFFER-P DOCUMENT-MODEL
                      FFI-WINDOW-TITLE KEYMAP BUFFER-MATCH-PREDICATE
                      PANEL-BUFFER-P FFI-BUFFER-ADD-USER-SCRIPT
                      FFI-BUFFER-ADD-USER-STYLE
                      FFI-BUFFER-SMOOTH-SCROLLING-ENABLED-P DISPATCH-COMMAND
                      INSPECTED-VALUE VALID-SCHEME-P FFI-PRINT-MESSAGE
                      EMPTY-PATH-URL-P CURRENT-SOURCE RENDERER-BUFFER
                      ON-SIGNAL-LOAD-COMMITTED FFI-BUFFER-REDO FFI-BUFFER-UNDO
                      DOCUMENT-BUFFER-P FFI-BUFFER-PASTE
                      FFI-PREFERRED-LANGUAGES BUFFER-SOURCE
                      FFI-BUFFER-REMOVE-USER-SCRIPT
                      INHERITED-VISIBILITY-PACKAGES FFI-BUFFER-USER-AGENT
                      FFI-WEB-EXTENSION-SEND-MESSAGE RENDERER-WINDOW
                      INPUT-BUFFER-P FFI-BUFFER-JAVASCRIPT-MARKUP-ENABLED-P
                      WEB-BUFFER-P FFI-BUFFER-LOAD MODE AUTO-RULE
                      FFI-WINDOW-FULLSCREEN FFI-BUFFER-DOWNLOAD COOKIE-POLICY
                      URL-SOURCES LOG-FILE NYXT-SOURCE-DIRECTORY MODE-SOURCE
                      INTRO FFI-BUFFER-DELETE FFI-BUFFER-SELECT-ALL
                      FFI-BUFFER-SOUND-ENABLED-P MODE-P MAYBE PACKAGES
                      FFI-BUFFER-EVALUATE-JAVASCRIPT-ASYNC EXTENSIONS-DIRECTORY
                      BASE-MODE-P GLOBAL-HISTORY-SOURCE FFI-WINDOW-ACTIVE
                      ACTIVE-MODE-SOURCE FORMAT-STATUS-URL
                      FFI-BUFFER-JAVASCRIPT-ENABLED-P
                      FFI-WITHIN-RENDERER-THREAD MANUAL-CONTENT
                      COMBINE-COMPOSED-HOOK-UNTIL-NIL PANEL-BUFFER CLASS-FORM
                      FFI-BUFFER-WEBGL-ENABLED-P))
 (#<PACKAGE "NYXT/USER-SCRIPT-MODE">
  (RENDERER-USER-SCRIPT USER-SCRIPT-MODE-P RENDERER-USER-STYLE))
 (#<PACKAGE "NYXT/RECORD-INPUT-FIELD-MODE">
  (INPUT-ENTRY RECORD-INPUT-FIELD-MODE-P))
 (#<PACKAGE "NYXT/REPEAT-MODE"> (REPEAT-MODE-P))
 (#<PACKAGE "NYXT/PASSTHROUGH-MODE"> (PASSTHROUGH-MODE-P))
 (#<PACKAGE "NYXT/STYLE-MODE"> (STYLE-MODE-P DARK-MODE-P))
 (#<PACKAGE "NYXT/KEYSCHEME">
  (VI-INSERT DEFAULT EMACS CUA NYXT-KEYMAP-VALUE VI-NORMAL))
 (#<PACKAGE "NYXT/NO-IMAGE-MODE"> (NO-IMAGE-MODE-P))
 (#<PACKAGE "NYXT/HISTORY-TREE-MODE"> (HISTORY-TREE-MODE-P))
 (#<PACKAGE "NYXT/BOOKMARK-MODE">
  (EQUALS BOOKMARK-MODE-P BOOKMARK-SOURCE BOOKMARK-ENTRY BOOKMARK-ADD))
 (#<PACKAGE "NYXT/HINT-MODE">
  (IDENTIFIER UNHIGHLIGHT-SELECTED-HINT HINT-MODE-P HIGHLIGHT-SELECTED-HINT))
 (#<PACKAGE "NYXT/SEARCH-BUFFER-MODE">
  (SEARCH-BUFFER-MODE-P SEARCH-BUFFER-SOURCE))
 (#<PACKAGE "NYXT/REDUCE-TRACKING-MODE"> (REDUCE-TRACKING-MODE-P))
 (#<PACKAGE "NYXT/TYPES"> (HTML-STRING-P COOKIE-POLICY MAYBE* ALIST-OF MAYBE))
 (#<PACKAGE "NYXT/SMALL-WEB-MODE"> (SMALL-WEB-MODE-P))
 (#<PACKAGE "NYXT/ANNOTATE-MODE">
  (ANNOTATE-MODE-P ANNOTATION SNIPPET-ANNOTATION URL-ANNOTATION))
 (#<PACKAGE "NYXT/BOOKMARK-FREQUENT-VISITS"> (BOOKMARK-FREQUENT-VISITS-MODE-P))
 (#<PACKAGE "NYXT/UTILITIES"> (+NEWLINE+ +ESCAPE+))
 (#<PACKAGE "NYXT/INPUT-EDIT-MODE">
  (WITH-TEXT-BUFFER INPUT-EDIT-MODE-P
    WITH-INPUT-AREA))
 (#<PACKAGE "NYXT/AUTOFILL-MODE">
  (MAKE-AUTOFILL AUTOFILL-P AUTOFILL-MODE-P AUTOFILL-SOURCE))
 (#<PACKAGE "NYXT/DOWNLOAD-MODE"> (DOWNLOAD-MODE-P RENDERER-DOWNLOAD))
 (#<PACKAGE "NYXT/DOCUMENT-MODE"> (GET-URL-SOURCE RING-SOURCE DOCUMENT-MODE-P))
 (#<PACKAGE "NYXT/KEYSCHEME-MODE"> (KEYSCHEME-MODE-P))
 (#<PACKAGE "NYXT/EXPEDITION-MODE"> (EXPEDITION-MODE-P))
 (#<PACKAGE "NYXT/TTS-MODE"> (TTS-MODE-P))
 (#<PACKAGE "NYXT/NO-PROCRASTINATE-MODE">
  (NO-PROCRASTINATE-ENTRY NO-PROCRASTINATE-MODE-P))
 (#<PACKAGE "NYXT/MIGRATION"> (FIND-SUGGESTIONS SUGGESTION-P TIP SUGGESTION))
 (#<PACKAGE "NYXT/BUFFER-LISTING-MODE"> (BUFFER-LISTING-MODE-P))
 (#<PACKAGE "NYXT/MESSAGE-MODE"> (MESSAGE-MODE-P))
 (#<PACKAGE "NYXT/WATCH-MODE"> (WATCH-MODE-P))
 (#<PACKAGE "NYXT/SPELL-CHECK-MODE"> (SPELL-CHECK-MODE-P))
 (#<PACKAGE "NYXT/HELP-MODE"> (HELP-MODE-P))
 (#<PACKAGE "NYXT/VISUAL-MODE"> (VISUAL-MODE-P))
 (#<PACKAGE "NYXT/READING-LINE-MODE"> (READING-LINE-MODE-P))
 (#<PACKAGE "NYXT/PASSWORD-MODE"> (PASSWORD-MODE-P))
 (#<PACKAGE "NYXT/MACRO-EDIT-MODE"> (MACRO-EDIT-MODE-P))
 (#<PACKAGE "NYXT/PREVIEW-MODE"> (PREVIEW-MODE-P))
 (#<PACKAGE "NYXT/LIST-HISTORY-MODE"> (LIST-HISTORY-MODE-P))
 (#<PACKAGE "NYXT/EMACS-MODE"> (EMACS-MODE-P))
 (#<PACKAGE "NYXT/FORCE-HTTPS-MODE"> (FORCE-HTTPS-MODE-P))
 (#<PACKAGE "NYXT/CRUISE-CONTROL-MODE"> (CRUISE-CONTROL-MODE-P))
 (#<PACKAGE "NYXT/HISTORY-MODE">
  (HISTORY-ALL-OWNER-NODES-SOURCE BLOCKED-P HISTORY-FORWARDS-SOURCE
   HISTORY-BACKWARDS-SOURCE HISTORY-MODE-P HISTORY-ALL-SOURCE
   ALL-HISTORY-FORWARDS-SOURCE))
 (#<PACKAGE "NYXT/REPL-MODE"> (REPL-MODE-P CANCEL-CELL))
 (#<PACKAGE "NYXT/FILE-MANAGER-MODE">
  (FILE-MANAGER-MODE-P RECURSIVE-DIRECTORY-ELEMENTS))
 (#<PACKAGE "NYXT/HINT-PROMPT-BUFFER-MODE"> (HINT-PROMPT-BUFFER-MODE-P))
 (#<PACKAGE "NYXT/DOM">
  (TRACK-ELEMENT-P RUBY-ELEMENT-P OPTGROUP-ELEMENT-P BLINK-ELEMENT-P
                   SOURCE-ELEMENT-P COL-ELEMENT-P EM-ELEMENT-P S-ELEMENT-P
                   CHECK-ELEMENT TD-ELEMENT-P NOSCRIPT-ELEMENT-P DATA-ELEMENT-P
                   TITLE-ELEMENT-P OUTPUT-ELEMENT-P Q-ELEMENT-P
                   MARQUEE-ELEMENT-P CHECKBOX-ELEMENT-P TEMPLATE-ELEMENT-P
                   CITE-ELEMENT-P ISINDEX-ELEMENT-P CAPTION-ELEMENT-P
                   CODE-ELEMENT-P DIV-ELEMENT-P PLAINTEXT-ELEMENT-P
                   TBODY-ELEMENT-P COLGROUP-ELEMENT-P DETAILS-ELEMENT-P
                   STYLE-ELEMENT-P B-ELEMENT-P LINK-ELEMENT-P PICTURE-ELEMENT-P
                   MAP-ELEMENT-P HGROUP-ELEMENT-P GET-UNIQUE-SELECTOR
                   H6-ELEMENT-P INS-ELEMENT-P PRE-ELEMENT-P H3-ELEMENT-P
                   BGSOUND-ELEMENT-P DFN-ELEMENT-P NEXTID-ELEMENT-P
                   IFRAME-ELEMENT-P SUP-ELEMENT-P STRUCTURE-ELEMENT-P
                   ABBR-ELEMENT-P NOBR-ELEMENT-P VIDEO-ELEMENT-P H2-ELEMENT-P
                   BASEFONT-ELEMENT-P FRAME-ELEMENT-P SPACER-ELEMENT-P
                   RTC-ELEMENT-P MAIN-ELEMENT-P STRIKE-ELEMENT-P VAR-ELEMENT-P
                   TR-ELEMENT-P ADDRESS-ELEMENT-P TABLE-ELEMENT-P U-ELEMENT-P
                   MARK-ELEMENT-P DIR-ELEMENT-P LEGEND-ELEMENT-P SAMP-ELEMENT-P
                   LISTING-ELEMENT-P DT-ELEMENT-P LIST-ELEMENT-P
                   OPTION-ELEMENT-P DIALOG-ELEMENT-P MULTICOL-ELEMENT-P
                   AUDIO-ELEMENT-P DEL-ELEMENT-P UL-ELEMENT-P H5-ELEMENT-P
                   EMBED-ELEMENT-P KBD-ELEMENT-P DD-ELEMENT-P BDI-ELEMENT-P
                   CLICK-ELEMENT FIELDSET-ELEMENT-P INPUT-ELEMENT-P
                   FIGCAPTION-ELEMENT-P SUB-ELEMENT-P SPAN-ELEMENT-P
                   FILE-CHOOSER-ELEMENT-P AREA-ELEMENT-P LABEL-ELEMENT-P
                   ARTICLE-ELEMENT-P FORM-ELEMENT-P FONT-ELEMENT-P
                   BODY-ELEMENT-P SLOT-ELEMENT-P OL-ELEMENT-P TH-ELEMENT-P
                   META-ELEMENT-P A-ELEMENT-P NOFRAMES-ELEMENT-P WBR-ELEMENT-P
                   TEXT-ELEMENT-P CENTER-ELEMENT-P SELECT-OPTION-ELEMENT
                   HOVER-ELEMENT ACRONYM-ELEMENT-P RT-ELEMENT-P THEAD-ELEMENT-P
                   SUMMARY-ELEMENT-P BDO-ELEMENT-P PARAM-ELEMENT-P H4-ELEMENT-P
                   BR-ELEMENT-P HEAD-ELEMENT-P SEMANTIC-ELEMENT-P
                   ASIDE-ELEMENT-P TT-ELEMENT-P HEADER-ELEMENT-P
                   APPLET-ELEMENT-P LI-ELEMENT-P NOEMBED-ELEMENT-P
                   SECTION-ELEMENT-P BASE-ELEMENT-P DATALIST-ELEMENT-P
                   FRAMESET-ELEMENT-P FIGURE-ELEMENT-P GET-NYXT-ID H-ELEMENT-P
                   METER-ELEMENT-P BLOCKQUOTE-ELEMENT-P FOCUS-SELECT-ELEMENT
                   P-ELEMENT-P BIG-ELEMENT-P NAV-ELEMENT-P STRONG-ELEMENT-P
                   OBJECT-ELEMENT-P PROGRESS-ELEMENT-P BUTTON-ELEMENT-P
                   SCROLL-TO-ELEMENT DL-ELEMENT-P I-ELEMENT-P CANVAS-ELEMENT-P
                   SET-CARET-ON-START TEXTAREA-ELEMENT-P XMP-ELEMENT-P
                   IMG-ELEMENT-P RADIO-ELEMENT-P TIME-ELEMENT-P HTML-ELEMENT-P
                   HR-ELEMENT-P SCRIPT-ELEMENT-P H1-ELEMENT-P SELECT-ELEMENT-P
                   TOGGLE-DETAILS-ELEMENT RP-ELEMENT-P RB-ELEMENT-P
                   TFOOT-ELEMENT-P FOOTER-ELEMENT-P SMALL-ELEMENT-P))
 (#<PACKAGE "NYXT/NO-WEBGL-MODE"> (NO-WEBGL-MODE-P))
 (#<PACKAGE "NYXT/BLOCKER-MODE"> (BLOCKER-MODE-P))
 (#<PACKAGE "NYXT/NO-SCRIPT-MODE"> (NO-SCRIPT-MODE-P))
 (#<PACKAGE "NYXT/EDITOR-MODE">
  (PLAINTEXT-EDITOR-MODE-P EDITOR-BUFFER-P EDITOR-MODE-P))
 (#<PACKAGE "NYXT/PROXY-MODE"> (PROXY-MODE-P))
 (#<PACKAGE "NYXT/PROMPT-BUFFER-MODE"> (PROMPT-BUFFER-MODE-P))
 (#<PACKAGE "NYXT/CERTIFICATE-EXCEPTION-MODE"> (CERTIFICATE-EXCEPTION-MODE-P))
 (#<PACKAGE "NYXT/REDUCE-BANDWIDTH-MODE"> (REDUCE-BANDWIDTH-MODE-P))
 (#<PACKAGE "NYXT/VI-MODE"> (VI-INSERT-MODE-P VI-NORMAL-MODE-P))
 (#<PACKAGE "NYXT/REMEMBRANCE-MODE">
  (REMEMBRANCE-MODE-P REMEMBRANCE-SOURCE REMEMBRANCE-EXACT-SOURCE))
 (#<PACKAGE "NYXT/BOOKMARKLETS-MODE"> (BOOKMARKLETS-MODE-P))
 (#<PACKAGE "NYXT/NO-SOUND-MODE"> (NO-SOUND-MODE-P))
 (#<PACKAGE "NYXT/PROCESS-MODE"> (PROCESS-MODE-P)))
Found undocumented exported symbols in 59 packages.
```
</details>

While some of these undocumented symbols are propagated from auto-generated code (like class predicates from NClasses), some of them are simply undocumented APIs we have. It's a high time we document all the public stuff we have in Nyxt. 

@aadcg, interested in digging into that? I'll fix the problems with auto-generated code, but you're in a better position to add the human-readable documentation :P

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [ ] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aadcg** [comment]
Sure, I can help here!

**Comment by Ambrevar** [comment]
We should auto-generate the docstring for class predicates, right?

**Comment by aadcg** [comment]
@ambrevar, I just noticed that the guix package definition for `nasdf` points to `ntemplate`. Was this a mistake?

@aartaka let me know whether the symbol documentation should be part of this PR or a separate one.

**Comment by aartaka** [comment]
> @Ambrevar, I just noticed that the guix package definition for `nasdf` points to `ntemplate`. Was this a mistake?

(Answering for Pierre) That's deliberate: ntemplate is a single source of authority when it comes to creating new projects and updating existing ones, so the latest and greatest version of NASDF also resides in ntemplate.

> @aartaka let me know whether the symbol documentation should be part of this PR or a separate one.

Yes, it should.

**Comment by aartaka** [comment]
So the roadmap for this PR is:
- Release NASDF 1.5 (discuss https://github.com/atlas-engineer/ntemplate/issues/13 first).
- Release NClasses 0.4.1/0.5.0.
- Send both to Guix and update submodules.
- Check NASDF reports for the actual offenders.

**Comment by aadcg** [comment]
> the latest and greatest version of NASDF also resides in ntemplate

Ah, now I get it. NASDF is used in ntemplate.

> Yes, it should.

Please clarify if it should be part of this PR, or a separate one.

**Comment by aartaka** [comment]
> Please clarify if it should be part of this PR, or a separate one.

Documentation should be part of this PR so that we ensure all the tests pass.

**Comment by aadcg** [comment]
@aartaka I'm not being able to run this branch. I have the latest version of `njson` available at `~/common-lisp/njson`.

Any idea?

```log
debugger invoked on a ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread
#<THREAD "main thread" RUNNING {1001398073}>:
  Component "njson/aliases" not found

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry ASDF operation.
  1: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  2: [RETRY                        ] Retry EVAL of current toplevel form.
  3: [CONTINUE                     ] Ignore error and continue loading file "/gnu/store/yhg5z5dkfnp89lqs0gr1n1i9ccplfgz6-profile/bin/lisp-repl-core-dumper".
  4: [ABORT                        ] Abort loading file "/gnu/store/yhg5z5dkfnp89lqs0gr1n1i9ccplfgz6-profile/bin/lisp-repl-core-dumper".
  5:                                 Ignore runtime option --eval "(with-open-file (s \"/gnu/store/yhg5z5dkfnp89lqs0gr1n1i9ccplfgz6-profile/bin/lisp-repl-core-dumper\")
  (read-line s)
  (load s))".
  6:                                 Skip rest of --eval and --load options.
  7:                                 Skip to toplevel READ/EVAL/PRINT loop.
  8: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

((LAMBDA NIL :IN ASDF/SYSTEM:FIND-SYSTEM))
; File has been modified since compilation:
;   SYS:CONTRIB;ASDF;ASDF.LISP.NEWEST
; Using form offset instead of character position.
   error finding frame source: invalid feature expression: "#.(UIOP/UTILITY:SYMBOL-TEST-TO-FEATURE-EXPRESSION
   '#:COMPILER-ERROR-CONTEXT-%SOURCE '#:SB-C)"
   source: NIL
0] 
* 
Error generating image.
```

**Comment by aadcg** [comment]
Rebasing over master made it work. I'm not sure why.

**Comment by aadcg** [comment]
It seems that when I issue `(asdf:test-system :nyxt)` the output relative to system `nyxt/tests/compilation` is empty. See the log below. How can I trigger a report of the undocumented symbols?

```log
Test Summary for :NYXT/TESTS (74 tests 1.47 sec)
  | 221 assertions total
  | 221 passed
  | 0 failed
  | 0 execution errors
  | 3 warnings
  | 0 empty
  | 0 missing tests

-------   ENDING Testing: NYXT/TESTS 
; ------- STARTING Compilation Testing: (NYXT)
; ------- ENDING Compilation Testing: (NYXT)
Manual dumped to #P"/home/aadcg/common-lisp/nyxt/manual.html".
; 
; compilation unit finished
;   printed 3 notes
```

**Comment by Ambrevar** [comment]
Note that Nyxt's current NASDF has diverged because of #2955.
We should first merge Nyxt's NASDF into Ntemplte, release NASDF 0.1.5, then update this PR.

**Comment by Ambrevar** [comment]
Closing in favour of #3003.

**Pull request closed without merging**
