### PR TITLE
Add new theme color

### PR DESCRIPTION
**Pull request by aadcg**
# Description

Follow up on the work that @jmercouris started in #2843.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [ ] I have pulled from master before submitting this PR
- [ ] There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [ ] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [ ] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by jmercouris** [comment]
feel free to merge! :-)

**Comment by aadcg** [comment]
@jmercouris, I've added some tests so that we have a clear definition for what a background alternate color is: a color that features a contrast ratio of, at least, 12:1 against its on background alternate color.

Other than that, just some minor docstring refactor.

I wonder whether we should opt for a the more succinct `alt` other than `alternate`.

**Comment by aadcg** [comment]
>  feel free to merge! :-)

Ok, I'll squash my commits onto yours.

**Comment by aartaka** [comment]
Like... What has just happened? I mean, yes, I've been out of context for the last ten hours (sleeping mostly, because it was an actual night in my timezone), but still, that's quite a narrow margin for getting to review things. 

Yes, there was an email exchange (yes, part of my guilt there was that I've missed a couple of emails and didn't respond to all of them), but that didn't bring much reasons for a new color and was an absolutely different context than message buffer, so this PR is not exactly obvious, even based on our email communication.

I still strongly oppose adding more colors to our theme infra. Especially if there's _only one_ use-case for those. I can come up with half a dozen of use-cases that would be nice with the color of their own:
- Error/warning color—this one is clearly necessary, even more than the alternate background whatever. Because there's actual semantics for errors in Nyxt—like `echo-warning` printouts.
- Gopher error lines.
- Prompt hover color (because the current one is still to eye-catching).
- Button hover color (because abusing transparency is not always a good decision).
- A color for visited links 
  - and hovered ones.
- Color for tab chips, because they occupy a tight crowded spot between the multi-colored status buffer elements.
- Additional colors for status buffer elements (because it's clearly not enough to have even five colors for those to look both pretty and varied).
- Color for code listing (because the border is not aesthetically perfect solution.

But still, I don't add those, exactly because we shouldn't create new entities unless absolutely necessary. The only color I would add to the state of themes (before this PR, because I can't accept, again, adding a color for _just a single interface element_) is the error/warning color, and only after _discussing_ it with everyone and making sure we can't just use something that's already there.

Please revert this change and open this PR anew, so that we all have the chance to discuss alternative solutions.

**Comment by aadcg** [comment]
I think I should have not merged this PR the way I did. I reacted too lightly on @jmercouris' message "feel free to merge". 

The context here is, nonetheless, important. I've extracted these changes from PR #2843 (now #2855). Clearly the theme changes wouldn't belong there, and they seemed like a pre-requisite for the tabs UI changes. Also, the topic of adding a new nuanced background color has been discussed in other places. Personally, my view is close to the one you hold @aartaka, i.e. we should avoid adding colors at all costs. Still, I can't deny the need of such a color, nor can I offer practical robust alternatives to it. Notice that we have been resisting the impulse of adding this color on a number of occasions now. I don't think we're giving in to a mere impulse here, and I believe that this color will be widely used.

Regardless, _hasty merges should be the exception and never the rule_.  For instance, in this particular case, the README of the `theme` library wasn't revised at it should have been. That's partially my fault too!

**Comment by jmercouris** [comment]
Hello Artyom, I want to preface my response by saying I have the deepest respect and love for you. It is absolutely not my intention to hurt you or anyone on the team!

> Yes, there was an email exchange ... email communication.

In the final email titled on March 7th:

> John and I did a little screenshare and found a few use cases for a subtle third color, that will reallly improve readabiltiy in some areas and help us communicate hierarchy in other areas. I have also been looking at some other UIs that I like and I notice 3-5 colors seems to be the sweet spot. (see example png)

It is not the first time this new color has been requested. Initially, we circumvented the need for it by using an opacity hack. However, we ultimately need a new color.

> I still strongly oppose adding more colors to our theme infra. Especially if there's _only one_ use-case for those. I can come up with half a dozen of use-cases that would be nice with the color of their own:
> 
>     * Error/warning color—this one is clearly necessary, even more than the alternate background whatever. Because there's actual semantics for errors in Nyxt—like `echo-warning` printouts.

I think we *should* add this actually. I think it is a great idea! I'm not suggesting we abandon all caution, but I do believe there would be great fruitful improvements with some of the ideas you've suggested!

> But still, I don't add those, ... something that's already there.

There is often a gap between ideal and implementation. In modern applications there are many colors, we are however limiting ourselves to a few colors. I think this hurts our UI. The example above about the warning message is a great example. This color would be incredibly useful! We are trying to make the best user experience in terms of the code AND the graphical interface. I don't believe we can sacrifice the graphical interface in favor of the code.

> Please revert this change and open this PR anew, so that we all have the chance to discuss alternative solutions.

I do not believe this PR needs to be reverted, it does not break anything. If you have an alternative solution, please propose it!

> @jmercouris, you keep breaking rules and conventions, and I feel offended by the way you do it. Rules and conventions that we've established exactly to make sure we don't end up with changes someone on the team feels deeply wrong about. You are already:
> 
>     * Merging without review altogether.

I don't believe this is a fair characterization.

With regards to the prompt buffer changes:

+ I demoed many of them for Thomas. I should have better communicated this!

With regards to the theme:

+ We had an email exchange, and the conclusion remained uncontested for quite some time. Ultimately we have to give the final decision to someone. Thomas knows way more of UI than all of us combined.

>     * Trying to legitimize your activity with the veto right of @lansingthomas, who often is out of context for the changes you do.

This has been a failure on my part. He is not out of context. We have a meeting every week where we share screens and he shows me new design proposals. I often end up implementing them without adequately communicating that. In order to remedy this to some extent: https://github.com/atlas-engineer/nyxt/blob/master/.github/ISSUE_TEMPLATE/ui_request.md

>     * Borking up Git history and code with chaotic and unpolished changes.

For this I am sorry. I am a noob sometimes too... :-(

>       * I often have to fix your code to conform with our existing APIs and style guidelines (modes, CSS units, internal page content generation), because, for some reason, you ignore huge parts of the existing infrastructure.

If you mean using px vs em, that's a deliberate decision. Px supserede em since they are exact "* Pixels (px) are relative to the viewing device. For low-dpi devices, 1px is one device pixel (dot) of the display. For printers and high resolution screens 1px implies multiple device pixels.".

>       * And searching for accidental bugs using `git bisect` becomes much longer (+2 minutes per every commit) when the git history is chaotic like it is after your changes.

I am learning the new conventions, I apologize for my failures in this regard.

> I don't feel like we collaborate, because most of the conventions we've established together aren't actually working when you are involved. I understand that you're CEO or whatever, but I still think that when it gets to the engineering side of things, rules should work for everyone, no matter the position.

I never gave myself a title. I don't believe in authoritarianism. I am not trying to eschew rules! Yes, I am making a lot of mistakes, but I am still getting used to the new conventions. If you think I am inflexible of change and learning ask @ambrevar how I programmed when we first started working together :-D. I have been AFK from the engineering for a while, but I'll get better.

> If you continue doing the caution-less authoritarian stuff that you do, I'll absolutely lose belief in conventions and rules and will start to do the same: pushing over other's code, merging my own opinionated changes without caring for anyone else, and reverting things I don't like. Because what sense is there for me to follow the rules if no one does?

I would like to emphasize that I am not:
  + pushing over other's code
  + merging opinionated changes without consulting others
  + reverting changes I don't like

Conclusion:

Artyom, I am sorry. I understand your position. I want to emphasize that I am not trying to eschew rules and do whatever I want. I am trying to improve Nyxt, the best I can. We are on the same team, give me some time to catch up with the engineering standards and I'll be better!

**Comment by aartaka** [comment]
> Also, the topic of adding a new nuanced background color has been discussed in other places. Personally, my view is close to the one you hold @aartaka, i.e. we should avoid adding colors at all costs. Still, I can't deny the need of such a color, nor can I offer practical robust alternatives to it. Notice that we have been resisting the impulse of adding this color on a number of occasions now. I don't think we're giving in to a mere impulse here, and I believe that this color will be widely used.

I may have missed some of these places where there also was a necessity for this new color, so I'll be glad to know which interface elements do lack an additonal color. I've listed those that seem suspicious to me personally, but most—if not all—of those are just fine the way they already are now.

In case of the message buffer, I can see other alternatives, like adding borders or arrows (like in status buffer and for consistency with it). There are ways for message buffer to stand out without adding yet another color (which, by the way, does not even solve the fact that message buffer is still flat monotonous surface. It should've been addressed first—because no amount of new colors can fix it.)

So I suggest again: let's revert this hasty change and sit at the (metaphorical) table of negotiations and discuss it all over. I've a strong conviction that we don't need a new interface color (however temptating it may be adding another one), and should just simplify/dumb-down the interfaces that "need" it. Because even the REPL (probably one of the most complex Nyxt interfaces I ever designed) is just fine with the set of colors we have.

**Comment by aartaka** [comment]
@jmercouris, apologies accepted—I believe you meant no harm. Some short nitpicky remarks:
- Email conversation didn't end on 7th, there also were March 8th emals on a separate thread. So it was not set in stone.
- Error color I can accept, this background-alt color—not yet. It has to have places it's actually needed in. So let's discuss these first and add the new color after all of us see its necessity (again, I'm not claiming it's universally unnecessary, I'm only operating on the data I have, which may be crazy incomplete).
- `em` is relative, but if you want absolute one—you can use `rem`. Those are both absolute/reliable per document (which anyway is what matters), and relative to the screen/settings of the user much better than `px` are.
- Good places to learn the up-to-date conventions could be: 
  - Our developer manual (https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org).
  - The actual `manual`.
  - And the pull request template—it was crafted with love and desire to check every single thing that makes a PR perfect :)

**Comment by aartaka** [comment]
> Regardless, _hasty merges should be the exception and never the rule_. For instance, in this particular case, the README of the `theme` library wasn't revised at it should have been. That's partially my fault too!

Not only that:
- Dark theme should've been brought up to date too. That's the one that hit me hardest—literally, a huge strip of (almost) white on an otherwise dark screen!
- `manual#appearance` should've been updated too.
- Article about theming Nyxt on our blog should also have been brought up to date.

But that, again, is a hypothetical chain of actions to do when we decide on needing this color. We have to decide it first :)

**Comment by aadcg** [comment]
> Dark theme should've been brought up to date too. That's the one that hit me hardest—literally, a huge strip of (almost) white on an otherwise dark screen!

How come? `background-color-alternate` is set to  `"#333333"` on dark themes, and to `"#eeeeee"` on light ones.

**Comment by jmercouris** [comment]
>     * Error color I can accept, this background-alt color—not yet. It has to have places it's actually needed in. So let's discuss these first and add the new color after all of us see its necessity (again, I'm not claiming it's universally unnecessary, I'm only operating on the data I have, which may be crazy incomplete).

How do you suggest we draw the tabs (while keeping it aesthetically pleasing)?

>     * `em` is relative, but if you want absolute one—you can use `rem`. Those are both absolute/reliable per document (which anyway is what matters), and relative to the screen/settings of the user much better than `px` are.

Noted, I shall use REM from now on!

>     * Good places to learn the up-to-date conventions could be:
>       
>       * Our developer manual (https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org).

I don't think I need to read the bit about the Lisp...  I think the part that changed and I have yet to truly master is largely the changes to how we handle Git. If you think my Lisp is bad, I can accept that, and am always willing for critique! I've never been a fan of style guides though, I believe in good judgement over linters/guides.

>       * And the pull request template—it was crafted with love and desire to check every single thing that makes a PR perfect :)

Yes, it is good, but too long and onerous. I think we should make it far simpler, it is quite intimidating!

**Comment by aartaka** [comment]
> How do you suggest we draw the tabs (while keeping it aesthetically pleasing)?

I've suggested several prototype designs in the respective PR.

> Noted, I shall use REM from now on!

<3

> > ```
> > * Good places to learn the up-to-date conventions could be:
> >   
> >   * Our developer manual (https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org).
> > ```
> 
> 
> I don't think I need to read the bit about the Lisp...  I think the part that changed and I have yet to truly master is largely the changes to how we handle Git. 

> If you think my Lisp is bad, I can accept that, and am always willing for critique! I've never been a fan of style guides though, I believe in good judgement over linters/guides.

No, I'm not saying your Lisp is bad. I mainly suggested the developer manual for the bits explaining commits and branches, and for Nyxt-specific uses of Lisp (like `(setf accessor) :after`, `maybe` types, etc.)

> > ```
> >   * And the pull request template—it was crafted with love and desire to check every single thing that makes a PR perfect :)
> > ```
> 
> Yes, it is good, but too long and onerous. I think we should make it far simpler, it is quite intimidating!

Indeed, intimidating it is. Let's discuss what we can shave off, in #2857.

**Pull request merged**
