### PR TITLE
Process permission requests.

### LINKED ISSUE #252: Mute Tab (microphone)
Hi,

A neat feature of Chromium and Icecat is muting tab or all tabs.

I know that webkit has that mute feature. Cant say for Webkitgtk

Thanks!

### PR DESCRIPTION
**Pull request by aartaka**
This allows for websites to ask the user for different permissions (e.g. geolocation, microphone) that are otherwise blocked. Some websites cannot work without such permissions (think conferencing or navigation software).

# Caveats
Requires cl-webkit to be at least at https://github.com/joachifm/cl-webkit/commit/dc730eb6c7e5b1e9da774372b08da8c70c02dd02. How about we actually release cl-webkit 3.1 with all the accumulated changes and fixes?

# How to test
- Compile Nyxt with this patch
- Run it
- Go to https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation
- Click `Try it` button.
- The prompt-buffer will appear with the question about geolocation.
- While this testing page is old and doesn't work as described (it doesn't necessarily show your lattitude), it still gets geolocation access if you grant it.

How does it look to you?

Closes #252 
Maybe #1041?

### CODE REVIEW

**Comment by Ambrevar** [comment]
I suppose that this does not enable WebRTC yet, does it? :p

**Comment by aartaka** [comment]
> I suppose that this does not enable WebRTC yet, does it? :p

I am not sure :) The best we can do is test and see!

**Comment by Ambrevar** [comment]
Looks good to me!
Can you update the cl-webkit submodule?

**Comment by aartaka** [comment]
> Looks good to me!
> Can you update the cl-webkit submodule?

Done!

**Comment by aartaka** [comment]
Merging then?

**Comment by jmercouris** [comment]
Yes :-)

**Comment by aartaka** [comment]
I'm afraid to merge, as I've finally gotten WebKit 2.34.1 and cannot re-test it yet again xD

**Comment by jmercouris** [comment]
Ok I'll do one final test and then merge :-)

**Comment by jmercouris** [comment]
Well then, guess that won't be needed :-D

**Comment by aartaka** [comment]
Oooops, sorry 😅 Anyway, It felt pretty robust to me :)

**Comment by jmercouris** [comment]
It's fine, just use kaomojis please, this an emoji free repository

**Comment by aartaka** [comment]
Sure (*≧▽≦)ﾉｼ))

**Pull request merged**
