### PR TITLE
fix un-fullscreening on focus-out-event

### PR DESCRIPTION
**Pull request by shaunsingh**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Removes code that was supposed to fix an older bug, but has an unintentional side-effect of un-fullscreening nyxt when its not supposed to

Fixes # (issue)
https://github.com/atlas-engineer/nyxt/issues/2359
https://github.com/atlas-engineer/nyxt/issues/1715

# Discussion

Mention there any suspicious parts of the new code, or the ideas that you'd like to discuss in regards to this change.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [ ] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by shaunsingh** [comment]
Tested on swayWM and River (wayland). Though the linked issue (#1715) says it fixed it for them on xmonad, someone on X11 should probably test as well

**Comment by Ambrevar** [comment]
CC @aartaka 

I'm pretty sure this is not the right fix, since focusing to an external application will then _not_ unfullscreen, which is not desirable.

We need a way to tell whether the focus change is happening within Nyxt or not.
Maybe just check if the main window still has the focus?  It's trivial and it should work.

**Comment by aartaka** [comment]
> I'm pretty sure this is not the right fix, since focusing to an external application will then _not_ unfullscreen, which is not desirable.

Right...

> We need a way to tell whether the focus change is happening within Nyxt or not. Maybe just check if the main window still has the focus? It's trivial and it should work.

Yes, that should work. Alternatively, check all of `panels-right`, `panels-left`, and `current-prompt-buffer` for the focus (`ffi-focused-p` on all of those should work). @shaunsingh, does that sound like a strategy for you?

**Comment by shaunsingh** [comment]
> I'm pretty sure this is not the right fix, since focusing to an external application will then not unfullscreen, which is not desirable.

My use case is when NYXT is the only window is a workspace, I fullscreen it, then I can switch between workspaces/applications and keep NYXT fullscreened. From what I understand you'd like it so if I switch nyxt to a different application the correct behavior would be to un-fullescreen the app?

> Yes, that should work. Alternatively, check all of panels-right, panels-left, and current-prompt-buffer for the focus (ffi-focused-p on all of those should work). @shaunsingh, does that sound like a strategy for you?

@aartaka I can certainly update the PR to reflect that, just wanted some clarification on what should be the expected behavior

For reference the behavior with the patch above matches the behavior of firefox/chrome

**Comment by aartaka** [comment]
> > Yes, that should work. Alternatively, check all of panels-right, panels-left, and current-prompt-buffer for the focus (ffi-focused-p on all of those should work). @shaunsingh, does that sound like a strategy for you?
> 
> @aartaka I can certainly update the PR to reflect that, just wanted some clarification on what should be the expected behavior

So yeah, don't unfullscreen if there is:
- Prompt buffer focus.
- Panel buffer focus.
- Main buffer focus.
And unfullscreen otherwise.

> For reference the behavior with the patch above matches the behavior of firefox/chrome

This fullscreen-then-switch behavior works even without this patch, at least for me (゜▼゜＊）

**Comment by shaunsingh** [comment]
Ah, thats definitely a cleaner way to go about it. Thanks! will update the PR

**Comment by jmercouris** [comment]
Any update? @shaunsingh

**Comment by jmercouris** [comment]
> CC @aartaka
> 
> I'm pretty sure this is not the right fix, since focusing to an external application will then _not_ unfullscreen, which is not desirable.
> 
> We need a way to tell whether the focus change is happening within Nyxt or not. Maybe just check if the main window still has the focus? It's trivial and it should work.

I believe this premise is flawed.

Full screen Firefox, then alt-tab to another application. Does Firefox become unfullscreened? No. It doesn't, and neither does Emacs. This is the expected behavior. We shouldn't make decisions like this for the user. That is the job of the WM.


https://user-images.githubusercontent.com/1691662/228669440-efc58f40-5c31-4530-92e1-7affdacfa98d.mp4

**Comment by jmercouris** [comment]
Upload attempt #2: 

https://user-images.githubusercontent.com/1691662/228669744-10c87961-828c-4107-b7da-3206cba99c05.mp4

**Comment by shaunsingh** [comment]
> Any update? @shaunsingh

Sorry, got a bit caught up with stuff. I'll take a look into this (and splits) soon. 

> > I'm pretty sure this is not the right fix, since focusing to an external application will then not unfullscreen, which is not desirable.
> I believe this premise is flawed.

I also (and many others) use fullscreen as a productivity tool to have one app take up the full screen, and I want it to stay full screened when switching between apps (as other browsers do). I personally think handling fullscreen should be left up to the WM rather than nyxt but I'm not experienced with the internals.

**Comment by jmercouris** [comment]
@Ambrevar what do you think of my above rationale?

**Comment by Ambrevar** [comment]
Yup, that's fair.

**Pull request merged**
