### PR TITLE
Tweak day theme palette 

### PR DESCRIPTION
**Pull request by lansingthomas**
# Description

add day theme palette to documents/.../theme

Fixes # ([Style Guide Discussion](https://github.com/atlas-engineer/nyxt/discussions/2867))

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [ ] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [ ] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by aartaka** [comment]
Not yet, we need more discussion on it.

**Comment by lansingthomas** [comment]
Good?

**Comment by lansingthomas** [comment]
Nyxt palette (Day) (2)

**Comment by lansingthomas** [comment]
uploaded a version with on-colors / text colors removed. @aartaka and I made some decisions about these but I wont impose them without creating a thread elsewhere. One thing at a time : )

@aadcg if you prefer to have this live in the readme please make it happen. I am not so adept with the .org files. Thank you.

**Comment by aartaka** [comment]
> uploaded a version with on-colors / text colors removed. @aartaka and I made some decisions about these but I wont impose them without creating a thread elsewhere. One thing at a time : )

Sure :)

**Comment by aadcg** [comment]
@lansingthomas thank you! I'll make it happen and keep you updated.

From a purely technical reason, it's easier for me to close this PR and open a new one since this branch isn't in our remote, but in @lansingthomas' fork of the project. Don't worry @lansingthomas, your commit will still be there!

In the new PR I'll review documentation and refactor the theme library to reflect the changes that were agreed upon.

**Pull request closed without merging**
