### PR TITLE
Htree without current owner

### PR DESCRIPTION
**Pull request by Ambrevar**
Lo and behold, the GHT is now much more reliable!

The theory is super simple: always pass the owner (the buffer ID) to all `htree` calls.

In practice, it induces a lot of changes.  Tests pass, but there might be a few broken calls here or there.
Please test!

Should fix https://github.com/atlas-engineer/nyxt/issues/1214,
https://github.com/atlas-engineer/nyxt/issues/1370 and address the biggest concern of https://github.com/atlas-engineer/nyxt/issues/1677.

Questions:

- This is _not backward compatible_.  The older history file still loads though, so the transition should be smooth for most people who don't use `htree` directly in their config.
Can we somehow preserve backward-compatibility even for the `htree` API?  It seems not possible, but please prove me wrong.
If we can't, shell we merge this as part of the 2-series still?

- Instead of passing `history` and `owner-id` as argument for `htree:forward`, etc., what about just passing an `owner` object`?  Then we could write

```lisp
(let ((owner (htree:owner history owner-id)))
  (htree:forward owner))
```

It'd be more convenient when chaining many htree calls, but it's less convenient for single htree calls.  Turns out that we never chain many htree calls, so might not be worth it.

Thoughts?

- What can of data should be use as owner IDs?  Currently, we use the buffer ID, but what about using the buffer object itself?  Maybe a bad idea, because if we don't clean up the history properly we may be holding reference back to dead buffers.  Thoughts?

Should we stick to buffer IDs, could we enforce typing?  Probably, like we do with `keymap` bindings.  I'd need to add this option then.

### CODE REVIEW

**Comment by jmercouris** [comment]
Only bug I found was `buffer-history-tree`, and `history-tree`, unfortunately I found these bugs after merging... since you are quite a bit more familiar, could you fix these? I took a look, but was not sure.

**Comment by Ambrevar** [comment]
Will look into it.

Other point I want to investigate since you reported an issue with this
patch when _not_ restoring buffers: we should reset the owners to '()
when loading the history and not restoring the buffers.

This bug has been around since we've merged the GHT.

**Comment by Ambrevar** [comment]
Fixed history-tree with 87c828ae92489b70508b74bebe43b11474672859.

**Comment by jmercouris** [comment]
Thank you Pierre!

**Pull request merged**
