### PR TITLE
Synchronous minibuffer cleanup

### PR DESCRIPTION
**Pull request by Ambrevar**
I've tried to apply #928 to all of Nyxt.  The result is that it does not start :( 

The problem with starting command in a new thread is that if a command calls a renderer instruction (like making a buffer) it needs to switch to the renderer thread.  

One way to fix it is to wrap all FFI functions with `ffi-within-renderer-thread`.  But what about the FFI functions for which the command needs a return value?

We can juggle with threads but it seems hard to guarantee the absence of dead locks.

### CODE REVIEW

**Comment by jmercouris** [comment]
I think the only way to fix it is to have ffi-within-renderer-thread sprinkled when necessary. The way I see it we have two options:

1. Awkward with-result handling of inputs
2. Awkward necessity of ffi-within-renderer-thread

I would prefer number 2. There is unfortunately no perfect solution (yet :-D), and we must make a trade.

**Comment by jmercouris** [comment]
We cannot guarantee the absence of deadlocks UNLESS we perform no blocking operations on the main thread.

**Comment by jmercouris** [comment]
The only resource that any thread could currently starve over would be the main thread.

**Comment by Ambrevar** [comment]
But when is it "necessary" to use ffi-within-renderer-thread?  It's not
so clear.

The only place where it's clear is around all the ffi-* functions.  I
tried to do this in the latest commit, but it hangs the browser on
startup.

The problem is that we don't know where the ffi-* function is called
from.
If it's called from the command thread, it works.  If called from the
renderer thread, it blocks.

**Comment by Ambrevar** [comment]
I've got an idea: the main issue here is that we don't know when the
caller is on the GTK thread or another thread.  If we knew, we could
decide whether to call ffi-within-renderer-thread or not (no need if
already on the GTK thread).

We can obtain the renderer thread with this code:

--8<---------------cut here---------------start------------->8---
(defvar *renderer-thread* nil)
(ffi-within-renderer-thread *browser*
 (lambda ()
  (setf *renderer-thread* (bt:current-thread))))

(defun renderer-thread-p ()
  (eq *renderer-thread* (bt:current-thread)))
--8<---------------cut here---------------end--------------->8---

Then we update ffi-within-renderer-thread:

--8<---------------cut here---------------start------------->8---
(defmethod ffi-within-renderer-thread ((browser gtk-browser) thunk)
  (declare (ignore browser))
  (if (renderer-thread-p)
      (funcall thunk)
      (gtk:within-gtk-thread
        (funcall thunk))))
--8<---------------cut here---------------end--------------->8---

@jmercouris: Do you think that would work?

**Comment by Ambrevar** [comment]
Actually this is wrong:

> --8<---------------cut here---------------start------------->8---
> (ffi-within-renderer-thread *browser*
>  (lambda ()
>   (setf *renderer-thread* (bt:current-thread))))
> --8<---------------cut here---------------end--------------->8---

since we modify ffi-within-renderer-thread.  Instead we should

--8<---------------cut here---------------start------------->8---
(gtk:within-gtk-thread
    (lambda ()
      (setf *renderer-thread* (bt:current-thread))))
--8<---------------cut here---------------end--------------->8---

**Comment by jmercouris** [comment]
I don't see why that should not work. Though GUI thread semantics have bitten me in the past... :-D

**Comment by Ambrevar** [comment]
Progress: I managed to start Nyxt and get the session restore prompt.
Every else fails after that, the web view is blank.

There is hope :)

**Comment by Ambrevar** [comment]
Progress!  This branch works for most things: loading pages, new windows, minibuffer inputs, history, hinting, etc.

Left to do:

- Pasting hangs again.
- web-mode's nyxt:on-signal-load-finished is supposed to unzoom, but when it does it hangs the browser.  Not sure why.

@jmercouris Can you test again on macOS?  You might have to play with the ffi-initialize and finalize functions to set up the threading properly on macOS.

On GNU/Linux, I run the startup-function in a chanl thread, _not_ in the GTK thread.  This is because the startup function, like any command, can prompt the minibuffer which is a blocking operation, so it cannot be done from the GTK thread otherwise it would hang the browser.

**Comment by jmercouris** [comment]
No luck, no window, I will play around with it.

**Comment by Ambrevar** [comment]
Continuing in #977.

**Pull request closed without merging**
