### PR TITLE
WIP: Headless mode with prompt buffer tests

### PR DESCRIPTION
**Pull request by Ambrevar**
This is a draft that shows how we can implement headless mode (see #1168) and makes use of this feature to test:

- The renderer;
- The interactive prompt buffer.

And it works!

A few points to address:

- "set-url" hangs on and off at `prompter:all-ready-p`.  Race condition?
- We need to add a few event signals, like:
  - when Nyxt is started and ready for interactions;
  - when URL is done loading (we already have this via methods, maybe tests could just add a default-mode to the tested buffer).
 
Thoughts?

### CODE REVIEW

**Comment by Ambrevar** [comment]
Also try in a TTY, without X / Wayland.

**Comment by aartaka** [comment]
What's the status of this PR?

**Comment by Ambrevar** [comment]
Still very high priority in my opinion!

I haven't found the time to work on it, hopefully I can get back to it
soon.
Unless someone beats me to it ;)

**Comment by aartaka** [comment]
Closing in favor of #2054 (rebase).

**Pull request closed without merging**
