### PR TITLE
Fix storage concurrency

### PR DESCRIPTION
**Pull request by Ambrevar**
This fixes the tests on master.

I'd like to call for a review of commits https://github.com/atlas-engineer/nyxt/commit/54876dfc4b9d010f667b4241c723c9907de6d923 to https://github.com/atlas-engineer/nyxt/commit/6d8bf888648ffce6b071e6048a2faa1c33d220b7.

@jmercouris @aartaka

### CODE REVIEW

**Comment by aartaka** [comment]
Maybe unrelated, but I just got this error when closing REPL-started `master`:
```
Interrupt thread failed: thread #<THREAD "Nyxt async-data-path worker" ABORTED {101085F153}> has exited.
   [Condition of type SB-THREAD:INTERRUPT-THREAD-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "Nyxt anonymous thread" RUNNING {101397D6A3}>)

Backtrace:
 0: (SB-THREAD:INTERRUPT-THREAD #<SB-THREAD:THREAD "Nyxt async-data-path worker" ABORTED {101085F153}> #<FUNCTION (LAMBDA NIL :IN SB-THREAD:TERMINATE-THREAD) {532019FB}>)
 1: (NYXT:QUIT)
      [No Locals]
 2: ((LAMBDA NIL :IN NYXT::RUN-ASYNC))
      Locals:
        NYXT::OLD-%BUFFER#1 = NIL
 3: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
      [No Locals]
 4: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 5: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-THREAD::RUN))
 6: ((FLET SB-UNIX::BODY :IN SB-THREAD::RUN))
 7: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::RUN))
 8: (SB-THREAD::RUN)
 9: ("foreign function: call_into_lisp")
10: ("foreign function: funcall1")
```

**Comment by jmercouris** [comment]
Interesting that the cache is just a lockable hash table suited for concurrent environments. I think you could generalize this idea and have a `lockable` class, and then different data structures that inherit from it. A `cache` is not likely to be the last locakable data structure we need. What do you think?

**Comment by Ambrevar** [comment]
@aartaka It's https://github.com/atlas-engineer/nyxt/commit/6d8bf888648ffce6b071e6048a2faa1c33d220b7.

I can't reproduce.  Can you?

**Comment by Ambrevar** [comment]
See https://github.com/atlas-engineer/nyxt/issues/1525.

**Pull request closed without merging**
