### PR TITLE
Fail safe profile

### LINKED ISSUE #2386: Add "noload" profile
In some cases and in particular for testing it's useful to ask Nyxt to not load any file from disk to ensure reproducible behaviour.

We often do `nyxt --no-config` but it's not enough: there is also the auto-config, the history, the bookmarks, and potentially more.

Wouldn't be nice to have a single knob to disable all file reads?  Actually, we can already programmatically do it by adding a profile which does just that.  

Since we have `nosave` already, I suggest we add `noload`.  Then it be enough to call

```lisp
nyxt --profile noload
```

to disable all file loads.

Should `noload` also disable file writes?  I would say yes, since it's not very intuitive to be "write only".

Thoughts?

### PR DESCRIPTION
**Pull request by Ambrevar**
# Description

This adds a long overdue `failsafe` command line parameter which should easily allow users to start Nyxt regardless of the their config, history, etc.

Fixes #2386.
Also addresses https://github.com/atlas-engineer/nyxt/issues/2535#issuecomment-1236731207

# Discussion

- Should `--failsafe` really modify the `*options*` values?  It makes for short code, but technically we lose "integrity" in the `*options*` variable.

- Do you like the `nofile-profile` name?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
> * Should `--failsafe` really modify the `*options*` values?  It makes for short code, but technically we lose "integrity" in the `*options*` variable.

Hmmmm. This may be a radical suggestion, but still: what it we propagate CLI options not through the `*options*` global variable, but through function arguments. This way we can solve the problem of `:failsafe` modifying too much global state (by altering the _values passed to functions_, instead of the global variable), and have our startup sequence to retain much more information in e.g., backtraces.

But this gotta be a huge refactoring, so I'm not sure it's worth it.

> * Do you like the `nofile-profile` name?

Sounds rhyming and fun :D But then, it's too easy to confuse with `nosave` one—they both seem to play with the filesystem jargon. So maybe use something more radical, like `null-profile` or `empty-profile`?

But naming things is definitely one of the hardest problems in computing :D

**Comment by Ambrevar** [comment]
> what it we propagate CLI options not through the `*options*` global variable, but through function arguments.

Example?

> they both seem to play with the filesystem jargon.

That's exactly what they do, so it's a good thing they sound related, no?

> like `null-profile` or `empty-profile`?

I find this actually more confusing, especially to non-programmers.

**Comment by aartaka** [comment]
For example, the `:no-socket` CLI option is used in `start-browser`. We can rewrite it as a keyword argument, like so
``` lisp
(defun start-browser (url-strings &key no-socket) ... 
```
and then call it in `start`, like so:
``` lisp
...
      (t
       (with-protect ("Error: ~a" :condition)
         (start-browser urls :no-socket no-socket))))
    (unless *run-from-repl-p* (uiop:quit))))
```
instead of getting it from the global variable.

**Comment by Ambrevar** [comment]
We cannot do this because any piece of code may want to access the options.  Try grepping `*options*`: it's scattered throughout the code base.

Having global access is very useful in this case.

**Comment by Ambrevar** [comment]
OK to merge?

**Comment by aadcg** [comment]
Let me test it.

**Comment by aadcg** [comment]
Ok to merge!

**Pull request merged**
