### PR TITLE
Documentation use `command-docstring-first-sentence` on tutorial

### PR DESCRIPTION
**Pull request by pdelfino**
The macro `command-docstring-first-sentence`  was already being used in the newer sections in tutorial. Some old sections were not using it, though. There were ad-hoc explanations about the commands. Almost always, the description would be really similar to the first sentence in the commands docstring. I just inserted the `command-docstring-first-sentence` so that things are more dynamic.

As I was doing this, on a few rare occasions the ad-hoc explanation on tutorial was actually better (IMHO) than the docstring. Thus, I inserted `command-docstring-first-sentence` **and** changed the docstring to have the better description version.

I also noticed a few rare mistakes that were fixed.

I was unsure on how to treat this considering commit frequency. One commit for each insertion of  `command-docstring-first-sentence` would be too much for master, I guess. So, I did 1 commit for each section changed. Enough atomic, I guess.

### CODE REVIEW

**Comment by jmercouris** [comment]
This pattern:

```
(:li (command-markup 'switch-buffer) ": " (command-docstring-first-sentence 'switch-buffer))
```

is repeating itself in the code endlessly, command-markup and then command-docstring separated by a colon. Perhaps we could use a macro for this? Something like:

(list-commands '(switch-buffer delete-buffer ...)) and it would generate all of the forms?

**Comment by jmercouris** [comment]
Thank you!

**Comment by pdelfino** [comment]
> This pattern:
> 
> ```
> (:li (command-markup 'switch-buffer) ": " (command-docstring-first-sentence 'switch-buffer))
> ```
> 
> is repeating itself in the code endlessly, command-markup and then command-docstring separated by a colon. Perhaps we could use a macro for this? Something like:
> 
> (list-commands '(switch-buffer delete-buffer ...)) and it would generate all of the forms?

Makes total sense. I wished I had realized this before doing it manually :sweat_smile:

I will work on that macro soon and submit a PR. Hopefully, today :)

**Comment by jmercouris** [comment]
Sometimes one must do it manually to realize said macro could exist :-)

**Pull request merged**
