### PR TITLE
Refactor tabs UI

### PR DESCRIPTION
**Pull request by aadcg**
# Description

A follow up to #2843, featuring a sensible branch name and rebased on top of the new theme changes.

# Discussion

There may be some minor topics left to discussion that were started in #2843.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [x] ASDF dependencies,
  - [x] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [x] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [ ] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - [x] My changes generate no new warnings.
  - [x] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aadcg** [comment]
@jmercouris I don't know what you did in the mean time, but the jittering that I noticed in the tab bar when switching buffers is no longer present! Good.

In short, I think this is ready to be merged. It's actually a huge improvement over what we have in place.

The only big issue that we currently have is how we deal with the fact that we run out of space:




Would you mind if I squash some commits and merge this?

**Comment by jmercouris** [comment]
I would not mind, please feel free to merge!

**Comment by aadcg** [comment]
I'll let everyone know when this will be ready for review. Tomorrow I'm pushing a more polished set of commits.

**Comment by jmercouris** [comment]
I look forward to it, thank you :-)

**Comment by jmercouris** [comment]
@aartaka 

I understand that the Theme colors are under contest right now. Let us still proceed with, and merge this.

If/when we arrive to a consensus about a better way to do the colors/interface for those elements, we will append/edit the source code with subsequent commits.

Let us not obsess over a perfect Git history in which we have made no revisions to prior designs, it greatly sabotages our inertia!

OK?

**Comment by aadcg** [comment]
@jmercouris I've radically changed the set of commits and its messages. The overall diff stays the same (obviously). I think you'd agree that this set of commits makes it easier on the reviewer and also on each of us that someday may study these changes.

**Comment by aadcg** [comment]
@jmercouris, I've studied your changes a bit deeper and we need to rethink commit bd7088716. When deleting a tab the prompt should not ask whether all buffers should be deleted. Rather, the prompt should list all buffers associated with that tab, and ask the user to mark those that he wishes to delete.

Notice that, as it stands in your implementation, there's no way for the user to understand whether he's deleting a single buffer (when there's a single one with that domain) or several of them.

Could you push a commit making this change? It should be easy.

**Comment by aartaka** [comment]
> I understand that the Theme colors are under contest right now. Let us still proceed with, and merge this.

No. There's nothing more permanent than the temporary, so let's not rush and add something possibly revertable in the first place. We're not in a hurry and are able to consider things thoroughly, are we?

> If/when we arrive to a consensus about a better way to do the colors/interface for those elements, we will append/edit the source code with subsequent commits.

Well, there are other options that can work even without adding a new color:

### Using a mere primary color:
``` diff
modified   source/buffer.lisp
@@ -806,8 +806,8 @@ store them somewhere and `ffi-buffer-delete' them once done."))
             `("#tabs::-webkit-scrollbar"
               :display "none")
             `(".tab"
-              :background-color ,theme:background-alternate
-              :color ,theme:on-background-alternate
+              :background-color ,theme:primary
+              :color ,theme:on-primary
               :opacity 0.6
               :display "inline-block"
               :margin-top "1px"
```

primary-hovered
primary-unhovered

### Using borders (obviously broken due to `clip-path` magic):
border-hover
border-nohover


### Relying on our arrows (not perfect, but you've got the idea: reusing the arrow overlaps):
``` diff
modified   source/buffer.lisp
@@ -806,8 +806,8 @@ store them somewhere and `ffi-buffer-delete' them once done."))
             `("#tabs::-webkit-scrollbar"
               :display "none")
             `(".tab"
-              :background-color ,theme:background-alternate
-              :color ,theme:on-background-alternate
+              :background-color ,theme:primary
+              :color ,theme:on-primary
               :opacity 0.6
               :display "inline-block"
               :margin-top "1px"
@@ -816,11 +816,8 @@ store them somewhere and `ffi-buffer-delete' them once done."))
               :margin-right "-8px"
               :margin-left "-9px"
               :text-decoration "transparent"
-              :border "transparent"
-              :border-radius "1px"
               :font "inherit"
-              :outline "inherit"
-              :clip-path "polygon(20px 0%, 100% 0%, calc(100% - 20px) 100%, 0% 100%)")
+              :outline "inherit")
             `(".tab:hover"
               :opacity 0.8
               :cursor "pointer")
modified   source/status.lisp
@@ -149,6 +149,7 @@ the URL.)"
                                    (quri:uri-domain url))
                           "plain tab"
                           "tab")
+               :class "arrow-right"
                :onclick (ps:ps
                           (if (or (= (ps:chain window event which) 2)
                                   (= (ps:chain window event which) 4))
```
arrown-nohover
arrows-hover

Out of those, I like primary color one the most, because it _looks like_ a different color, while still being a part of our theme. Win-win, right?

**Comment by aadcg** [comment]
@jmercouris this PR was again merged incorrectly (take a look at the git log). Please remind me to teach you how to do it in our next call. You're just missing the fact that you need to rebase the branch onto the target branch (master) before the merge.

In the meantime, please ask me to merge :)

**Comment by jmercouris** [comment]
Damn and I thought I had had it right!

OK, so a merge commit, but rebase before I do the merge commit!

Next time I will get it right! ay yai yai...! sorry!

**Comment by aadcg** [comment]
> OK, so a merge commit, but rebase before I do the merge commit!

Right, as you would do if you were merging a single commit! You always want to make sure that you rebase over the target branch right before the merge!

No worries :)

**Pull request merged**
