### PR TITLE
Keepassxc yubikey support

### LINKED ISSUE #2111: Support using hardware security keys with KeePassXC
**Is your feature request related to a problem? Please describe.**
I use a hardware security key with my KeePassXC database. However, I cannot seem to open it using Nyxt's password manager commands. Instead, I am prompted for a password file, which I do not have set on my database.

**Describe the solution you'd like**
I would like to be able to use my hardware security key to open my KeePassXC database so that I can take advantage of Nyxt's KeePassXC integration.

**Describe alternatives you've considered**
I could remove the security key from my KeepassXC database, but I would like to avoid that.
I could just manually open KeepassXC and manually copy-paste login information, which I currently do, but this is inconvenient.

**Additional context**
No additional context.

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This adds Yubikey support to our KeePass password interface and makes our interface completion logic a bit more flexible to different invariants of KeePass database locking mechanisms.

Fixes #2111

# Discussion

@Anomalocaridid, does that work for you?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [X] I've added the new dependencies as:
  - [X] ASDF dependencies,
  - [X] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [X] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - [X] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [x] I have updated the existing documentation to match my changes.
  - [X] I have commented my code in hard-to-understand areas.
  - [X] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [X] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [X] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [X] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [X] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Anomalocaridid** [comment]
@aartaka, this works for me. However, there are a few small, but annoying issues:

- It prompts for the Yubikey slot every time I copy a password, but there should be no need to because I used your snippet from the manual to set it.
- It also prompts for the key file every time I copy a password, but I do not use a key file and I am not quite sure what I need to put in my config to get it to stop doing that.
- There is no indication that I am supposed to tap my Yubikey when I am supposed to. It just prompts for the password again, which disappears after I tap my Yubikey. My Yubikey still lights up to indicate it is being queried, though, so I can just look at it to check when I need to tap it. I would not consider this a blocking issue, but it would still be nice to have some sort of indicator.

**Comment by aartaka** [comment]
> * It prompts for the Yubikey slot every time I copy a password, but there should be no need to because I used your snippet from the manual to set it.

Indeed, that was my sloppy prototyping that didn't consider the already set values. Fixed in 3aa5567de8b0a3eecc9d6326050c74ba4a0d8770.

> * It also prompts for the key file every time I copy a password, but I do not use a key file and I am not quite sure what I need to put in my config to get it to stop doing that.

Fixed in 3aa5567de8b0a3eecc9d6326050c74ba4a0d8770 too (★^O^★)

> * There is no indication that I am supposed to tap my Yubikey when I am supposed to. It just prompts for the password again, which disappears after I tap my Yubikey. My Yubikey still lights up to indicate it is being queried, though, so I can just look at it to check when I need to tap it. I would not consider this a blocking issue, but it would still be nice to have some sort of indicator.

Right, that's wasn't an obvious one. Fixed in 3aa5567de8b0a3eecc9d6326050c74ba4a0d8770 with the help of d886953a7eabbf2aa751b2e036ef5b4bc78e3a3c. Can you test it now to see whether it all works fine?

> By the way, thanks a lot for implementing this!

You're welcome (´ ▽｀).。ｏ♡

**Comment by Anomalocaridid** [comment]
It no longer prompts me for the yubikey slot, and it now only prompts once for the key file. However, there are still some issues:

- I still cannot see any way to make it not prompt me for the key file at all.
- For some reason, I have to tap my Yubikey before I get prompted for anything as well as after I enter my database password. This does not occur if I run Nyxt with `--no-config`
- The prompt to tap my Yubikey does not appear after entering my database password.

**Comment by aartaka** [comment]
> * I still cannot see any way to make it not prompt me for the key file at all.

Yeah, that seems to be the best we can do: if KeePassXC DB is not yet unlocked, we have to go through all the options, including the key file.

> * For some reason, I have to tap my Yubikey before I get prompted for anything as well as after I enter my database password. This does not occur if I run Nyxt with `--no-config`
> * The prompt to tap my Yubikey does not appear after entering my database password.

Right, it was a silly typo of mine. Fixed in 7818b75a42ef2930658ca353f85e047b592b264b, can you test? Sorry for this back-and-forth—I would've tested it myself if I had a Yubikey, but well（*/∇＼*）

**Comment by Anomalocaridid** [comment]
> Yeah, that seems to be the best we can do: if KeePassXC DB is not yet unlocked, we have to go through all the options, including the key file.

Unfortunate, but understandable.

> Right, it was a silly typo of mine. Fixed in https://github.com/atlas-engineer/nyxt/commit/7818b75a42ef2930658ca353f85e047b592b264b, can you test?

I can see the prompt to tap my Yubikey now, but I still keep getting prompted to tap it before everything else, as well as at the end. It seems that removing the configuration snippet from my config and manually entering the password file and Yubikey slot prevents this, but I am not sure if the issue is on my end or your end. Here's the exact code I used to configure the KeepassXC integration in case it would help:

```lisp
(defmethod initialize-instance :after
           ((interface password:keepassxc-interface)
            &key &allow-other-keys)
  (setf (password:password-file interface) "/home/anomalocaris/Sync/Keepass Databases/Personal.kdbx"
        (password:yubikey-slot interface) "2"))

(define-configuration nyxt/password-mode:password-mode
  ((nyxt/password-mode:password-interface
    (make-instance 'password:keepassxc-interface))))
```

> Sorry for this back-and-forth—I would've tested it myself if I had a Yubikey, but well（/∇＼）

It's no problem at all. I'm happy to help.

**Comment by aartaka** [comment]
> I can see the prompt to tap my Yubikey now, but I still keep getting prompted to tap it before everything else, as well as at the end. It seems that removing the configuration snippet from my config and manually entering the password file and Yubikey slot prevents this, but I am not sure if the issue is on my end or your end. 

That's a restriction of the way we interface with the password managers—we often check them to make sure credentials are right. Which, with Yubikey support, implies you may need to tap it more than once per `copy-password`. Not much we can fix here, unfortunately :(

The best we can do in this situation is clarify the Yubikey prompt text. Is it clear enough now, or does it need some improvement? Any suggestions (CC @aadcg, @lansingthomas)?

@Anomalocaridid, if you're okay with things as they are (no fix for the occasional double tapping until a major refactor of `libraries/password-manager`, unfortunately), then I can merge as-is :)

**Comment by Anomalocaridid** [comment]
@aartaka Unfortunate, but understandable. I think everything is fine as it currently is. I did not see any other issues trying out your changes.

**Comment by aartaka** [comment]
@Anomalocaridid, thanks for your help and feedback! Yubikey support is in :D

**Comment by Anomalocaridid** [comment]
@aartaka No problem! I'm glad I could help!

**Pull request merged**
