### PR TITLE
Highlight functions and variables in :ncode blocks.

### LINKED ISSUE #1480: Add syntax highlighting for code examples
This is just a suggestion but you could use a library like this:
https://prismjs.com/
To add Common Lisp syntax highlighting :+1:

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This adds a rudimentary syntax highlighting to all our :ncode blocks, which means: all code examples in `manual` and `describe-*` pages. This is a prototype, but a working one (see screenshots below).

highlight-simple
highlight-complex

Fixes #1480.

At this stage I'm interested in what all y'all have to say about this. Am I going the right way here? @aadcg, @jmercouris, @Ambrevar.

# Discussion

- [ ] I don't like that `let`-bindings are highlighted as functions, due to primitiveness of the code walker (`resolve-linkable-symbols`). We have to fix that. Anyone aware of some package/CL function that gets us to the body of the macro/special form, ignoring the arguments/bindings/special symbols? Swank should have something like that, but I can't find it. How does SLY do syntax highlighting then?
- [ ] This change introduces a lot of compile-time computations. On my machine, this slow the compilation from 7 seconds to 20 seconds. I'm pretty sure we can optimize it, and I believe we _have to_. How can we speed this thing up? Maybe shift to regexps somewhere?
 
# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [X] I've added the new dependencies as:
  - [X] ASDF dependencies,
  - [X] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [X] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - [X] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [X] I have updated the existing documentation to match my changes.
  - [X] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [X] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [X] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [X] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [X] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
Look! It highlights special forms now (`progn` needs more love, yes) ＼(^▽^＠)ノ

special-form-highlight

**Comment by aartaka** [comment]
Okay, now I'm fully satisfied with what's there:
- Highlighting of:
  -  Functions.
  - Variables.
  - Macros.
  - (and, separately, in accent color) CL special forms!
  - we might do something special with classes here, but let's first discuss what's there.
- Links to relevant documentation.
- Slow-down of complication from 7 seconds to 17 seconds (yes, I've sped it up some, but help won't hurt).

**Comment by Ambrevar** [comment]
It's impressive work!

But before we get down to further discussion, the original issue #1480 mentioned https://prismjs.com/, which may already contain a CL highlighter.

There are also pure CL libraries like https://github.com/kingcons/colorize.

**Comment by aartaka** [comment]
> But before we get down to further discussion, the original issue #1480 mentioned https://prismjs.com/, which may already contain a CL highlighter.

Indeed, PrismJS has CL highlighting, but we agreed to not include any JS into Nyxt distribution unless strictly necessary. In our case, it's not strictly necessary at all, as compiler/language gives us enough leverage for even a more meaningful highlighting than PrismJS can ever give.

> There are also pure CL libraries like https://github.com/kingcons/colorize.

Right, this one is good in being a Lisp library. But still, it's the same paradygm as PrismJS: it treats the code as a mere text, a mere thing to colorize based on pre-set rules and sets of symbols. It links ANSI CL symbols to CLHS, but no more linking/interactiveness beyond that.

This PR is different in that it inspects the image to infer the highlighting information. Importantly, it distinguishes functions, macros, and special forms from each other, and may thus highlight them differently. It also provides links to all the functions/macros used in the given code. This approach is quite demanding on compiler/distribution, but we're hard-set on making Nyxt a self-introspecting program anyway, so it should be more than relevant.

**Comment by Ambrevar** [comment]
OK, thanks for investigating.

That said, aren't there any other library that do just that?
Actually what about Swank / Slynk?  To do offer some symbol analysis.

**Comment by aadcg** [comment]
Do we want to have links in code snippets?

**Comment by aartaka** [comment]
> Do we want to have links in code snippets?

Yes, because those allow to immediately look at the docs/sources of the function/macro/whatever used in the code. 

And links are so nice and fidgety as code highlighting elements too :P

**Comment by aartaka** [comment]
So I've enabled code highlighting in `describe-*` pages and enabled class highlighting. Seems quite mergeable to me. Anyone willing to test?

**Comment by jmercouris** [comment]
I can test if you ping me on email :-D otherwise i may forget!

**Comment by jmercouris** [comment]
I did test, and it is fucking awesome! I did encounter a bug though :-O. Can't do `try in repl`. Any ideas?

**Comment by aartaka** [comment]
> Can't do `try in repl`. Any ideas?

Fixed on master and rebased here. Shoud be fixed now, it the error you're (not) referring to is the same as mine :)

**Comment by jmercouris** [comment]
Well, I fixed the bug that I encountered :-)

**Comment by aartaka** [comment]
Yep, I allowed myself a liberty to edit it some.

Need to refactor the whole macro before merging (is it OK to merge then?)

**Comment by jmercouris** [comment]
It is OK :-)

**Comment by jmercouris** [comment]
Feel free to refactor the macro on master, that is orthogonal to this PR, this PR is OK to merge, thus I merged :-D

**Comment by aadcg** [comment]
@jmercouris, you didn't merge this according to our standards - it should have been merged with a merge commit. This is extremely important.
[
See the instructions](https://github.com/atlas-engineer/nyxt/tree/master/documents#branch-management). 

Also, the commits should probably have been squashed.

**Comment by jmercouris** [comment]
Sorry Andre, I had totally forgotten about this. Old habits!

**Comment by aadcg** [comment]
No big deal, thanks.

**Pull request merged**
