### PR TITLE
check SBCL version

### PR DESCRIPTION
**Pull request by phil-hands**
I can imagine that one could make this slightly neater using make rather than shell for the test and conditional, but this does work as it is.

### CODE REVIEW

**Comment by jmercouris** [comment]
Thank you! It looks/works good on my system. I would like @Ambrevar to confirm it works on his system before merging.

**Comment by Ambrevar** [comment]
As per the developer's readme, we support SBCL 1.4.2.
Some reported that it does not work with SBCL <=2.0.0, I wonder if this can be confirmed.

Also intead of parsing the SBCL output, we could run

```sh
sbcl --no-userinit --non-interactive --eval '(assert-version->= 1 4 2)'
```

**Comment by jmercouris** [comment]
Phil just had problems on that version, so it doesn't support something we are doing.

**Comment by Ambrevar** [comment]
Which version? 1.4.2?

**Comment by jmercouris** [comment]
1.4.16, maybe 1.4.2 is still OK.

**Comment by phil-hands** [comment]
I was running the version that is in Debian stable, the changelog for which is here:

  https://metadata.ftp-master.debian.org/changelogs//main/s/sbcl/sbcl_1.4.16-2_changelog

**Comment by Ambrevar** [comment]
Thanks.  I'll try to fix Nyxt for 1.4.16 when I find the time.

**Comment by jmercouris** [comment]
In the meantime shall we not apply this patch to prevent people from compiling with a version which does not work?

**Comment by Ambrevar** [comment]
No, let's use the line I suggested instead, it's simpler, shorter, more reliable.

**Comment by Ambrevar** [comment]
Done in a23a2124e18ed71168398028fb4284b06d16a144.
Thanks for reporting!

**Pull request closed without merging**
