### PR TITLE
Format modes status bar glyph support

### PR DESCRIPTION
**Pull request by jmercouris**
Add glyph presentation support for status buffers. This is a feature requested by a few users.
Also:

+ whether a mode is visible or not is within its own configuration
+ the glyph of a mode is defined within its own configuration
+ whether a status buffer uses glyphs or full names is defined within a status-buffer configuration

### CODE REVIEW

**Comment by jmercouris** [comment]
If you follow the commits in order, it is pretty straightforward :-)

**Comment by aartaka** [comment]
Looks all good to me :)

**Comment by jmercouris** [comment]
Voila!

**Comment by aartaka** [comment]
Oh, wait a second! I've used it in my initfile, and debugger complains about the unexported symbols for `glyph` accessor 0_o

**Comment by jmercouris** [comment]
Works for me...

**Comment by jmercouris** [comment]
I did '(define-configuration Nyxt/emacs-mode:emacs-mode 
((Glyph "!")))'

**Comment by jmercouris** [comment]
What did you try? Do we need to maybe export glyph or something somewhere?

**Comment by aartaka** [comment]
Forget it -- I had a poor reimplementation of glyphs in my init file conflicting with it xD

**Pull request merged**
