### PR TITLE
Remove osicat

### PR DESCRIPTION
**Pull request by Ambrevar**
This specializes some code to use SBCL extensions instead of Osicat.  It still falls back to Osicat when not using SBCL.

 This allows us to get rid of Osicat, which is a bit harder to package than the rest because the `.so` is generated within the Osicat package.

@jmercouris Can you test to make sure I didn't break it for you?

### CODE REVIEW

**Comment by jmercouris** [comment]
I can't really test on macOS anymore. I wonder if we should make a 'trivial-readlink' library... do you think it is justified?

**Comment by Ambrevar** [comment]
Too trivial maybe.
What about adding it to file-attributes?  We can ask upstream.

**Comment by Ambrevar** [comment]
Why can't you test on macOS?
If we can't, shall we drop official support then?

**Comment by jmercouris** [comment]
I don't have my macbook anymore. We should consider dropping official support yes. Just getting Nyxt to run on there is a huge challenge in of itself..

**Comment by Ambrevar** [comment]
Wanna send a patch to update the doc then? :p

**Comment by jmercouris** [comment]
Maybe... I'm still not sold on dropping support. Nyxt /should/ continue to work on macOS.

**Comment by Ambrevar** [comment]
I'm confused.  Are you saying you changed your mind after the previous
comment and want to keep macOS support?

If so, how?

**Comment by jmercouris** [comment]
I'm saying we don't need to drop it if it ain't broken 🙃

**Comment by Ambrevar** [comment]
I meant updating the documentation / home page to mention that macOS is
not tested or something like that.

**Comment by jmercouris** [comment]
OK, I can do that.

**Comment by Ambrevar** [comment]
Shall we merge this then?

**Comment by jmercouris** [comment]
Yes

**Comment by jmercouris** [comment]
thank you!

**Pull request merged**
