### PR TITLE
documents/README: add section for beginners

### PR DESCRIPTION
**Pull request by hgluka**
# Description

Add a section to the Developer's Manual in documents/README.org that details a way to run Nyxt from source with SBCL, Guix, Emacs and SLY. 

This was motivated by a talk with @aadcg last week. Essentially, as someone new to Common Lisp and Emacs and Guix, I don't think that I would've been able to get started as quickly on my own, with just that manual for help. That's why I wrote down what we did to get everything working in under an hour. This will hopefully help/encourage newcomers that want to start contributing.

# Discussion

I'm not 100% sure about the section title and placement in the file. I put it at the top so that people don't miss it, but maybe there's a better place.
I've tested the instructions in a brand new virtual machine and there are no missing steps or mistakes in that sense, but let me know if there are any stylistic errors in there.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] Git hygiene:
  - I have pulled from master before submitting this PR
  - There are no merge conflicts.
- [x] I've added the new dependencies as:
  - ASDF dependencies,
  - Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - I have updated the existing documentation to match my changes.
  - I have commented my code in hard-to-understand areas.
  - I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
    - Changelog update should be a separate commit.
  - I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - My changes generate no new warnings.
  - I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - I ran the tests locally (`(asdf:test-system :nyxt)` and `(asdf:test-system :nyxt/gi-gtk)`) and they pass.

### CODE REVIEW

**Comment by Ambrevar** [comment]
I agree with the overall direction.

People already using Quicklisp should be knowledgeable enough to hack a setup themselves.

**Comment by hgluka** [comment]
I can take a crack at it, no problem. The branch name `hgluka:add-readme-section` is a bit unfortunate if this is going to turn into a bigger rewrite. Maybe I should close this PR and open a new one?

**Comment by jmercouris** [comment]
@hgluka I am merging this, I can create an issue about it, and if you want to do it feel free. But I will make the changes to the document as necessary, this is already a good start!

**Comment by jmercouris** [comment]
See here for more detail: https://github.com/atlas-engineer/nyxt/issues/3068

**Pull request closed without merging**
