### PR TITLE
Refactor set url

### LINKED ISSUE #3349: set-url: entering url without http(s):// prefix no longer works v3.11.3
**Describe the bug**
Typing fqdn in set-url (github.com / google.com/etc) without http(s):// prefix no longer takes you to the direct url, instead shows search results. 

Issue occurs in Nyxt 3.11.3. Works properly in ≤3.11.2

**Precise recipe to reproduce the issue**

1. Run set url command (o in vi mode)
2. type github.com > enter
3. Takes you to search results instead of https://github.com

**Information**
- OS name+version: 
gentoo 
- Graphics card and driver:
- Desktop environment / Window manager name+version: 
dwl
- How you installed Nyxt (Guix pack, package manager, build from source):
source
- Information from `show-system-information`:
Nyxt version: 3.11.3
Renderer: GI-GTK
Operating system kernel: Linux 6.7.6-gentoo
Lisp implementation: SBCL 2.4.1 (Dynamic space size: 3221225472)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-3.11 :NYXT-3 :NYXT-3.11.3
 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :SBCL+SAFE-STANDARD-READTABLE :NAMED-READTABLES :GLOBAL-VARS
 :CL-FAD :LPARALLEL :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE
 :CL-UNICODE :CL-JSON-DOUBLE-FLOAT-IS-SUBSUMED
 :CL-JSON-SINGLE-FLOAT-IS-SUBSUMED :CHUNGA :FLEXI-STREAMS :CL-PPCRE :WEBKIT2
 :WEBKIT-2.42.5 :WEBKIT-2.42 :WEBKIT-2 :WEBKIT2-CORS-ALLOWLIST
 :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING :WEBKIT2-MUTE :WEBKIT2-EMOJI
 :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22 :GTK-3-20 :GTK-3-18 :GTK-3-16
 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6 :GTK-3-4 :GTK :GDK-3-22
 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12 :GDK-3-10 :GDK-3-8 :GDK-3-6
 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF :CLOSER-MOP :GLIB-2-30 :GLIB-2-32
 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46
 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54 :GLIB-2-56 :GLIB-2-58 :GLIB
 :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2 :LPARALLEL.WITH-CAS
 :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :COMMON-LISP :ELF :IEEE-FLOATING-POINT :LINUX :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)

### PR DESCRIPTION
**Pull request by aadcg**
# Description

Fixes #3349

The CI fails but it is unrelated to this PR.

# Checklist:

- [x] Git branch state is mergable.
- [x] Changelog is up to date (via a separate commit).
- [x] New dependencies are accounted for.
- [x] Documentation is up to date.
- [x] Compilation and tests (`(asdf:test-system :nyxt/gi-gtk)`)
  - No new compilation warnings.
  - Tests are sufficient.

### CODE REVIEW

**Comment by odanoburu** [comment]
No freezes here. Thank you @aadcg !

**Review by jmercouris — APPROVED** [review]

**Comment by jmercouris** [comment]
I couldn't get it to freeze!

**Comment by fictitiousexistence** [comment]
@aadcg Just got around to testing. Seems to be functioning properly again. Thanks!

**Comment by fictitiousexistence** [comment]
@aadcg After using this for about a month I started to realize that using a direct ip instead of a hostname will take you to search results for that ip instead of trying http/https. An example ip: 146.190.62.39 (httpforever.com). 


Also it seems to go to search results if you enter a full url with a path ex:
httpforever.com/favicon.ico.

Thanks.

**Comment by aadcg** [comment]
@fictitiousexistence you are correct, but this has been the behavior all along. In other others, the topic you're raising is unrelated to this PR and I'd suggest opening an issue.

For a URL to be interpreted as an IP you need to input e.g. `http://192.168.0.1`. Note that in Firefox, while possible to input `192.168.0.1`, it is resolved internally to `http://192.168.0.1` (to prove it, copy from the address bar). It should be easy to implement this DWIM behavior in Nyxt.

**Pull request merged**
