### PR TITLE
Check keyschemes

### PR DESCRIPTION
**Pull request by aadcg**
# Description

This PR [addresses a comment](https://github.com/atlas-engineer/nyxt/pull/2685#discussion_r1046241480) that @Ambrevar made.

# Discussion

It's always good to have separate tests to check different functionality. But, since these modes are so simple, I added the check in the `toggle-mode` test. 

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [x] I have pulled from master before submitting this PR
- [x] There are no merge conflicts.
- [x] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [x] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [x] Documentation:
  - [x] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [x] I have updated the existing documentation to match my changes.
  - [x] I have commented my code in hard-to-understand areas.
  - [x] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [x] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [x] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [x] Compilation and tests:
  - [x] My changes generate no new warnings.
  - [x] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by aartaka — APPROVED** [review]

**Comment by aadcg** [comment]
@Ambrevar is this what you had in mind? OK to merge?

**Comment by Ambrevar** [comment]
Yes, thanks!

Can you also test that disabling the mode reverts back to the previous keyscheme?

**Comment by aadcg** [comment]
Good point! Take a final look.

OK to merge?

**Comment by Ambrevar** [comment]
Looks good to me, thanks!

**Comment by aadcg** [comment]
Thanks!

**Pull request merged**
