### PR TITLE
command-commands.lisp: execute extended command optional arguments

### PR DESCRIPTION
**Pull request by jmercouris**
further revisions should also consider key arguments

this is greatly simplified due to the new architecture!

### CODE REVIEW

**Comment by Ambrevar** [comment]
Wow! :)

**Comment by jmercouris** [comment]
I take it is OK to merge into your branch? :-D

**Comment by Ambrevar** [comment]
Wait, I'll do a complete clean up, no need to push a conflict just now! :)

**Comment by jmercouris** [comment]
OK!

**Comment by Ambrevar** [comment]
Don't you want to merge this afterwards?

**Comment by jmercouris** [comment]
I've saved it on my computer

**Comment by Ambrevar** [comment]
What do you mean?  Don't you want to add this feature upstream?

**Comment by jmercouris** [comment]
Yes, I will make a new commit, when synchronous minibuffer is merged to master, I have the change set still on my machine

**Comment by Ambrevar** [comment]
You can push to this branch, shouldn't be a problem.

**Pull request closed without merging**
