### PR TITLE
Empty action

### PR DESCRIPTION
**Pull request by Ambrevar**
This answers #1352.
In the end, I couldn't add a separate source because if there are marks in _any_ source, then all unmarked elements are ignored.
The action of unmarked elements is ignored.

Here I took another approach: add an action which discard the selection if there are no marks.  I've made sure that the prompt is explicit to the user.

Thoughts?

### CODE REVIEW

**Comment by aartaka** [comment]
I like this movement of `(funcall* return-function)` higher in the `hide-prompt-buffer`! Wanted this for a long time :)

Everything is fine, it seems.

**Comment by aartaka** [comment]
How about extracting `return-marks-only` to a top-level function and exporting it? Maybe make a function-maker. Then it can be used in much more contexts than the original (attributes choice) one.

**Comment by Ambrevar** [comment]
Good point, I'll try to extract it.

**Comment by Ambrevar** [comment]
Done and merged with 7c29efddb3fffadf75ddea734bd3a127216f2607.

**Comment by jmercouris** [comment]
Thank you!

**Pull request closed without merging**
