### PR TITLE
Refactor search buffer (Follow up to #2424)

### LINKED ISSUE #1169: search-buffer fails to return occurrences
Steps to reproduce:

- open [Nyxt's github page](https://github.com/atlas-engineer/nyxt)
- run `search-buffer`
- type "you are " (notice the last whitespace)

As soon as you type the last whitespace the search result vanishes. 

**Edit:** I understand that is due to its corresponding html page.  I wonder tho, why are there two whitespaces between "are" and "looking" if there's a single whitespace in the corresponding `.org` file?

And, more generally, is this an "uphill battle" that makes little sense to try to win?

### LINKED ISSUE #1204: Search-buffer performance
Say we're searching in a web buffer with tons of lines. Since that requires running JS, I understand that there's not much to do.  

But perhaps in those cases, we could treat the source of the page as text so that the search will be faster? There might be some overhead into fetching the text but it should compensate nonetheless. 

I bumped into this while [here](https://packages.ubuntu.com/focal/allpackages?format=txt.gz).

### LINKED ISSUE #1237: search lists duplicates
Recipe:

- Go to https://github.com/atlas-engineer/nyxt/pull/1211
- Search "conf"

"This branch has no conflicts " is listed twice, the first one is not visible.
Any clue what's going on?

### LINKED ISSUE #1555: Selecting `search-buffer` candidates doesn't bring them into focus on certain pages
- Go to https://github.com/ndwarshuis/org-ml/blob/master/docs/api-reference.md
- Call `search-buffer` and type "build"
- Candidates appear in the prompt-buffer, but selecting them doesn't bring them into focus.

Moreover, the order of search candidate ID's seems to be wrong:
- On the same page, search for "string"
- The "Secondary strings" candidate has ID 2 although it is not the second candidate.

It seems that internal links are displayed first.

### LINKED ISSUE #2504: Requiring 3 characters to search causes multilingual (CJK) problems
Requiring 3 characters to perform a search makes searching in some languages difficult.  CJK languages in particular have very dense writing—one- and two-character words are extremely common.

For instance, I was trying to find a way to insert a symbol into a TeX document for an _inkan_(印鑑)—one's official seal stamp in Japan, used similar to signatures in the West.  I need this for a document I'm going to be submitting to court.  I found a site that should have a solution, but the page is quite long, so I tried to C-s C-s "印鑑".  It took me a while to figure out what the problem was, because as soon as I'd finished inputting the character, I pressed "Enter", which closes the minibuffer (so I assumed it was a another multilingual input issue).

Is there a reason for the 3-character minimum?  Is there a way to override it?  I've never used a browser that required a minimum number of characters to search.

### PR DESCRIPTION
**Pull request by aadcg**
# Description

This PR follows the strategy started in #2424, but the implementation is completely new.

It fixes long standing issues, and goes beyond the features of the old `search-buffer` capabilities.

Closes #1204.
Closes #2504.
Closes #1555. 
Closes #1237.
Closes #1169.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [ ] I have pulled from master before submitting this PR
- [ ] There are no merge conflicts.
- [ ] I've added the new dependencies as:
  - [ ] ASDF dependencies,
  - [ ] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [ ] and Guix dependencies.
- [ ] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [ ] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [ ] Documentation:
  - [ ] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [ ] I have updated the existing documentation to match my changes.
  - [ ] I have commented my code in hard-to-understand areas.
  - [ ] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [ ] I have added a `migration.lisp` entry for all compatibility-breaking changes.
- [ ] Compilation and tests:
  - [ ] My changes generate no new warnings.
  - [ ] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aadcg** [comment]
@aartaka why do you set `input` to `(str:replace-all " " " " input)`?

**Comment by aadcg** [comment]
Note to self.

Abstract setting `input` to `(str:replace-all " " " " input)` into whitespace equivalence.

**Comment by aadcg** [comment]
@aartaka I don't understand the goal of `get-unique-selector` in `dom.lisp`, since all elements have unique Nyxt IDs. Could you explain?

**Comment by aartaka** [comment]
> @aartaka I don't understand the goal of `get-unique-selector` in `dom.lisp`, since all elements have unique Nyxt IDs. Could you explain?

Yes. So the problem with Nyxt IDs is: they're part of page state and can be flushed away anytime page changes. It rarely happens, but it's a risk notetheless.

To avoid this risk, we can use the structure of the DOM itself to mark its elements and to find them properly. This is what `get-unique-selector` tries to do—finding a DOM-specific information that uniquely identifies the element. 

It's neither complete nor error-free, but once rigorously checked and completed — it's an easy and reliable way forward towards Nyxt ID deprecation and a happy page interaction :)

**Comment by aadcg** [comment]
Artyom Bologov ***@***.***> writes:

> Yes. So the problem with Nyxt IDs is: they're part of page state and can
> be flushed away anytime page changes. It rarely happens, but it's a risk
> notetheless.

Ok, it makes sense now.  Thanks.

**Comment by aadcg** [comment]
[White smoke emerges from Sistine Chapel](https://www.youtube.com/watch?v=2SDOwgCKb1M&t=1561). The first prototype of the new search is out. 

Lots of work ahead. No need to review it yet. The curious ones can give it a try (@jmercouris)

**Comment by aadcg** [comment]
> Yes. So the problem with Nyxt IDs is: they're part of page state and can be flushed away anytime page changes. It rarely happens, but it's a risk notetheless.
> 
> To avoid this risk, we can use the structure of the DOM itself to mark its elements and to find them properly. This is what `get-unique-selector` tries to do—finding a DOM-specific information that uniquely identifies the element.
> 
> It's neither complete nor error-free, but once rigorously checked and completed — it's an easy and reliable way forward towards Nyxt ID deprecation and a happy page interaction :)

Nyxt IDs are indeed problematic. Everyone acknowledges and agree on that!

Still, the strategy of computing unique selectors is a concept that needs to be validated. Personally, I'm very skeptical. @jmercouris told me that he's sure that there are lots of shortcoming to that approach. I don't want to start a conversation on that topic here. Rather, I'm justifying why, in this PR, I'm using Nyxt IDs.

**Comment by aartaka** [comment]
Sure, not denying the usefulness of Nyxt IDs!

**Comment by aadcg** [comment]
The feature of highlighting matches that span multiple nodes is coming together! CC @jmercouris 

https://user-images.githubusercontent.com/45483512/224339108-1b0c467e-5e89-4da5-829a-330e521a342d.mp4

**Comment by jmercouris** [comment]
that problem has eluded us for years!

**Comment by aadcg** [comment]
Pushed an alpha version. **Not** ready for review.

**Comment by aadcg** [comment]
I think we're very close to having a new `search-buffer` mechanism that greatly improves the previous one.

I'm looking for beta testers who are eager to find bugs and corners cases. CC @jmercouris @Ambrevar @aartaka.

**I'm not looking for a code review**. I'm still looking for bugs, writing documentation and doing minor refactoring.

**Comment by jmercouris** [comment]
I've changed the animation, what do you think?

**Comment by jmercouris** [comment]
Original one was close, but I want it to be like a "sweeping" look if that makes sense!

**Comment by aadcg** [comment]
@jmercouris great idea, thanks! I've polished it a bit further.

**Comment by jmercouris** [comment]
Lol that's funny. I guess we could go from top to bottom, and it would solve that problem... wouldn't look nearly as cool. I suggest we just don't worry about it, it isn't really a breaking bug. What do you think?

**Comment by aadcg** [comment]
> I suggest we just don't worry about it, it isn't really a breaking bug. What do you think?

Seems sensible. We'll try to vertical animation together and evaluate the pros and cons.

The fact that a single match may correspond to several span elements was done intentionally. I tried for some time to have to have it always correspond to single span element in the edge cases (partially selected nodes) without success. While I can image how it could be done, I'm almost sure it would translate into much more code to maintain (both in size and complexity).

**Comment by aadcg** [comment]
Closed in favor of #2908.

**Pull request closed without merging**
