### PR TITLE
Refactor `:nselect`, `:nbutton`, `:ninput` for debuggability and maintainability

### PR DESCRIPTION
**Pull request by aartaka**
# Description

This continues the work of #2826 in making our tags more maintainable and splitting those into small runtime helpers (with the end goal of making them so self-sufficient that they can be moved to a separate library). This time, it's the refactoring of the interactive tags: our beloved `:nbutton` and less used `:nselect` and `:ninput`. Because of their interactive code-executing character, this PR is slightly more opinionated and needs more review.

# Discussion

You can see that all the uses of `:nbutton`, `:nselect`, and `:ninput` require quoted forms for execution. This is a significant change, so at least note that the syntax has changed. The syntax has changed for more transparency and less macro-wizardry, but it still has a certain learning curve (see the respective documentation and type declarations for reference on which values are accepted). In particular, closing over values requires either unquoting or inline closure creation. Examples:

mode/buffer-listing.lisp:
``` lisp
(:nbutton
 :text "Update ↺"
 :buffer panel-buffer
 `(reload-buffer
   (find
    ;; NOTE: unquoted:
    (render-url (url ,panel-buffer))
    (nyxt::panel-buffers (current-window))
    :test #'string=
    :key (compose
          #'render-url #'url))))
```

mode/repl.lisp:
``` lisp
(:nbutton
 :text "Edit Nyxt function"
 :title "Edit the source of one of Nyxt commands in REPL."
 ;; NOTE: Using closure here to capture repl-mode, because it's
 ;; mentioned in too much places. See `:nbutton' documentation.
 `(funcall
   ,#'(lambda ()
        (let ((functions (prompt :prompt "Function to edit"
                                 :sources (make-instance
                                           'nyxt::function-source
                                           :actions-on-return #'identity))))
          (setf (evaluations repl-mode)
                (append
                 (evaluations repl-mode)
                 (mapcar (lambda (sym)
                           (make-instance 'evaluation
                                          :input (function-lambda-string
                                                  (symbol-function sym))))
                         functions)))
          (reload-buffer (buffer repl-mode))))))
```

Does this look alright to you? @jmercouris, @aadcg?

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.

- [X] I have pulled from master before submitting this PR
- [X] There are no merge conflicts.
- [X] I've added the new dependencies as:
  - [X] ASDF dependencies,
  - [X] Git submodules,
    ```sh
	cd /path/to/nyxt/checkout
    git submodule add https://gitlab.common-lisp.net/nyxt/py-configparser _build/py-configparser
    ```
  - [X] and Guix dependencies.
- [X] My code follows the style guidelines for Common Lisp code. See:
  - [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf)
  - [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml)
- [X] I have performed a self-review of my own code.
- [ ] My code has been reviewed by at least one peer.  (The peer review to approve a PR counts.  The reviewer must download and test the code.)
- [X] Documentation:
  - [X] All my code has docstrings and `:documentation`s written in the aforementioned style.  (It's OK to skip the docstring for really trivial parts.)
  - [X] I have updated the existing documentation to match my changes.
  - [X] I have commented my code in hard-to-understand areas.
  - [X] I have updated the `changelog.lisp` with my changes if it's anything user-facing (new features, important bug fix, compatibility breakage).
  - [X] I have added a `migration.lisp` entry for all compatibility-breaking changes.
  - [X] (If this changes something about the features showcased on Nyxt website) I have these changes described in the new/existing article at Nyxt website or will notify one of maintainters to do so.
- [X] Compilation and tests:
  - [X] My changes generate no new warnings.
  - [X] I have added tests that prove my fix is effective or that my feature works.  (If possible.)
  - [X] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by aartaka** [comment]
So, merging? Even though it's a new syntax, it is consistent with our other changes, like switching to LASS and recent `:ncode` refactoring.

**Comment by aadcg** [comment]
@aartaka I can't possibly think of any reason to oppose this PR! 

Nonetheless, perhaps an additional look by @Ambrevar wouldn't hurt :)

**Comment by aartaka** [comment]
> Nonetheless, perhaps an additional look by Ambrevar wouldn't hurt :)

So be it then.

**Comment by Ambrevar** [comment]
I'm not very knowledgeable about this part of the code base, but looks good to me from a quick looksy!

**Comment by aartaka** [comment]
Merged with eb68f62c03118dfdda8a822470e09f403eec398d, thanks!

**Pull request merged**
