### PR TITLE
urls: Memoize lookup-hostname.

### PR DESCRIPTION
**Pull request by Ambrevar**
iolib/sockets:lookup-hostname is particularly slow.  Memoizing it works around
this issue.  In practice, many URLs tend to come from the same hosts.

### CODE REVIEW

**Comment by aartaka** [comment]
All good, although I feel that `defmemo` (or something like it) should have been part of some utility library...

**Comment by Ambrevar** [comment]
I could find a definition in
https://github.com/AccelerationNet/function-cache and fare-memoization.

**Comment by Ambrevar** [comment]
https://gitlab.common-lisp.net/frideau/fare-memoization

**Comment by aartaka** [comment]
I mean, it feels likebelonging to Alexandria or Serapeum. Anyway, thanks for the patch and references!

**Comment by Ambrevar** [comment]
Should we add the fare-memoization or function-cache dependency to Nyxt
then?

The defmemo definition I've used here is very basic.
Among others, it does not time out and it's not thread-safe.

**Comment by jmercouris** [comment]
I would suggest let's wait on introducing a new library. First let's see if both of those problems arise.

**Comment by Ambrevar** [comment]
It's not urgent for sure and I've already put a TODO: comment so we remember.  I'll
merge then.

**Pull request merged**
