### PR TITLE
Port tests

### PR DESCRIPTION
**Pull request by aadcg**
# Description

A very incomplete attempt at porting the test to the new chosen library. In the process, I'm getting acquainted with `lisp-unit2`, which will be helpful regardless. 

Will work on this on Monday too, and get as far as possible. I'm afraid you'll be on your own after that @Ambrevar.

# Discussion

# Checklist:
(to be ticked by @Ambrevar)
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [x] I have pulled from master before submitting this PR
- [x] I've added the new dependencies as:
  - [x] ASDF dependencies,
  - [x] Git submodules,
  - [x] and Guix dependencies.
- [x] My code follows the style guidelines for Common Lisp code
  - See [Norvig & Pitman's Tutorial on Good Lisp Programming Style (PDF)](https://www.cs.umd.edu/~nau/cmsc421/norvig-lisp-style.pdf) and [Google Common Lisp Style Guide](https://google.github.io/styleguide/lispguide.xml).
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by aadcg** [comment]
@Ambrevar this is as far as I could get.

I tried to map the logic from `prove` to `lisp-unit2` as best as I could, but I didn't look very deeply into details.

[Integration with ASDF is missing](https://github.com/AccelerationNet/lisp-unit2#asdf).

**Comment by aadcg** [comment]
For reference, I've run most tests manually with:

```lisp
(run-tests :package :name-of-the-package
           :run-contexts #'with-summary-context)
```

and most of them passed. I left comments when they didn't. Hope this helps.

**Comment by Ambrevar** [comment]
We don't use ASDF integration (like `prove-asdf` if this is what you meant).  To be able to call `(asdf:test-system :nyxt)`, look at how I did it for nfiles and nkeymaps.  It's no problem at all.

Thanks for your work! :)

**Comment by Ambrevar** [comment]
The reason why the `nyxt/class-star` tests failed is because `assert-typep` checks the type of a value, but here `(getf (mopu:slot-properties 'foo-type-infer 'name) :type)` returns a type name.  So we only need to compare 2 symbols.

Does that make sense?

**Comment by Ambrevar** [comment]
@aadcg: Note that to properly remove a git submodule, you should not edit the `.gitmodules` file but instead do

```sh
git rm _build/prove
```

**Comment by Ambrevar** [comment]
The gi-gtk tests are broken, but they are also broken on master.

@aartaka Any idea?

**Comment by Ambrevar** [comment]
Argh, it's `nyxt::*interactive-p*` again! :(
(You must hate me now... OK, let's make this a very high priority issue!)

**Comment by Ambrevar** [comment]
To do:

- [ ] Port `nyxt/application/tests`.
- [ ] Port OSPM.   Actually, time to use https://github.com/atlas-engineer/ospm.

**Comment by Ambrevar** [comment]
All done.

@aartaka Can you have a quick look and confirm it's good to merge?
Note that this requires the `ospm` library, so either clone it to your ~/common-lisp or `guix pull`.

**Comment by aartaka** [comment]
On it!

**Comment by aartaka** [comment]
Right now it fails with 
```
Component "nyxt/download-manager/tests" not found, required by
#<NYXT-SYSTEM "nyxt">
   [Condition of type ASDF/FIND-COMPONENT:MISSING-DEPENDENCY]
```

Am I missing something? Seems like this system is no longer in `nyxt.asd`...

**Comment by aartaka** [comment]
OK, now it works, tests pass, and it omits reasonable report.

**Comment by aartaka** [comment]
@Ambrevar, any reason to remove `download-manager` tests?

**Comment by Ambrevar** [comment]
OK  to merge then?

**Comment by aartaka** [comment]
OK to merge!

**Comment by aadcg** [comment]
Thanks for continuing this work @Ambrevar.

**Pull request merged**
