### PR TITLE
Nix

### PR DESCRIPTION
**Pull request by bqv**
@jmercouris

### CODE REVIEW

**Comment by jmercouris** [comment]
Thank you, will take a look!

**Comment by jmercouris** [comment]
Would it be possible to move this into the build-scripts?

**Comment by bqv** [comment]
All three of those files are meant to be in the root, really. If you were desperate you can delete shell.nix, it's not really necessary here

**Comment by jmercouris** [comment]
I was afraid that would be the answer... I tried moving it myself and experienced some problems.

**Comment by aartaka** [comment]
I may be out of context here, but can symlinking help in keeping things in the `build-scripts/`? Like
- Have all the three new files in the `build-scripts/`.
- Have a `nix-install.sh` script that will:
    - Symlink/copy all the three files to root.
    - Run `nix-env` (or whatever it is that installs packages on Nix) on these files.
    - Do cleanup when necessary.

Does that fit the Nix style? Shell scripts are discouraged in functional world, so I might be suggesting nonsense :)

**Comment by bqv** [comment]
The main issue is that for the flake.nix to work, it needs to be committed at the root of the git repository, so there's no real messing with that. The default.nix is less of an issue, but given people tend to like to `import ./.` and `nix build` in the root, it breaks a bit of ergonomicity. The shell.nix is pretty unnecessary as i mentioned, especially given none of you use nix to dev

**Comment by jmercouris** [comment]
I use NixOS to develop, I am only on the system about 1 month now though, so I am quite ignorant still. I use the shell.nix file located in our build-scripts directory.

**Comment by bqv** [comment]
Fixed the missing calispel dependency by using lisp-overlay

**Comment by jmercouris** [comment]
Will test again today, thank you!

**Comment by jmercouris** [comment]
Thank you!

**Pull request merged**
